// cmd/gen-cli/main.go — README generator for the CLI command catalogue.
//
// Run via:  go run ./cmd/gen-cli
//
// Or from cmd/mpm/:  go run ../gen-cli
//
// The generator uses go/parser + go/ast to extract the r.Commands
// map literal from cmd/mpm/router.go and rewrites the block between
// sentinel comments in README.md with a markdown catalogue.
//
// Why this exists: manual sync of CLI commands to README is drift-prone
// (same problem the MCP tools catalogue had — fixed via cmd/gen-readme).
// With this generator, the doc invariant becomes "I added a command
// to router.go and ran `go run ./cmd/gen-cli` — the README is now correct."
//
// Scope note: this walks r.Commands at the top level. Subcommand
// surfaces (mpm kb memory list, mpm ops gc, etc.) are dispatched via
// handlers_*.go and are NOT captured here. The README's manually-
// written subsections for kb/ops/debug remain the source of truth for
// subcommand enumeration.

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

const (
	readmeBeginSentinel = "<!-- cli:begin — auto-generated by `go run ./cmd/gen-cli`. Do not edit by hand. -->"
	readmeEndSentinel   = "<!-- cli:end — auto-generated by `go run ./cmd/gen-cli`. Do not edit by hand. -->"
)

type entry struct {
	name        string
	description string
	aliases     []string
	minArgs     int
	maxArgs     int
}

func main() {
	if err := run("cmd/mpm/router.go", "README.md"); err != nil {
		fmt.Fprintf(os.Stderr, "gen_cli: %v\n", err)
		os.Exit(1)
	}
}

func run(routerPath, readmePath string) error {
	entries, err := extractCommands(routerPath)
	if err != nil {
		return fmt.Errorf("extract commands from %s: %w", routerPath, err)
	}

	data, err := os.ReadFile(readmePath)
	if err != nil {
		return fmt.Errorf("read %s: %w", readmePath, err)
	}
	content := string(data)

	beginIdx := strings.Index(content, readmeBeginSentinel)
	endIdx := strings.Index(content, readmeEndSentinel)
	if beginIdx < 0 || endIdx < 0 || endIdx < beginIdx {
		return fmt.Errorf("README missing one or both sentinels — add them around the CLI catalogue block:\n  %s\n  %s",
			readmeBeginSentinel, readmeEndSentinel)
	}

	generated := renderCatalogue(entries)

	before := content[:beginIdx]
	after := content[endIdx+len(readmeEndSentinel):]
	newContent := before + readmeBeginSentinel + "\n" + generated + "\n" + readmeEndSentinel + after

	if err := os.WriteFile(readmePath, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write %s: %w", readmePath, err)
	}
	fmt.Printf("Updated %s with %d top-level commands.\n", readmePath, len(entries))
	return nil
}

// extractCommands parses the router.go source and extracts the r.Commands
// map literal — name, description, aliases, min/max args for each entry.
func extractCommands(path string) ([]entry, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var entries []entry

	ast.Inspect(f, func(n ast.Node) bool {
		as, ok := n.(*ast.AssignStmt)
		if !ok || len(as.Lhs) != 1 || len(as.Rhs) != 1 {
			return true
		}
		// Match `r.Commands = ...`
		sel, ok := as.Lhs[0].(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Commands" {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if !ok || ident.Name != "r" {
			return true
		}
		mapLit, ok := as.Rhs[0].(*ast.CompositeLit)
		if !ok {
			return true
		}

		for _, elt := range mapLit.Elts {
			kv, ok := elt.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			keyLit, ok := kv.Key.(*ast.BasicLit)
			if !ok || keyLit.Kind != token.STRING {
				continue
			}
			name := strings.Trim(keyLit.Value, `"`)
			cmdLit, ok := kv.Value.(*ast.CompositeLit)
			if !ok {
				continue
			}
			e := entry{name: name}
			for _, field := range cmdLit.Elts {
				fkv, ok := field.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				fname, ok := fkv.Key.(*ast.Ident)
				if !ok {
					continue
				}
				switch fname.Name {
				case "Name":
					if lit, ok := fkv.Value.(*ast.BasicLit); ok && lit.Kind == token.STRING {
						e.name = strings.Trim(lit.Value, `"`)
					}
				case "Description":
					if lit, ok := fkv.Value.(*ast.BasicLit); ok && lit.Kind == token.STRING {
						e.description = strings.Trim(lit.Value, `"`)
					}
				case "Aliases":
					if slice, ok := fkv.Value.(*ast.CompositeLit); ok {
						for _, a := range slice.Elts {
							if lit, ok := a.(*ast.BasicLit); ok && lit.Kind == token.STRING {
								e.aliases = append(e.aliases, strings.Trim(lit.Value, `"`))
							}
						}
					}
				case "MinArgs":
					if lit, ok := fkv.Value.(*ast.BasicLit); ok && lit.Kind == token.INT {
						fmt.Sscanf(lit.Value, "%d", &e.minArgs)
					}
				case "MaxArgs":
					if lit, ok := fkv.Value.(*ast.BasicLit); ok && lit.Kind == token.INT {
						fmt.Sscanf(lit.Value, "%d", &e.maxArgs)
					}
				}
			}
			entries = append(entries, e)
		}
		return false // Already consumed the Commands assignment
	})

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})
	return entries, nil
}

func renderCatalogue(entries []entry) string {
	var sb strings.Builder
	sb.WriteString("\n### Command Catalogue (auto-generated)\n\n")
	sb.WriteString("Top-level commands registered in `cmd/mpm/router.go`. ")
	sb.WriteString("Subcommand surfaces (e.g. `mpm kb memory list`, `mpm ops gc`) ")
	sb.WriteString("are dispatched via `handlers_*.go` and documented manually in the ")
	sb.WriteString("subsections above. Regenerate this block with `go run ./cmd/gen-cli`.\n\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "- **`%s`**", e.name)
		if len(e.aliases) > 0 {
			fmt.Fprintf(&sb, " _(aliases: %s)_", strings.Join(e.aliases, ", "))
		}
		if e.description != "" {
			// Escape backticks to keep markdown code spans valid.
			desc := strings.ReplaceAll(e.description, "`", "'")
			fmt.Fprintf(&sb, " — %s", desc)
		}
		fmt.Fprintln(&sb)
	}
	return sb.String()
}