// instructions_primer_drift_test.go — pin the embedded instructions
// primer to the canonical renderer's output.
//
// The primer string embedded in main.go (instructionsPrimer) is
// generated by `agent_installation/scripts/render_managed_blocks.py
// --dump instructions` and committed alongside the source as
// instructions_primer.txt. The renderer derives the primer's
// imperative headers and primary tool references from the canonical
// managed block, so the primer cannot drift from
// MPM_AGENT_INTEGRATION_SNIPPETS.md without this test failing.
//
// Two failure modes are caught:
//
//  1. The snippets file changes and the primer was not regenerated.
//     The Python `--check` mode in render_managed_blocks.py catches
//     this on the Python side; this Go test catches it on the Go
//     side by re-running the renderer and comparing to the constant
//     baked into the binary.
//
//  2. Someone hand-edits instructions_primer.txt (or the
//     instructionsPrimer constant) without re-running the renderer.
//     The drift is detected here because the renderer's output
//     diverges from the checked-in text.
//
// **Brittleness notice.** This test is INTENTIONALLY strict —
// byte-for-byte equality between the embedded primer and the
// rendered output. A failure here is NOT automatically a bug to route
// around or work around; it is a gate.
//
// On a failure, the contributor who triggered it must stop and
// figure out which of two cases they are in:
//
//	(a) You changed the canonical managed block (or the renderer's
//	    header/footer template) deliberately. This is fine — the
//	    canonical contract has changed and the primer should track
//	    it. Update the embedded file by re-running
//	    `python3 agent_installation/scripts/render_managed_blocks.py
//	    --dump instructions > cmd/mpm-mcp/instructions_primer.txt`
//	    (the write mode does this automatically). The change goes in
//	    the same commit as the canonical-block edit; the test
//	    message names which direction the drift ran.
//
//	(b) You did not intend the change. This is a real regression
//	    against the audited contract; back out the offending edit
//	    before merging.
//
// Do NOT loosen the byte-equality comparison (e.g. by trimming
// whitespace, dropping lines, or asserting substring-only) to make a
// failure go away. Loosening the gate removes the gate; the drift
// exists because this kind of silent divergence is otherwise
// invisible.
package main

import (
	"bytes"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestInstructionsPrimerDrift_MatchesRenderer verifies that the
// string baked into the binary is byte-for-byte identical to what the
// canonical renderer would produce from the current snippets source.
// A failure here means the embedded primer has drifted away from the
// canonical contract.
func TestInstructionsPrimerDrift_MatchesRenderer(t *testing.T) {
	// Locate the renderer. The script lives at
	// agent_installation/scripts/render_managed_blocks.py relative
	// to the repo root, which is two parents up from this test
	// file's directory (cmd/mpm-mcp/).
	rendererPath := filepath.Join(
		"..", "..", "agent_installation", "scripts", "render_managed_blocks.py",
	)
	abs, err := filepath.Abs(rendererPath)
	if err != nil {
		t.Fatalf("renderer path abs: %v", err)
	}
	if _, err := exec.LookPath("python3"); err != nil {
		t.Skipf("python3 not on PATH; cannot run renderer drift check: %v", err)
	}

	cmd := exec.Command("python3", abs, "--dump", "instructions")
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("renderer exited non-zero: %v\nstderr:\n%s", err, stderr.String())
	}
	rendered := stdout.String()

	if rendered != instructionsPrimer {
		// Build a unified-diff-style hint that names the source of
		// each side so the failing reader can tell at a glance which
		// direction the drift ran (canonical -> baked, or baked ->
		// canonical). We don't pull in a diff library here — the
		// short string is small enough that length + first differing
		// byte is enough to diagnose.
		t.Errorf(
			"embedded instructions primer has drifted from the canonical renderer output.\n"+
				"  embedded (cmd/mpm-mcp/main.go: instructionsPrimer, baked from instructions_primer.txt): %d bytes\n"+
				"  rendered (python3 render_managed_blocks.py --dump instructions):                     %d bytes\n"+
				"If the canonical managed block changed deliberately, regenerate the primer:\n"+
				"  python3 agent_installation/scripts/render_managed_blocks.py --dump instructions > cmd/mpm-mcp/instructions_primer.txt\n"+
				"If the embedded file was edited by hand, revert and re-run the renderer.\n"+
				"\n--- first 200 chars of rendered ---\n%s\n--- first 200 chars of embedded ---\n%s",
			len(instructionsPrimer), len(rendered),
			truncate(rendered, 200), truncate(instructionsPrimer, 200),
		)
	}
}

// truncate returns at most n chars of s, with an ellipsis marker if
// truncated. Used for diagnostic output only.
func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "...[truncated]"
}

// TestInstructionsPrimer_NonEmptyAndStructured guards against the
// pathological case where the embedded file is empty or missing its
// recognisable shape (header line + bullet items + footer line). This
// is a sanity check independent of the renderer; the renderer
// itself enforces these properties, but the binary could in principle
// be built from a partial checkout where the embed source was empty.
func TestInstructionsPrimer_NonEmptyAndStructured(t *testing.T) {
	if strings.TrimSpace(instructionsPrimer) == "" {
		t.Fatal("embedded instructions primer is empty — instructions_primer.txt missing or empty?")
	}
	// The canonical header starts with "MPM behavioral contract loaded."
	if !strings.HasPrefix(instructionsPrimer, "MPM behavioral contract loaded.") {
		t.Errorf(
			"embedded primer does not start with the canonical header line.\n"+
				"first 80 chars: %q", truncate(instructionsPrimer, 80),
		)
	}
	// The canonical footer mentions the CLI fallback contract.
	if !strings.Contains(instructionsPrimer, "fall back to `mpm call") {
		t.Errorf(
			"embedded primer is missing the CLI-fallback footer.\n"+
				"content:\n%s", instructionsPrimer,
		)
	}
	// Each numbered invariant in the canonical block must contribute
	// at least one bullet, so the primer must contain at least three
	// bullet lines (Wake, Persist, Handoff are non-negotiable).
	bullets := 0
	for _, line := range strings.Split(instructionsPrimer, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "- ") {
			bullets++
		}
	}
	if bullets < 3 {
		t.Errorf(
			"embedded primer has only %d bullets; expected at least 3 (Wake, Persist, Handoff are non-negotiable)",
			bullets,
		)
	}
}
