// instructions_primer_drift_test.go — pin the embedded instructions
// primer to the canonical renderer's output.
//
// The primer string embedded in main.go (instructionsPrimer) is
// generated by `agent_installation/scripts/render_managed_blocks.py
// --dump instructions` and committed alongside the source as
// instructions_primer.txt. The renderer derives the primer's
// imperative headers and primary tool references from the canonical
// managed block, so the primer cannot drift from
// MPM_AGENT_INTEGRATION_SNIPPETS.md without this test failing.
//
// Two failure modes are caught:
//
//  1. The snippets file changes and the primer was not regenerated.
//     The Python `--check` mode in render_managed_blocks.py catches
//     this on the Python side; this Go test catches it on the Go
//     side by re-running the renderer and comparing to the constant
//     baked into the binary.
//
//  2. Someone hand-edits instructions_primer.txt (or the
//     instructionsPrimer constant) without re-running the renderer.
//     The drift is detected here because the renderer's output
//     diverges from the checked-in text.
//
// **Brittleness notice.** This test is INTENTIONALLY strict —
// byte-for-byte equality between the embedded primer and the
// rendered output. A failure here is NOT automatically a bug to route
// around or work around; it is a gate.
//
// On a failure, the contributor who triggered it must stop and
// figure out which of two cases they are in:
//
//	(a) You changed the canonical managed block (or the renderer's
//	    header/footer template) deliberately. This is fine — the
//	    canonical contract has changed and the primer should track
//	    it. Update the embedded file by re-running
//	    `python3 agent_installation/scripts/render_managed_blocks.py
//	    --dump instructions > cmd/mpm-mcp/instructions_primer.txt`
//	    (the write mode does this automatically). The change goes in
//	    the same commit as the canonical-block edit; the test
//	    message names which direction the drift ran.
//
//	(b) You did not intend the change. This is a real regression
//	    against the audited contract; back out the offending edit
//	    before merging.
//
// Do NOT loosen the byte-equality comparison (e.g. by trimming
// whitespace, dropping lines, or asserting substring-only) to make a
// failure go away. Loosening the gate removes the gate; the drift
// exists because this kind of silent divergence is otherwise
// invisible.
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/flowbyte-com/mpm-core/tools"
)

// TestInstructionsPrimerDrift_MatchesRenderer verifies that the
// string baked into the binary is byte-for-byte identical to what the
// canonical renderer would produce from the current snippets source.
// A failure here means the embedded primer has drifted away from the
// canonical contract.
func TestInstructionsPrimerDrift_MatchesRenderer(t *testing.T) {
	// Locate the renderer. The script lives at
	// agent_installation/scripts/render_managed_blocks.py relative
	// to the repo root, which is two parents up from this test
	// file's directory (cmd/mpm-mcp/).
	rendererPath := filepath.Join(
		"..", "..", "agent_installation", "scripts", "render_managed_blocks.py",
	)
	abs, err := filepath.Abs(rendererPath)
	if err != nil {
		t.Fatalf("renderer path abs: %v", err)
	}
	if _, err := exec.LookPath("python3"); err != nil {
		t.Skipf("python3 not on PATH; cannot run renderer drift check: %v", err)
	}

	cmd := exec.Command("python3", abs, "--dump", "instructions")
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("renderer exited non-zero: %v\nstderr:\n%s", err, stderr.String())
	}
	rendered := stdout.String()

	if rendered != instructionsPrimer {
		// Build a unified-diff-style hint that names the source of
		// each side so the failing reader can tell at a glance which
		// direction the drift ran (canonical -> baked, or baked ->
		// canonical). We don't pull in a diff library here — the
		// short string is small enough that length + first differing
		// byte is enough to diagnose.
		t.Errorf(
			"embedded instructions primer has drifted from the canonical renderer output.\n"+
				"  embedded (cmd/mpm-mcp/main.go: instructionsPrimer, baked from instructions_primer.txt): %d bytes\n"+
				"  rendered (python3 render_managed_blocks.py --dump instructions):                     %d bytes\n"+
				"If the canonical managed block changed deliberately, regenerate the primer:\n"+
				"  python3 agent_installation/scripts/render_managed_blocks.py --dump instructions > cmd/mpm-mcp/instructions_primer.txt\n"+
				"If the embedded file was edited by hand, revert and re-run the renderer.\n"+
				"\n--- first 200 chars of rendered ---\n%s\n--- first 200 chars of embedded ---\n%s",
			len(instructionsPrimer), len(rendered),
			truncate(rendered, 200), truncate(instructionsPrimer, 200),
		)
	}
}

// truncate returns at most n chars of s, with an ellipsis marker if
// truncated. Used for diagnostic output only.
func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "...[truncated]"
}

// TestInstructionsPrimer_NonEmptyAndStructured guards against the
// pathological case where the embedded file is empty or missing its
// recognisable shape (header line + bullet items + footer line). This
// is a sanity check independent of the renderer; the renderer
// itself enforces these properties, but the binary could in principle
// be built from a partial checkout where the embed source was empty.
func TestInstructionsPrimer_NonEmptyAndStructured(t *testing.T) {
	if strings.TrimSpace(instructionsPrimer) == "" {
		t.Fatal("embedded instructions primer is empty — instructions_primer.txt missing or empty?")
	}
	// The canonical header starts with "MPM behavioral contract loaded."
	if !strings.HasPrefix(instructionsPrimer, "MPM behavioral contract loaded.") {
		t.Errorf(
			"embedded primer does not start with the canonical header line.\n"+
				"first 80 chars: %q", truncate(instructionsPrimer, 80),
		)
	}
	// The canonical footer mentions the CLI fallback contract.
	if !strings.Contains(instructionsPrimer, "fall back to `mpm call") {
		t.Errorf(
			"embedded primer is missing the CLI-fallback footer.\n"+
				"content:\n%s", instructionsPrimer,
		)
	}
	// Each numbered invariant in the canonical block must contribute
	// at least one bullet, so the primer must contain at least three
	// bullet lines (Wake, Persist, Handoff are non-negotiable).
	bullets := 0
	for _, line := range strings.Split(instructionsPrimer, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "- ") {
			bullets++
		}
	}
	if bullets < 3 {
		t.Errorf(
			"embedded primer has only %d bullets; expected at least 3 (Wake, Persist, Handoff are non-negotiable)",
			bullets,
		)
	}
}

// requiredPrimerConcepts lists the discoverability substrings that the
// MCP protocol-level `instructions` field MUST teach an agent
// connecting through mpm-mcp today. Each entry is a substring the
// primer must contain; missing or stale entries are surface-level
// regressions (the agent would arrive without the orientation it
// needs to use the post-discoverability MPM substrate correctly).
//
// These checks are semantic — substring presence — not exact-string
// snapshots. They are deliberately loose enough to survive natural
// prose tightening in the canonical renderer (the byte-level
// equality test above is the authoritative drift guard for the
// renderer's output; this guard catches *semantic* regressions where
// the renderer output drifts away from the discoverability
// architecture). Changes here MUST stay in lock-step with the
// architecture pinned by `internal/core/tools/compact_surface_filter_test.go`
// (3-tool compact surface — intentionally fixed at mpm_memory /
// mpm_context / mpm_help; full Registry + mpm_help closure derived
// at runtime via `len(Registry) + 1`)
// and the wake-envelope contract in `internal/core/wake_context.go`.
var requiredPrimerConcepts = []string{
	// Compact initial surface: the three tools an MCP client sees
	// when connecting.
	"`mpm_memory`",
	"`mpm_context`",
	"`mpm_help`",
	// Discovery: how the agent reaches the rest of the substrate.
	"`reach_via_cli`",
	// Tools/list filtering: hidden tools stay registered.
	"`tools/list`",
	// Substrate availability: CLI fallback + the
	// MPM_EXPOSE_ALL_TOOLS=1 escape hatch.
	"`MPM_EXPOSE_ALL_TOOLS=1`",
	"`mpm call <tool> --payload '{\"action\":\"<op>\",\"params\":{...}}'`",
	// Wake envelope: auto-injection (bullet 1 + footer cover the
	// literal "read_wake_context"; here we assert that the wake
	// payload shape is named).
	"`read_wake_context`",
	// Wake envelope: contextual_focus as inherited working
	// awareness, NOT a ranking.
	"`<contextual_focus>`",
	"inherited working awareness",
	"NOT a ranking",
	// Wake envelope: recent_activity as factual history,
	// observational, not ranked.
	"`recent_activity`",
	"observational, not ranked",
	// Wake envelope: contextual_candidates as diagnostic / routing,
	// NOT for normal startup, NOT a ranking mechanism.
	"`contextual_candidates`",
	"NOT for normal startup",
}

// TestInstructionsPrimer_CoversDiscoverabilityConcepts guards
// against the primer drifting into a "behavioural contract only"
// shape — the kind of drift that misses what the model needs to
// know about the post-discoverability architecture (compact
// surface, mpm_help discovery, hidden Registry tools, CLI
// fallback, wake-context shape, contextual_focus /
// recent_activity / contextual_candidates semantics).
//
// The primer must mention each substring in requiredPrimerConcepts.
// A failure here means the primer has lost its orienting layer; the
// agent will not know how to find specialists, what the wake
// envelope carries, or when recent_activity vs contextual_candidates
// is the right tool.
func TestInstructionsPrimer_CoversDiscoverabilityConcepts(t *testing.T) {
	for _, want := range requiredPrimerConcepts {
		if !strings.Contains(instructionsPrimer, want) {
			t.Errorf(
				"embedded primer is missing required discoverability concept %q.\n"+
					"The MCP `instructions` field must orient the agent on the\n"+
					"post-discoverability surface. Update either the primer\n"+
					"or the requiredPrimerConcepts table; do not weaken the\n"+
					"substring check to make this go away.",
				want,
			)
		}
	}
}

// TestInstructionsPrimer_ReferenceRetrievalContract pins the
// reference-retrieval contract that the previous experiment found
// was missing from the agent contract: the canonical managed block
// and the MCP instructions primer must BOTH direct the agent to
// query the existing MPM reference corpus (via `mpm_references`
// action `search`) before reacquiring the same source. The fix
// added item 9 ("Search the reference corpus before reacquiring")
// to the managed block AND the corresponding primer bullet.
//
// A failure here means one of the two artefacts has lost the
// directive: the agent would fall back to acquiring the same
// reference instead of checking what MPM already knows.
//
// The substring is the tool invocation as it appears in both
// documents: the canonical block uses the host-neutral form
// `` `mpm_references` action `search` ``; the primer is rendered
// from the same source so the substring matches verbatim. We check
// the embedded primer AND the canonical managed block read fresh
// from disk so a regression on either side is caught.
func TestInstructionsPrimer_ReferenceRetrievalContract(t *testing.T) {
	// Embedded primer must mention the new directive.
	primerSubstr := "`mpm_references` action `search`"
	if !strings.Contains(instructionsPrimer, primerSubstr) {
		t.Errorf(
			"embedded instructions primer is missing the reference-retrieval contract substring %q.\n"+
				"The primer must tell the agent to query the existing reference corpus via "+
				"`mpm_references` action `search` before reacquiring the same source.\n"+
				"Regenerate via `python3 agent_installation/scripts/render_managed_blocks.py` "+
				"after editing the canonical managed block in "+
				"agent_installation/MPM_AGENT_INTEGRATION_SNIPPETS.md.",
			primerSubstr,
		)
	}

	// Canonical managed block (read fresh from disk, so a future
	// edit that drops the directive from the canonical source
	// without regenerating the primer is caught here even if the
	// primer still embeds the old text).
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("repo root abs: %v", err)
	}
	canonicalPath := filepath.Join(
		repoRoot, "agent_installation", "MPM_AGENT_INTEGRATION_SNIPPETS.md",
	)
	canonicalBytes, err := os.ReadFile(canonicalPath)
	if err != nil {
		t.Fatalf("read canonical snippets: %v", err)
	}
	canonical := string(canonicalBytes)
	if !strings.Contains(canonical, "Search the reference corpus before reacquiring") {
		t.Errorf(
			"canonical managed block (%s) is missing the "+
				"'Search the reference corpus before reacquiring' item.\n"+
				"The managed block is the source of truth for the contract; "+
				"the primer is derived from it. Restore the item in the canonical "+
				"source and re-run the renderer.",
			canonicalPath,
		)
	}
	// The canonical block must wire both the tool name and the
	// action — independently, since the canonical source wraps
	// them across a line break — so the per-adapter renderer's
	// host-prefix substitution has something concrete to operate
	// on.
	if !strings.Contains(canonical, "`mpm_references`") {
		t.Errorf(
			"canonical managed block is missing the host-neutral "+
				"tool reference `mpm_references` that the per-adapter "+
				"renderer prefixes to produce the host-specific form.",
		)
	}
	if !strings.Contains(canonical, "action `search`") {
		t.Errorf(
			"canonical managed block is missing the `action \\`search\\`` "+
				"invocation keyword that pairs the tool with the action.",
		)
	}
	// And it must include the CLI-fallback example the contract
	// promises, so the recovery path is consistent with the rest of
	// the contract.
	if !strings.Contains(canonical, "mpm call mpm_references --payload") {
		t.Errorf(
			"canonical managed block is missing the CLI-fallback example for "+
				"`mpm_references` action `search`. Add the mpm call invocation "+
				"so the recovery path matches the rest of the contract.",
		)
	}
}

// TestInstructionsPrimer_NoStaleSurfaceCounts guards against
// historical tool counts hard-coded into the primer going stale
// when the Registry grows. The primer describes the
// discoverability model qualitatively ("the rest of the
// substrate", "every registered tool", "`mpm call <tool>`"); any
// literal numeric count embedded in prose is a candidate for
// staleness.
//
// Today the Registry has 21 entries (live-derived via
// `compact_surface_filter_test.go::TestCompactSurface_FullRegistryPreserved`).
// If the primer ever hard-codes a count, this test enforces that
// the count equals `len(tools.Registry) + 1` (the +1 is for the
// `mpm_help` discovery closure that is registered via
// `cmd/mpm-mcp/tools.go::RegisterAllTools` rather than via the
// Registry slice). A test failure here either means someone
// hand-edited a stale count into the primer (revert it) or the
// Registry grew and the primer needs a regeneration to either
// drop the literal count or update it.
func TestInstructionsPrimer_NoStaleSurfaceCounts(t *testing.T) {
	// We import tools via the public path used by the rest of
	// cmd/mpm-mcp. Importing only for `len(Registry)` keeps this
	// test small.
	wantFull := len(tools.Registry) + 1 // Registry + mpm_help closure
	wantRegistry := len(tools.Registry)

	// If the primer mentions a hard-coded "3" as the surface
	// count, it must equal len(defaultCoreTools) — currently 3.
	// We assert positive: today's primer mentions "3-tool compact
	// MCP surface" (a correct hard-coded count for the compact
	// surface). If the surface grows, this substring changes and
	// the test fires.
	if !strings.Contains(instructionsPrimer, "3-tool compact MCP surface") {
		t.Logf(
			"NOTE: primer does not contain the literal '3-tool compact MCP surface'; "+
				"either the surface grew past 3 (Registry says %d, full surface says %d) "+
				"or the framing changed. Update this test if the framing is now correct.",
			wantRegistry, wantFull,
		)
	}

	// Catch-and-fail on any hard-coded "21 Registry" or "22-tool"
	// wording if it contradicts the live Registry size. The primer
	// today does NOT carry such wording (the framing is qualitative),
	// so the test should pass silently. If a future edit pins a
	// numeric count, the test will catch any drift.
	if strings.Contains(instructionsPrimer, "21 Registry") {
		if !strings.Contains(instructionsPrimer, fmt.Sprintf("%d Registry", wantRegistry)) {
			t.Errorf(
				"primer mentions '21 Registry' but live Registry has %d entries; "+
					"either update the primer or drop the literal count",
				wantRegistry,
			)
		}
	}
	if strings.Contains(instructionsPrimer, "22-tool") ||
		strings.Contains(instructionsPrimer, "22 tool") {
		if !strings.Contains(instructionsPrimer, fmt.Sprintf("%d-tool", wantFull)) &&
			!strings.Contains(instructionsPrimer, fmt.Sprintf("%d tool", wantFull)) {
			t.Errorf(
				"primer mentions a '22-tool' / '22 tool' surface but live Registry+closure=%d; "+
					"either update the primer or drop the literal count",
				wantFull,
			)
		}
	}
}
