#!/usr/bin/env python3
r"""
install_agents_instructions.py — Install OpenCode AGENTS.md with MPM
behavioral protocol, idempotently.

Usage:
    python3 install_agents_instructions.py \
        --scope user \                            # or 'project'
        --target "$HOME/project/AGENTS.md" \
        --snippet /path/to/AGENTS.md.snippet

For project scope, --target should be the project's AGENTS.md.
For user scope, --target should be ~/.config/opencode/AGENTS.md.

Behavior matches install_claude_instructions.py: idempotent, preserves
existing content, fails closed on corrupted target, backs up before any
modification.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path


MANAGED_BEGIN_RE = re.compile(r"<!-- BEGIN MPM-MANAGED SECTION:opencode-instructions(?: [^\n]*)?-->")
MANAGED_END_RE   = re.compile(r"<!-- END MPM-MANAGED SECTION:opencode-instructions(?: [^\n]*)?-->")
LEGACY_BEGIN_RE  = re.compile(r"<!-- BEGIN MPM-MANAGED SECTION(?:[: ][^\n]*| [^\n]*)?-->")
LEGACY_END_RE    = re.compile(r"<!-- END MPM-MANAGED SECTION(?:[: ][^\n]*| [^\n]*)?-->")

# Outer managed-section markers (must match renderer's copy_paste_outer_*).
OUTER_BEGIN = "<!-- BEGIN MPM-MANAGED SECTION:opencode-instructions -->"
OUTER_END   = "<!-- END MPM-MANAGED SECTION:opencode-instructions -->"

HEAD_COMMENT = """\
<!--
This file's AGENTS.md MPM section is managed by the mpm-opencode plugin's
install_agents_instructions.py. The block between BEGIN/END MPM-MANAGED
SECTION markers is regenerated by the installer; everything outside the
markers is preserved. To uninstall: python3 install_agents_instructions.py
--uninstall --target ...
-->"""


def footer() -> str:
    return OUTER_END


def build_managed_block(snippet_body: str) -> str:
    """Build the managed block to match the renderer's compose_snippet output
    exactly. The outer managed-section markers wrap the snippet body
    verbatim; the snippet itself already includes the inner
    <!-- BEGIN MPM MANAGED BLOCK --> / <!-- END MPM MANAGED BLOCK -->
    markers from the renderer's render_for_host.

    Earlier revisions of this function prepended a `<!-- generated: ... -->`
    timestamp and a `<!-- source: ... -->` line. Those were removed:
    they created a content-blinder where the installer's output never
    byte-matched the renderer's canonical output, so the
    check-installed-drift guard (3760e0e6) reported false-positive
    drift after every successful refresh. The body comparison below is
    the authoritative currency check: byte-equality between the
    extracted managed block and the rendered canonical block.
    """
    return f"{OUTER_BEGIN}\n{snippet_body.rstrip()}\n{OUTER_END}\n"


def install(scope: str, target: str, snippet_path: str) -> int:
    target_path = Path(target)
    snippet = Path(snippet_path).read_text()

    # Build the managed block from the canonical snippet. The result is
    # the same bytes the renderer (render_managed_blocks.py
    # compose_snippet) would produce today; the body comparison below
    # is therefore a byte-equality test against the canonical render
    # at the time of install.
    managed_block = build_managed_block(snippet)
    if not target_path.exists():
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(HEAD_COMMENT + "\n\n" + managed_block)
        print(f"[install_agents_instructions] wrote fresh {target_path}; scope={scope}")
        return 0
    existing = target_path.read_text()

    # Already managed — compare the extracted block against the
    # canonical render. If they match byte-for-byte, no-op. If they
    # differ, replace. The body is the entire managed block
    # (BEGIN+body+END), so the comparison catches both content
    # drift and any structural divergence from the renderer.
    if MANAGED_BEGIN_RE.search(existing) and MANAGED_END_RE.search(existing):
        # Normalize both sides to rstrip() before comparing: the regex
        # extraction does not include any trailing newline after the
        # END marker, and the canonical block has a trailing \n.
        # Without normalization, an otherwise-current file would
        # appear stale on every run (false-positive drift).
        new_managed = managed_block.rstrip()
        if (_extract_managed_block(existing) or "").rstrip() == new_managed:
            print(f"[install_agents_instructions] {target_path} already has current managed section; no-op")
            return 0
        backup = backup_path(target_path)
        shutil.copy2(target_path, backup)
        replaced = re.sub(
            MANAGED_BEGIN_RE.pattern + r".*?" + MANAGED_END_RE.pattern,
            new_managed,
            existing,
            flags=re.DOTALL,
        )
        target_path.write_text(replaced)
        print(
            f"[install_agents_instructions] {target_path} had stale managed "
            f"section — refreshed from snippet. backup at {backup}"
        )
        return 0

    # Legacy managed block -> replace in place.
    if LEGACY_BEGIN_RE.search(existing) and LEGACY_END_RE.search(existing):
        backup = backup_path(target_path)
        shutil.copy2(target_path, backup)
        m = re.search(
            LEGACY_BEGIN_RE.pattern + r".*?" + LEGACY_END_RE.pattern,
            existing, flags=re.DOTALL,
        )
        if not m:
            print(f"[install_agents_instructions] ERROR extracting legacy block; backup at {backup}", file=sys.stderr)
            return 2
        target_path.write_text(existing.replace(m.group(0), managed_block.rstrip() + "\n"))
        print(f"[install_agents_instructions] replaced legacy block in {target_path}; backup at {backup}")
        return 0

    # BEGIN without a matching END — corrupted file. Abort safely.
    #
    # Conservative handling: an orphan END (no BEGIN) in user content
    # is unusual but not catastrophic. The append path below will add
    # the managed block at the end of the file, leaving the orphan in
    # place. A BEGIN-without-END is the structurally dangerous case:
    # the regex below would walk past the missing END and consume
    # arbitrary file content as if it were inside the managed block.
    if MANAGED_BEGIN_RE.search(existing) and not MANAGED_END_RE.search(existing):
        backup = backup_path(target_path)
        shutil.copy2(target_path, backup)
        print(
            f"[install_agents_instructions] ERROR: {target_path} has "
            f"a BEGIN marker without a matching END; refusing to modify; "
            f"backup at {backup}",
            file=sys.stderr,
        )
        return 2

    # No managed block -> append.
    backup = backup_path(target_path)
    shutil.copy2(target_path, backup)
    insertion = "\n\n" + HEAD_COMMENT + "\n\n" + managed_block.rstrip() + "\n"
    target_path.write_text(existing.rstrip() + insertion)
    print(f"[install_agents_instructions] appended managed section to {target_path}; backup at {backup}; scope={scope}")
    return 0


def uninstall(target: str) -> int:
    target_path = Path(target)
    if not target_path.exists():
        print(f"[install_agents_instructions] no AGENTS.md at {target_path}; nothing to uninstall")
        return 0
    existing = target_path.read_text()
    for begin_re, end_re, label in (
        (MANAGED_BEGIN_RE, MANAGED_END_RE, "opencode"),
        (LEGACY_BEGIN_RE, LEGACY_END_RE, "legacy"),
    ):
        if begin_re.search(existing) and end_re.search(existing):
            backup = backup_path(target_path)
            shutil.copy2(target_path, backup)
            out = re.sub(begin_re.pattern + r".*?" + end_re.pattern, "", existing, flags=re.DOTALL)
            if out.strip() == HEAD_COMMENT.strip() or out.strip() == "":
                target_path.unlink()
                print(f"[install_agents_instructions] removed {label} section; unlinked empty file; backup at {backup}")
                return 0
            target_path.write_text(out)
            print(f"[install_agents_instructions] removed {label} section; backup at {backup}")
            return 0
    print(f"[install_agents_instructions] no managed section at {target_path}")
    return 0


def backup_path(target_path: Path) -> Path:
    parent = target_path.parent
    name = target_path.name + ".bak"
    i = 1
    p = parent / name
    while p.exists():
        p = parent / f"{target_path.name}.bak.{i}"
        i += 1
    return p


def _extract_managed_block(content: str) -> str | None:
    """Return the raw managed block (BEGIN/END inclusive) or None."""
    m = re.search(
        MANAGED_BEGIN_RE.pattern + r".*?" + MANAGED_END_RE.pattern,
        content,
        flags=re.DOTALL,
    )
    return m.group(0) if m else None


def main() -> int:
    ap = argparse.ArgumentParser(description="Install OpenCode AGENTS.md with MPM behavioral section, idempotently.")
    ap.add_argument("--scope", choices=("user", "project"), required=True)
    ap.add_argument("--target", required=True, help="Absolute path to AGENTS.md")
    ap.add_argument("--snippet", required=True, help="Path to the AGENTS.md.snippet")
    ap.add_argument("--uninstall", action="store_true")
    args = ap.parse_args()
    if args.uninstall:
        return uninstall(args.target)
    return install(args.scope, args.target, args.snippet)


if __name__ == "__main__":
    sys.exit(main())
