#!/usr/bin/env python3
r"""
install_agents_instructions.py — Install OpenCode AGENTS.md with MPM
behavioral protocol, idempotently.

Usage:
    python3 install_agents_instructions.py \
        --scope user \                            # or 'project'
        --target /home/user/project/AGENTS.md \
        --snippet /path/to/AGENTS.md.snippet

For project scope, --target should be the project's AGENTS.md.
For user scope, --target should be ~/.config/opencode/AGENTS.md.

Behavior matches install_claude_instructions.py: idempotent, preserves
existing content, fails closed on corrupted target, backs up before any
modification.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


MANAGED_BEGIN_RE = re.compile(r"<!-- BEGIN MPM-MANAGED SECTION:opencode-instructions(?: [^\n]*)?-->")
MANAGED_END_RE   = re.compile(r"<!-- END MPM-MANAGED SECTION:opencode-instructions(?: [^\n]*)?-->")
LEGACY_BEGIN_RE  = re.compile(r"<!-- BEGIN MPM-MANAGED SECTION(?:[: ][^\n]*| [^\n]*)?-->")
LEGACY_END_RE    = re.compile(r"<!-- END MPM-MANAGED SECTION(?:[: ][^\n]*| [^\n]*)?-->")

HEAD_COMMENT = """\
<!--
This file's AGENTS.md MPM section is managed by the opencode-mpm plugin's
install_agents_instructions.py. The block between BEGIN/END MPM-MANAGED
SECTION markers is regenerated by the installer; everything outside the
markers is preserved. To uninstall: python3 install_agents_instructions.py
--uninstall --target ...
-->"""


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


# Match the existing `<!-- generated: ... -->` comment so re-installs can
# preserve the original timestamp instead of bumping it every run. Without
# this, two consecutive installs (e.g. CI smoke + manual re-run) produce
# different bytes and trip the idempotency test.
_GENERATED_RE = re.compile(r"<!-- generated: (\d{8}T\d{6}Z) -->")


def _existing_generated(content: str) -> str | None:
    """Return the `<!-- generated: ... -->` timestamp from content's first
    managed block, or None if no managed block is present."""
    m = _GENERATED_RE.search(content)
    return m.group(1) if m else None


def banner(existing_ts: str | None = None) -> str:
    ts = existing_ts or now_iso()
    return f"""<!-- BEGIN MPM-MANAGED SECTION:opencode-instructions -->
<!-- generated: {ts} -->
<!-- source: ~/.mpm/agent_installation/opencode-mpm/templates/AGENTS.md.snippet -->"""


def footer() -> str:
    return "<!-- END MPM-MANAGED SECTION:opencode-instructions -->"


def build_managed_block(snippet_body: str, existing_ts: str | None = None) -> str:
    return f"{banner(existing_ts=existing_ts)}\n{snippet_body.rstrip()}\n{footer()}\n"


def install(scope: str, target: str, snippet_path: str) -> int:
    target_path = Path(target)
    snippet = Path(snippet_path).read_text()

    # Preserve the existing `<!-- generated: ... -->` timestamp on
    # refresh so re-runs don't bump the timestamp every second (closes
    # the idempotency-flake where two runs in different seconds produce
    # different bytes). On a fresh install no existing block exists, so
    # existing_ts is None and build_managed_block uses now_iso().
    existing_ts = (
        _existing_generated(target_path.read_text())
        if target_path.exists()
        else None
    )
    managed_block = build_managed_block(snippet, existing_ts=existing_ts)
    if not target_path.exists():
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(HEAD_COMMENT + "\n\n" + managed_block)
        print(f"[install_agents_instructions] wrote fresh {target_path}; scope={scope}")
        return 0
    existing = target_path.read_text()

    # Already managed — refresh the block content from the snippet when it
    # differs from the latest template, so re-runs converge on the canonical
    # contract. User content outside the markers is preserved. Closes the
    # drift class where the managed block became stale relative to the snippet
    # while the markers still matched (the previous no-op branch let stale
    # content survive indefinitely — see MPM cross-adapter integrity audit,
    # 2026-09-04).
    if MANAGED_BEGIN_RE.search(existing) and MANAGED_END_RE.search(existing):
        new_managed = managed_block.rstrip() + "\n"
        if _extract_managed_block(existing) == new_managed:
            print(f"[install_agents_instructions] {target_path} already has current managed section; no-op")
            return 0
        backup = backup_path(target_path)
        shutil.copy2(target_path, backup)
        replaced = re.sub(
            MANAGED_BEGIN_RE.pattern + r".*?" + MANAGED_END_RE.pattern,
            new_managed.rstrip(),
            existing,
            flags=re.DOTALL,
        )
        target_path.write_text(replaced)
        print(
            f"[install_agents_instructions] {target_path} had stale managed "
            f"section — refreshed from snippet. backup at {backup}"
        )
        return 0

    # Legacy managed block -> replace in place.
    if LEGACY_BEGIN_RE.search(existing) and LEGACY_END_RE.search(existing):
        backup = backup_path(target_path)
        shutil.copy2(target_path, backup)
        m = re.search(
            LEGACY_BEGIN_RE.pattern + r".*?" + LEGACY_END_RE.pattern,
            existing, flags=re.DOTALL,
        )
        if not m:
            print(f"[install_agents_instructions] ERROR extracting legacy block; backup at {backup}", file=sys.stderr)
            return 2
        target_path.write_text(existing.replace(m.group(0), managed_block.rstrip() + "\n"))
        print(f"[install_agents_instructions] replaced legacy block in {target_path}; backup at {backup}")
        return 0

    # Unmatched markers -> fail closed.
    begins = re.findall(r"<!-- BEGIN MPM-MANAGED SECTION", existing)
    ends = re.findall(r"<!-- END MPM-MANAGED SECTION", existing)
    if (begins and not ends) or (ends and not begins):
        backup = backup_path(target_path)
        shutil.copy2(target_path, backup)
        print(f"[install_agents_instructions] ERROR: {target_path} has unmatched marker; refusing to modify; backup at {backup}", file=sys.stderr)
        return 2

    # No managed block -> append.
    backup = backup_path(target_path)
    shutil.copy2(target_path, backup)
    insertion = "\n\n" + HEAD_COMMENT + "\n\n" + managed_block.rstrip() + "\n"
    target_path.write_text(existing.rstrip() + insertion)
    print(f"[install_agents_instructions] appended managed section to {target_path}; backup at {backup}; scope={scope}")
    return 0


def uninstall(target: str) -> int:
    target_path = Path(target)
    if not target_path.exists():
        print(f"[install_agents_instructions] no AGENTS.md at {target_path}; nothing to uninstall")
        return 0
    existing = target_path.read_text()
    for begin_re, end_re, label in (
        (MANAGED_BEGIN_RE, MANAGED_END_RE, "opencode"),
        (LEGACY_BEGIN_RE, LEGACY_END_RE, "legacy"),
    ):
        if begin_re.search(existing) and end_re.search(existing):
            backup = backup_path(target_path)
            shutil.copy2(target_path, backup)
            out = re.sub(begin_re.pattern + r".*?" + end_re.pattern, "", existing, flags=re.DOTALL)
            if out.strip() == HEAD_COMMENT.strip() or out.strip() == "":
                target_path.unlink()
                print(f"[install_agents_instructions] removed {label} section; unlinked empty file; backup at {backup}")
                return 0
            target_path.write_text(out)
            print(f"[install_agents_instructions] removed {label} section; backup at {backup}")
            return 0
    print(f"[install_agents_instructions] no managed section at {target_path}")
    return 0


def backup_path(target_path: Path) -> Path:
    parent = target_path.parent
    name = target_path.name + ".bak"
    i = 1
    p = parent / name
    while p.exists():
        p = parent / f"{target_path.name}.bak.{i}"
        i += 1
    return p


def _extract_managed_block(content: str) -> str | None:
    """Return the raw managed block (BEGIN/END inclusive) or None."""
    m = re.search(
        MANAGED_BEGIN_RE.pattern + r".*?" + MANAGED_END_RE.pattern,
        content,
        flags=re.DOTALL,
    )
    return m.group(0) if m else None


def main() -> int:
    ap = argparse.ArgumentParser(description="Install OpenCode AGENTS.md with MPM behavioral section, idempotently.")
    ap.add_argument("--scope", choices=("user", "project"), required=True)
    ap.add_argument("--target", required=True, help="Absolute path to AGENTS.md")
    ap.add_argument("--snippet", required=True, help="Path to the AGENTS.md.snippet")
    ap.add_argument("--uninstall", action="store_true")
    args = ap.parse_args()
    if args.uninstall:
        return uninstall(args.target)
    return install(args.scope, args.target, args.snippet)


if __name__ == "__main__":
    sys.exit(main())
