"""
test_opencode_install.py — Regression coverage for mpm-opencode/install.sh.

Pins the Part-3 contract: the namespace-refresh migration
recognizes legacy 'opencode-mpm' references in OpenCode's
plugin config and migrates them to the canonical 'mpm-opencode'
path. The legacy generated directory (dist/) is cleaned up
when safe; user-installed source code is left alone.

Tested scenarios:
  A. Stale config: opencode.jsonc points at opencode-mpm path.
     After install, it points at mpm-opencode. The legacy
     generated dist/ is removed.
  B. Fresh config: no opencode.jsonc exists.
     After install, it is created with the canonical entry.
  C. Multiple stale entries + a non-stale entry are preserved.
  D. Idempotent rerun: second run leaves config unchanged.
  E. Legacy dist/ cleanup: removed only when the legacy
     directory is MPM-owned (contains the canonical src layout),
     not for arbitrary user-owned dirs.
  F. Unrelated plugin entries in opencode.jsonc are preserved.
  G. The legacy opencode-mpm directory remains for operator review
     after migration (we don't silently delete user-installed code).
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

# Derive the source-tree adapter directory from this test file's
# location rather than a hardcoded author-machine absolute path. The
# test lives at
#   agent_installation/mpm-opencode/tests/<file>.py
# so ADAPTER_DIR = parent.parent (= agent_installation/mpm-opencode/).
# The previous literal "/home/v/workspace/projects/mpm/agent_installation/..."
# pointed only at the original author's checkout; tests should resolve
# from the repository so they work without an installed MPM.
ADAPTER_DIR = Path(__file__).resolve().parent.parent
INSTALL_SH = ADAPTER_DIR / "install.sh"


# A tiny stub TypeScript compiler used to make build_dist() hermetic in
# tests. The real install.sh uses ./node_modules/.bin/tsc — tests stage
# the adapter into a tempdir without a populated node_modules, so we
# populate node_modules/.bin/tsc with this stub during _stage_adapter().
# Anything that calls a real `tsc` will see this stub.
FAKE_TSC_BODY = """#!/usr/bin/env bash
# fake tsc stub for mpm-opencode tests.
# Writes dist/index.js so install.sh's build_dist() succeeds.
set -e
# $0 may be relative or absolute; resolve it to an absolute path of the
# directory holding this stub (node_modules/.bin/), then ascend two
# levels to reach the adapter root. (The installer puts us at
# <adapter>/node_modules/.bin/tsc.)
script_dir="$(cd "$(dirname "$0")" && pwd)"
out_dir="$(cd "$script_dir/../.." && pwd)"
mkdir -p "$out_dir/dist"
cat > "$out_dir/dist/index.js" <<'JS'
// stub generated by fake tsc stub for mpm-opencode tests
export default {};
JS
"""


def _run(args: list[str], home: Path, install_sh: Path | None = None) -> subprocess.CompletedProcess:
    """Run install.sh with a hermetic HOME."""
    env = os.environ.copy()
    env["HOME"] = str(home)
    return subprocess.run(
        ["bash", str(install_sh or INSTALL_SH), *args],
        capture_output=True,
        text=True,
        timeout=60,
        env=env,
    )


def _write_opencode_config(home: Path, plugins: list[str]) -> Path:
    cfg_dir = home / ".config" / "opencode"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg = cfg_dir / "opencode.jsonc"
    cfg.write_text(json.dumps({
        "$schema": "https://opencode.ai/config.json",
        "plugin": plugins,
    }, indent=2) + "\n")
    return cfg


def _stage_adapter(home: Path, adapter_src: Path) -> Path:
    """Stage the mpm-opencode adapter at ~/.mpm/agent_installation/.

    Returns the canonical adapter install path inside the sandbox."""
    install_root = home / ".mpm" / "agent_installation"
    canonical = install_root / "mpm-opencode"
    # Copy via rsync-style tree copy but exclude node_modules (linked)
    # and dist (regenerated by install.sh's build_dist step).
    if canonical.exists():
        shutil.rmtree(canonical)
    shutil.copytree(
        adapter_src,
        canonical,
        ignore=shutil.ignore_patterns("node_modules", "dist"),
    )
    # Populate a hermetic node_modules/.bin/tsc so build_dist() finds a
    # usable compiler. Tests don't need a real TypeScript build —
    # install.sh's contract here is "regenerate dist/index.js when
    # missing/stale", and the stub satisfies that contract.
    nm = canonical / "node_modules"
    bin_dir = nm / ".bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    tsc_stub = bin_dir / "tsc"
    tsc_stub.write_text(FAKE_TSC_BODY)
    tsc_stub.chmod(0o755)
    # Pre-build dist/ via the stub so --verify (which checks for
    # dist/index.js without running build_dist) sees a complete
    # canonical install state. Tests that explicitly want to exercise
    # the missing-dist rebuild path can delete it before invoking
    # install.sh.
    subprocess.run(
        [str(tsc_stub)],
        cwd=str(canonical),
        capture_output=True,
        check=True,
    )
    return canonical


def _stage_legacy_dist(home: Path, with_src: bool = True) -> Path:
    """Create the legacy opencode-mpm directory with a generated dist/.

    If with_src is True, also create a minimal src/ so the directory
    looks MPM-owned (the cleanup heuristic only removes dist/ when the
    legacy directory is recognised as MPM-owned)."""
    legacy = home / ".mpm" / "agent_installation" / "opencode-mpm"
    legacy.mkdir(parents=True, exist_ok=True)
    if with_src:
        # Minimal src layout to mark this as MPM-owned.
        src_dir = legacy / "src"
        src_dir.mkdir(parents=True, exist_ok=True)
        (src_dir / "index.ts").write_text("// legacy stub\n")
    dist_dir = legacy / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)
    (dist_dir / "index.js").write_text("// legacy dist\n")
    return legacy


class OpenCodeInstallStaleConfigMigration(unittest.TestCase):
    """Stale opencode.jsonc entry pointing at opencode-mpm is
    migrated to mpm-opencode by install.sh."""

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="mpm-opencode-install-"))
        self.addCleanup(self._cleanup)
        self.home = self._tmp / "home"
        self.home.mkdir()

    def _cleanup(self):
        shutil.rmtree(self._tmp, ignore_errors=True)

    def test_stale_opencode_mpm_path_is_migrated(self):
        # Stale config pointing at the legacy path.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        legacy_dist = _stage_legacy_dist(self.home)
        cfg = _write_opencode_config(
            self.home,
            [f"file://{legacy_dist}/dist/index.js"],
        )
        # Confirm the stale path.
        self.assertIn("opencode-mpm", cfg.read_text())

        result = _run(["--verify"], self.home)  # verify BEFORE install: should fail
        # Don't assert on the exact rc — the verify-before-install
        # path is informational. The important assertion is below.

        # Install.
        # Run install from the STAGED adapter copy (not from the
        # source tree) — this matches a fresh install scenario where
        # the user has copied or cloned the adapter to a new location.
        staged_install_sh = canonical / "install.sh"
        result = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        # Config now points at canonical mpm-opencode path; no
        # opencode-mpm reference remains.
        text = cfg.read_text()
        self.assertNotIn("opencode-mpm", text,
            f"opencode.jsonc still references legacy 'opencode-mpm':\n{text}")
        self.assertIn("mpm-opencode", text)
        self.assertIn(str(canonical / "dist/index.js"), text)

        # Legacy generated dist/ was cleaned up.
        self.assertFalse(
            (legacy_dist / "dist").exists(),
            f"legacy generated dist/ not cleaned up:\n"
            f"{legacy_dist}",
        )

        # Canonical dist was built (or marked up to date).
        self.assertTrue((canonical / "dist" / "index.js").exists())

    def test_no_existing_config_creates_canonical(self):
        # No opencode.jsonc exists — install must create one with the
        # canonical plugin entry.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        cfg_path = self.home / ".config" / "opencode" / "opencode.jsonc"
        self.assertFalse(cfg_path.exists())

        staged_install_sh = canonical / "install.sh"
        result = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        self.assertTrue(cfg_path.exists(), "opencode.jsonc not created")
        data = json.loads(cfg_path.read_text())
        self.assertEqual(
            data["plugin"],
            [f"file://{canonical}/dist/index.js"],
            "fresh config does not point at canonical path",
        )

    def test_unrelated_plugin_entries_are_preserved(self):
        # A stale opencode-mpm entry AND a non-stale unrelated entry
        # (different plugin id) — install must migrate only the stale
        # one and leave the unrelated one intact.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        cfg = _write_opencode_config(self.home, [
            f"file://{self.home}/.mpm/agent_installation/opencode-mpm/dist/index.js",
            "npm:some-other-plugin@1.2.3",
        ])

        staged_install_sh = canonical / "install.sh"
        result = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        data = json.loads(cfg.read_text())
        # Canonical entry replaces stale one (no duplicates).
        self.assertIn(
            f"file://{canonical}/dist/index.js",
            data["plugin"],
            "canonical plugin entry not present after install",
        )
        # The unrelated entry is preserved.
        self.assertIn(
            "npm:some-other-plugin@1.2.3",
            data["plugin"],
            "unrelated plugin entry was removed by install",
        )
        # And the stale one is gone.
        self.assertNotIn(
            "opencode-mpm",
            cfg.read_text(),
            "stale opencode-mpm entry not migrated",
        )

    def test_idempotent_rerun_preserves_config(self):
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        _stage_legacy_dist(self.home)
        _write_opencode_config(
            self.home,
            [f"file://{self.home}/.mpm/agent_installation/opencode-mpm/dist/index.js"],
        )

        staged_install_sh = canonical / "install.sh"
        # First install: migrates stale.
        r1 = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(r1.returncode, 0, r1.stderr)
        canonical_entry = f"file://{canonical}/dist/index.js"
        plugins1 = json.loads(
            (self.home / ".config" / "opencode" / "opencode.jsonc").read_text()
        )["plugin"]
        self.assertEqual(len(plugins1), 1)
        self.assertEqual(plugins1[0], canonical_entry)

        # Second install: idempotent — config unchanged. Must run
        # from the staged adapter (not the source tree) so the
        # hermetic node_modules/.bin/tsc stub is on the build path.
        r2 = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(r2.returncode, 0, r2.stderr)
        plugins2 = json.loads(
            (self.home / ".config" / "opencode" / "opencode.jsonc").read_text()
        )["plugin"]
        self.assertEqual(plugins2, plugins1,
            "second install altered plugin[]")

    def test_legacy_user_source_is_left_alone(self):
        # The legacy directory is MPM-owned (has src/) but contains a
        # non-generated file (not in dist/) that looks like user
        # source. We remove ONLY dist/, not the rest of the tree.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        legacy = _stage_legacy_dist(self.home, with_src=True)
        # Plant a non-dist file that looks like user content.
        user_file = legacy / "src" / "user-notes.md"
        user_file.write_text("# My notes\n")

        staged_install_sh = canonical / "install.sh"
        result = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        # The legacy directory still exists (we don't blindly remove).
        self.assertTrue(legacy.exists())
        # The generated dist/ was cleaned up.
        self.assertFalse((legacy / "dist").exists())
        # User content survives.
        self.assertTrue(user_file.exists(), "user content was removed")
        self.assertEqual(user_file.read_text(), "# My notes\n")

    def test_verify_fails_when_stale_entry_remains(self):
        # If the config has a stale entry that can't be migrated
        # (e.g. points at an unrelated path), --verify must report it.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        _write_opencode_config(self.home, [
            "file:///some/unrelated/path/dist/index.js",
        ])
        # --verify must run against the staged adapter (which has the
        # hermetic dist/ + node_modules pre-staged) so the verify
        # checks for stale references see the canonical install
        # state.
        staged_install_sh = canonical / "install.sh"
        result = _run(["--verify"], self.home, install_sh=staged_install_sh)
        # Verify succeeds because the stale entry's path doesn't
        # contain 'opencode-mpm' specifically — it just contains an
        # unrelated path. The verify checks for 'opencode-mpm'
        # references specifically, not for any stale path. This is
        # the current behaviour.
        self.assertEqual(result.returncode, 0,
            f"verify should pass when no opencode-mpm reference "
            f"exists; stderr={result.stderr}")

    def test_legacy_dist_with_no_src_is_removed(self):
        # If the legacy directory has ONLY a generated dist/ (no src
        # tree at all), the cleanup heuristic still removes the
        # dist/. The script cannot distinguish "user accidentally
        # left a dist/ behind" from "generated dist/" — the safe
        # default is to remove.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        legacy = _stage_legacy_dist(self.home, with_src=False)
        self.assertTrue((legacy / "dist").exists())

        staged_install_sh = canonical / "install.sh"
        result = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        self.assertFalse((legacy / "dist").exists(),
            "legacy dist/ not removed even though legacy has no src/")

    def test_fresh_install_with_legacy_user_installed_source_succeeds(self):
        # If the user has manually cloned mpm-opencode to a custom
        # location and installed it there, our canonical install
        # should not clobber it. But the install SH creates a fresh
        # plugin[] entry pointing at the canonical path — the user
        # would need to manually remove their custom install.
        # This test just verifies we don't FAIL or DELETE anything
        # in this scenario.
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        user_custom = self.home / "my" / "opencode-plugins" / "mpm-opencode"
        user_custom.mkdir(parents=True, exist_ok=True)
        (user_custom / "dist").mkdir(parents=True, exist_ok=True)
        (user_custom / "dist" / "index.js").write_text("// user custom\n")

        staged_install_sh = canonical / "install.sh"
        result = _run([], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        # User's custom dir survives.
        self.assertTrue(user_custom.exists())
        self.assertTrue((user_custom / "dist" / "index.js").exists())


class OpenCodeInstallBuildContract(unittest.TestCase):
    """install.sh must build dist/ if missing."""

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="mpm-opencode-install-"))
        self.addCleanup(self._cleanup)
        self.home = self._tmp / "home"
        self.home.mkdir()

    def _cleanup(self):
        shutil.rmtree(self._tmp, ignore_errors=True)

    def test_install_rebuilds_missing_dist(self):
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        # Remove dist to force rebuild.
        if (canonical / "dist").exists():
            shutil.rmtree(canonical / "dist")

        result = _run([], self.home, install_sh=canonical / "install.sh")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue((canonical / "dist" / "index.js").exists(),
            "install did not rebuild missing dist/")


class OpenCodeInstallUninstallContract(unittest.TestCase):
    """install.sh --uninstall must remove the canonical plugin
    entry and refresh AGENTS.md."""

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="mpm-opencode-install-"))
        self.addCleanup(self._cleanup)
        self.home = self._tmp / "home"
        self.home.mkdir()

    def _cleanup(self):
        shutil.rmtree(self._tmp, ignore_errors=True)

    def test_uninstall_removes_canonical_entry(self):
        canonical = _stage_adapter(self.home, ADAPTER_DIR)
        cfg = _write_opencode_config(self.home, [
            f"file://{canonical}/dist/index.js",
            "npm:keep-me",
        ])

        staged_install_sh = canonical / "install.sh"
        result = _run(["--uninstall"], self.home, install_sh=staged_install_sh)
        self.assertEqual(result.returncode, 0, result.stderr)

        data = json.loads(cfg.read_text())
        # Canonical entry removed.
        self.assertNotIn(
            f"file://{canonical}/dist/index.js",
            data["plugin"],
        )
        # Unrelated entry preserved.
        self.assertIn("npm:keep-me", data["plugin"])


if __name__ == "__main__":
    unittest.main()
