#!/usr/bin/env python3
r"""
install_openclaw_instructions.py — Install the MPM managed block into
the active OpenClaw agent's SOUL.md, idempotently.

Usage (called by install.sh):
    python3 install_openclaw_instructions.py \
        --home "$HOME" \
        --target "$HOME/.openclaw/workspace/SOUL.md" \
        --snippet /path/to/SOUL.md.snippet

Behaviour:
  * If target does not exist: create it with the MPM snippet as the
    initial content (header + managed block + footer, no other
    content). This is the documented fresh-install behaviour for
    SOUL.md — the user/persona file is created only when no persona
    material exists yet (a fresh OpenClaw install).
  * Otherwise the file is CONVERGED to exactly one effective MPM
    behavioural contract by the shared engine in
    scripts/managed_block_convergence.py, which recognizes every MPM
    marker form MPM has ever written (this host's section, another
    host's section, legacy unsuffixed and Hermes-spaced anchors, and a
    deterministically repairable unterminated section). After
    convergence the file contains exactly ONE behavioural contract.
  * All user/persona content outside MPM-owned regions is preserved
    byte-for-byte.
  * Always backs up the existing target before any modification.
  * Refuses (exit 3, no write) when the file's markers are genuinely
    ambiguous, rather than risk deleting user content.

Discovery:
  When --target is not provided, the script resolves the active
  agent's SOUL.md by reading ~/.openclaw/openclaw.json →
  agents.entries.<id>.workspace / SOUL.md. The default agent id is
  "main"; multi-agent installations resolve each entry's workspace
  independently. The installer writes the managed block into the
  SOUL.md at that path.

This script does NOT touch MPM core, MPM source, or any path outside
the OpenClaw workspace (for user scope).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

# The shared convergence engine. It lives in agent_installation/scripts/
# alongside the reconciler and the renderer, and is imported by path
# rather than by package name because every adapter's installer is
# executed as a standalone script with no package context.
_SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import managed_block_convergence as convergence  # noqa: E402


# Marker conventions follow the per-host pattern used by the other
# persistent-file installers (claude-code, opencode, pi, hermes).
# The OUTER markers are the installer's idempotency anchor; the
# INNER `<!-- BEGIN/END MPM MANAGED BLOCK -->` pair nests the
# canonical managed block. We do NOT match random `<!-- BEGIN mpm-* -->`
# markers from unrelated plugins because that would conflate their
# blocks with ours in a shared file.
#
# The outer/inner SPLIT and the recognition of every historical MPM
# marker form are owned by the shared convergence engine, not by this
# installer. This installer used to match only its own marker pair,
# which meant a file carrying another host's MPM section matched
# nothing and fell through to the append path — leaving two behavioural
# contracts in one SOUL.md. Delegating the whole decision keeps the
# "at most one effective MPM behavioural contract per file" invariant
# in exactly one place.
MANAGED_BEGIN_RE = re.compile(
    r"<!-- BEGIN MPM-MANAGED SECTION:openclaw-instructions(?: [^\n]*)?-->"
)
MANAGED_END_RE = re.compile(
    r"<!-- END MPM-MANAGED SECTION:openclaw-instructions(?: [^\n]*)?-->"
)
# The marker id this host owns. The engine compares a found region's
# id against this set to tell "my own block" from "a foreign host's
# block that must be migrated", not refreshed in place.
OWN_HOST_IDS = frozenset({"openclaw-instructions"})

# Default OpenClaw config location. Overridden by resolve_openclaw_target
# using the --home argument; Path.home() is only used as the absolute
# fallback when --home is not provided.
DEFAULT_OPENCLAW_CONFIG_RELATIVE = Path(".openclaw") / "openclaw.json"
DEFAULT_AGENT_ID = "main"
DEFAULT_SOUL_FILENAME = "SOUL.md"


HEAD_COMMENT = """\
<!--
This file's SOUL.md MPM section is managed by the mpm-memory-openclaw
plugin's install_openclaw_instructions.py. The block between
BEGIN/END MPM-MANAGED SECTION:openclaw-instructions markers is
regenerated by the installer; everything outside the markers is
preserved. To uninstall: python3 install_openclaw_instructions.py
--uninstall --target ...
-->
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def resolve_openclaw_target(home: Path, agent_id: str, target_arg: str | None) -> Path:
    """Resolve the active agent's SOUL.md path.

    Order:
      1. Explicit --target, if provided.
      2. Read <home>/.openclaw/openclaw.json → agents.entries.<id>.workspace;
         fall back to agents.defaults.workspace; fall back to
         <home>/.openclaw/workspace.
      3. Append SOUL.md.
    """
    if target_arg:
        return Path(target_arg).expanduser()

    config = home / DEFAULT_OPENCLAW_CONFIG_RELATIVE
    if not config.is_file():
        # Fallback: legacy default workspace.
        return home / ".openclaw" / "workspace" / DEFAULT_SOUL_FILENAME

    try:
        data = json.loads(config.read_text(encoding="utf-8"))
    except Exception as e:
        sys.stderr.write(
            f"[openclaw install] WARN: cannot read {config}: {e}\n"
        )
        data = {}

    agents = data.get("agents", {}) if isinstance(data, dict) else {}
    entries = agents.get("entries", {}) if isinstance(agents, dict) else {}
    entry = entries.get(agent_id, {}) if isinstance(entries, dict) else {}
    workspace = None
    if isinstance(entry, dict):
        workspace = entry.get("workspace")
    if not workspace:
        defaults = agents.get("defaults", {}) if isinstance(agents, dict) else {}
        if isinstance(defaults, dict):
            workspace = defaults.get("workspace")
    if not workspace:
        workspace = str(home / ".openclaw" / "workspace")

    workspace_path = Path(workspace)
    if not workspace_path.is_absolute():
        workspace_path = (home / workspace_path).resolve()
    return workspace_path / DEFAULT_SOUL_FILENAME


def backup_target(path: Path) -> Path | None:
    """Snapshot the existing target before any modification.

    Returns the backup path, or None if the target didn't exist.
    """
    if not path.exists():
        return None
    backup = path.with_suffix(path.suffix + f".bak.{now_iso()}")
    shutil.copy2(path, backup)
    return backup


def build_managed_section(snippet_text: str, existing_ts: str | None = None) -> str:
    """Wrap the rendered snippet in the OpenClaw outer section markers.

    The snippet is the canonical header + block + footer produced by
    scripts/render_managed_blocks.py. This installer wraps that body
    inside the outer `<!-- BEGIN/END MPM-MANAGED SECTION:openclaw-instructions -->`
    pair so the resulting target file has the same outer-marker shape
    as the other persistent-block hosts (claude-code, opencode, pi,
    hermes). The `<!-- generated: ... -->` timestamp is preserved on
    refresh so two installs in different seconds do not produce
    different bytes outside the managed section.
    """
    ts = existing_ts or now_iso()
    banner = (
        f"<!-- BEGIN MPM-MANAGED SECTION:openclaw-instructions -->\n"
        f"<!-- generated: {ts} -->\n"
        f"<!-- source: ~/.mpm/agent_installation/mpm-memory-openclaw/templates/SOUL.md.snippet -->\n"
        f"<!-- do not edit between the BEGIN/END markers; edit the snippet or the -->\n"
        f"<!-- canonical protocol at ~/.mpm/agent_installation/mpm-agent-protocol.md. -->\n"
    )
    footer = "<!-- END MPM-MANAGED SECTION:openclaw-instructions -->"
    return f"{banner}{snippet_text.rstrip()}\n{footer}\n"


def extract_generated_ts(managed_section_text: str) -> str | None:
    """Recover the existing `<!-- generated: ... -->` timestamp from
    a currently-installed managed section, if any. Used to preserve
    the timestamp on refresh.
    """
    m = re.search(r"<!-- generated: ([^\n]+) -->\n", managed_section_text)
    return m.group(1) if m else None


def extract_generated_ts_from_managed_region(text: str) -> str | None:
    """Recover the install timestamp from whichever MPM-managed region
    the file already carries.

    Reads this host's section first, then falls back to any other MPM
    region. The fallback matters when converging a file that currently
    holds a foreign-host or legacy section: those carry a timestamp
    too, and dropping it would make the first convergent write
    indistinguishable from a real content change on the next run.
    """
    own = read_managed_section(text)
    if own:
        ts = extract_generated_ts(own)
        if ts:
            return ts
    m = re.search(r"<!-- generated: ([^\n]+) -->\n", text)
    return m.group(1) if m else None


def read_managed_section(text: str) -> str | None:
    """Return the bytes of this host's currently-managed section.

    Only recognizes THIS host's markers. Use of the engine's
    `analyze` is what generalizes; this helper exists for callers that
    specifically mean "my own section" (notably timestamp recovery).
    """
    begin = MANAGED_BEGIN_RE.search(text)
    end = MANAGED_END_RE.search(text)
    if begin and end and end.start() > begin.end():
        return text[begin.start():end.end()]
    return None


def do_install(target: Path, snippet: Path) -> int:
    """Converge target onto exactly one MPM behavioural contract.

    Returns 0 on success or no-op, 3 on an ambiguous refusal.
    """
    snippet_text = snippet.read_text(encoding="utf-8")

    if not target.exists():
        # Fresh install: create the target with the wrapper header +
        # snippet body + wrapper footer. The snippet is the canonical
        # header + block + footer produced by the renderer; we wrap it
        # in the outer section markers so the file has the same shape
        # as a refreshed install.
        backup_target(target)  # no-op when target doesn't exist
        target.parent.mkdir(parents=True, exist_ok=True)
        managed = build_managed_section(snippet_text)
        target.write_text(managed, encoding="utf-8")
        sys.stderr.write(
            f"[openclaw install] created {target} ({len(managed)} bytes)\n"
        )
        return 0

    text = target.read_text(encoding="utf-8")

    # Preserve the existing `<!-- generated: ... -->` timestamp on
    # refresh so re-runs in different seconds do not produce different
    # bytes outside the managed section (idempotency). The timestamp is
    # read from whichever MPM-managed region is already present — a
    # foreign-host or repaired section carries one too, and dropping it
    # would make an otherwise-unchanged file look rewritten.
    existing_ts = extract_generated_ts_from_managed_region(text)

    new_section = build_managed_section(snippet_text, existing_ts=existing_ts)
    plan = convergence.plan_convergence(text, new_section, OWN_HOST_IDS)

    if plan.action == convergence.PLAN_REFUSE:
        sys.stderr.write(
            f"[openclaw install] REFUSING to modify {target}: {plan.reason}\n"
            f"[openclaw install] no backup taken and no bytes written; inspect "
            f"the file manually and re-run once the markers are resolved.\n"
        )
        return 3

    if plan.action == convergence.PLAN_NOOP:
        sys.stderr.write(
            f"[openclaw install] {target} already has the current managed "
            f"section; no-op\n"
        )
        return 0

    backup = backup_target(target)
    if backup is not None:
        sys.stderr.write(
            f"[openclaw install] backed up {target} -> {backup}\n"
        )
    target.write_text(plan.text, encoding="utf-8")
    sys.stderr.write(
        f"[openclaw install] {plan.action}: {plan.reason} "
        f"({len(new_section)} bytes)\n"
    )
    return 0


def do_uninstall(target: Path) -> int:
    """Remove the MPM managed section from target.

    Removes every MPM-owned region — this host's, another host's, or a
    legacy one — because leaving a foreign or legacy contract behind
    would defeat the point of uninstalling. Refuses on ambiguity.
    """
    if not target.exists():
        return 0
    text = target.read_text(encoding="utf-8")
    analysis = convergence.analyze(text)
    if analysis.problems or not analysis.regions:
        if analysis.problems:
            sys.stderr.write(
                f"[openclaw install] REFUSING to uninstall from {target}: "
                f"{'; '.join(analysis.problems)}\n"
            )
            return 3
        return 0
    backup = backup_target(target)
    if backup is not None:
        sys.stderr.write(
            f"[openclaw install] backed up {target} -> {backup}\n"
        )
    new_text = convergence.remove_regions(text, analysis.regions)
    target.write_text(new_text, encoding="utf-8")
    sys.stderr.write(
        f"[openclaw install] removed {len(analysis.regions)} managed "
        f"section(s) from {target}\n"
    )
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--home", default=str(Path.home()),
                        help="Home directory (default: $HOME)")
    parser.add_argument("--target",
                        help="Explicit SOUL.md path (default: resolve from openclaw.json)")
    parser.add_argument("--snippet", required=True,
                        help="Path to the rendered SOUL.md.snippet")
    parser.add_argument("--agent-id", default=DEFAULT_AGENT_ID,
                        help=f"OpenClaw agent id (default: {DEFAULT_AGENT_ID})")
    parser.add_argument("--uninstall", action="store_true",
                        help="Remove the MPM managed section from target")
    args = parser.parse_args(argv)

    home = Path(args.home).expanduser()
    target = resolve_openclaw_target(home, args.agent_id, args.target)
    snippet = Path(args.snippet).expanduser()

    if not snippet.is_file():
        sys.stderr.write(f"[openclaw install] ERROR: snippet not found: {snippet}\n")
        return 4

    if args.uninstall:
        return do_uninstall(target)
    return do_install(target, snippet)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
