#!/usr/bin/env python3
r"""
install_openclaw_instructions.py — Install the MPM managed block into
the active OpenClaw agent's SOUL.md, idempotently.

Usage (called by install.sh):
    python3 install_openclaw_instructions.py \
        --home "$HOME" \
        --target "$HOME/.openclaw/workspace/SOUL.md" \
        --snippet /path/to/SOUL.md.snippet

Behaviour:
  * If target does not exist: create it with the MPM snippet as the
    initial content (header + managed block + footer, no other
    content). This is the documented fresh-install behaviour for
    SOUL.md — the user/persona file is created only when no persona
    material exists yet (a fresh OpenClaw install).
  * If target exists WITHOUT the managed section: insert the managed
    section at the end (preserves all existing user/persona content
    above).
  * If target exists WITH the managed section already: refresh only
    the managed section (between the BEGIN and END markers). All
    other content (persona, user notes, etc.) is preserved verbatim.
  * If target has only LEGACY markers from a prior version: replace
    the legacy block with the current managed block. Persona/user
    content outside the markers is preserved.
  * Always backs up the existing target before any modification.

The script fails closed if anything unexpected is in the target —
partial markers, mismatched BEGIN/END counts, etc.

Discovery:
  When --target is not provided, the script resolves the active
  agent's SOUL.md by reading ~/.openclaw/openclaw.json →
  agents.entries.<id>.workspace / SOUL.md. The default agent id is
  "main"; multi-agent installations resolve each entry's workspace
  independently. The installer writes the managed block into the
  SOUL.md at that path.

This script does NOT touch MPM core, MPM source, or any path outside
the OpenClaw workspace (for user scope).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


# Marker conventions follow the per-host pattern used by the other
# persistent-file installers (claude-code, opencode, pi, hermes).
# The OUTER markers are the installer's idempotency anchor; the
# INNER `<!-- BEGIN/END MPM MANAGED BLOCK -->` pair nests the
# canonical managed block. We do NOT match random `<!-- BEGIN mpm-* -->`
# markers from unrelated plugins because that would conflate their
# blocks with ours in a shared file.
MANAGED_BEGIN_RE = re.compile(
    r"<!-- BEGIN MPM-MANAGED SECTION:openclaw-instructions(?: [^\n]*)?-->"
)
MANAGED_END_RE = re.compile(
    r"<!-- END MPM-MANAGED SECTION:openclaw-instructions(?: [^\n]*)?-->"
)
LEGACY_BEGIN_RE = re.compile(
    r"<!-- BEGIN MPM-MANAGED BLOCK(?::[^\n]*| [^\n]*)?-->"
)
LEGACY_END_RE = re.compile(
    r"<!-- END MPM-MANAGED BLOCK(?::[^\n]*| [^\n]*)?-->"
)

# Default OpenClaw config location. Overridden by resolve_openclaw_target
# using the --home argument; Path.home() is only used as the absolute
# fallback when --home is not provided.
DEFAULT_OPENCLAW_CONFIG_RELATIVE = Path(".openclaw") / "openclaw.json"
DEFAULT_AGENT_ID = "main"
DEFAULT_SOUL_FILENAME = "SOUL.md"


HEAD_COMMENT = """\
<!--
This file's SOUL.md MPM section is managed by the mpm-memory-openclaw
plugin's install_openclaw_instructions.py. The block between
BEGIN/END MPM-MANAGED SECTION:openclaw-instructions markers is
regenerated by the installer; everything outside the markers is
preserved. To uninstall: python3 install_openclaw_instructions.py
--uninstall --target ...
-->
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def resolve_openclaw_target(home: Path, agent_id: str, target_arg: str | None) -> Path:
    """Resolve the active agent's SOUL.md path.

    Order:
      1. Explicit --target, if provided.
      2. Read <home>/.openclaw/openclaw.json → agents.entries.<id>.workspace;
         fall back to agents.defaults.workspace; fall back to
         <home>/.openclaw/workspace.
      3. Append SOUL.md.
    """
    if target_arg:
        return Path(target_arg).expanduser()

    config = home / DEFAULT_OPENCLAW_CONFIG_RELATIVE
    if not config.is_file():
        # Fallback: legacy default workspace.
        return home / ".openclaw" / "workspace" / DEFAULT_SOUL_FILENAME

    try:
        data = json.loads(config.read_text(encoding="utf-8"))
    except Exception as e:
        sys.stderr.write(
            f"[openclaw install] WARN: cannot read {config}: {e}\n"
        )
        data = {}

    agents = data.get("agents", {}) if isinstance(data, dict) else {}
    entries = agents.get("entries", {}) if isinstance(agents, dict) else {}
    entry = entries.get(agent_id, {}) if isinstance(entries, dict) else {}
    workspace = None
    if isinstance(entry, dict):
        workspace = entry.get("workspace")
    if not workspace:
        defaults = agents.get("defaults", {}) if isinstance(agents, dict) else {}
        if isinstance(defaults, dict):
            workspace = defaults.get("workspace")
    if not workspace:
        workspace = str(home / ".openclaw" / "workspace")

    workspace_path = Path(workspace)
    if not workspace_path.is_absolute():
        workspace_path = (home / workspace_path).resolve()
    return workspace_path / DEFAULT_SOUL_FILENAME


def backup_target(path: Path) -> Path | None:
    """Snapshot the existing target before any modification.

    Returns the backup path, or None if the target didn't exist.
    """
    if not path.exists():
        return None
    backup = path.with_suffix(path.suffix + f".bak.{now_iso()}")
    shutil.copy2(path, backup)
    return backup


def build_managed_section(snippet_text: str, existing_ts: str | None = None) -> str:
    """Wrap the rendered snippet in the OpenClaw outer section markers.

    The snippet is the canonical header + block + footer produced by
    scripts/render_managed_blocks.py. This installer wraps that body
    inside the outer `<!-- BEGIN/END MPM-MANAGED SECTION:openclaw-instructions -->`
    pair so the resulting target file has the same outer-marker shape
    as the other persistent-block hosts (claude-code, opencode, pi,
    hermes). The `<!-- generated: ... -->` timestamp is preserved on
    refresh so two installs in different seconds do not produce
    different bytes outside the managed section.
    """
    ts = existing_ts or now_iso()
    banner = (
        f"<!-- BEGIN MPM-MANAGED SECTION:openclaw-instructions -->\n"
        f"<!-- generated: {ts} -->\n"
        f"<!-- source: ~/.mpm/agent_installation/mpm-memory-openclaw/templates/SOUL.md.snippet -->\n"
        f"<!-- do not edit between the BEGIN/END markers; edit the snippet or the -->\n"
        f"<!-- canonical protocol at ~/.mpm/agent_installation/mpm-agent-protocol.md. -->\n"
    )
    footer = "<!-- END MPM-MANAGED SECTION:openclaw-instructions -->"
    return f"{banner}{snippet_text.rstrip()}\n{footer}\n"


def extract_generated_ts(managed_section_text: str) -> str | None:
    """Recover the existing `<!-- generated: ... -->` timestamp from
    a currently-installed managed section, if any. Used to preserve
    the timestamp on refresh.
    """
    m = re.search(r"<!-- generated: ([^\n]+) -->\n", managed_section_text)
    return m.group(1) if m else None


def read_managed_section(text: str) -> str | None:
    """Return the bytes of the currently-managed section, or None."""
    begin = MANAGED_BEGIN_RE.search(text)
    end = MANAGED_END_RE.search(text)
    if begin and end and end.start() > begin.end():
        return text[begin.start():end.end()]
    return None


def replace_managed_section(text: str, new_section: str) -> str:
    """Replace the managed section in text with new_section.

    Fails closed if the BEGIN/END markers are missing or mismatched.
    """
    begin = MANAGED_BEGIN_RE.search(text)
    end = MANAGED_END_RE.search(text)
    if not begin or not end:
        # Try legacy markers.
        legacy_begin = LEGACY_BEGIN_RE.search(text)
        legacy_end = LEGACY_END_RE.search(text)
        if legacy_begin and legacy_end and legacy_end.start() > legacy_begin.end():
            return text[:legacy_begin.start()] + new_section + text[legacy_end.end():]
        # No markers present — append at end.
        sep = "" if text.endswith("\n") else "\n"
        return text + sep + "\n" + new_section + "\n"
    if end.start() <= begin.end():
        raise ValueError(
            f"managed section markers are mismatched (BEGIN at {begin.start()}, "
            f"END at {end.start()})"
        )
    return text[:begin.start()] + new_section + text[end.end():]


def do_install(target: Path, snippet: Path) -> int:
    """Install/refresh the managed section in target from snippet.

    Returns 0 on success. Fails closed on any unexpected state.
    """
    snippet_text = snippet.read_text(encoding="utf-8")

    if not target.exists():
        # Fresh install: create the target with the wrapper header +
        # snippet body + wrapper footer. The snippet is the canonical
        # header + block + footer produced by the renderer; we wrap it
        # in the outer section markers so the file has the same shape
        # as a refreshed install.
        backup_target(target)  # no-op when target doesn't exist
        target.parent.mkdir(parents=True, exist_ok=True)
        managed = build_managed_section(snippet_text)
        target.write_text(managed, encoding="utf-8")
        sys.stderr.write(
            f"[openclaw install] created {target} ({len(managed)} bytes)\n"
        )
        return 0

    text = target.read_text(encoding="utf-8")

    # Refuse partial state.
    begin_count = len(MANAGED_BEGIN_RE.findall(text))
    end_count = len(MANAGED_END_RE.findall(text))
    if begin_count != end_count:
        sys.stderr.write(
            f"[openclaw install] ERROR: mismatched markers in {target} "
            f"(begin={begin_count}, end={end_count}); refusing to touch\n"
        )
        return 2

    backup = backup_target(target)
    if backup is not None:
        sys.stderr.write(
            f"[openclaw install] backed up {target} -> {backup}\n"
        )

    # Identify the snippet's managed section so we can swap it in
    # without disturbing header/footer positioning relative to user
    # content. The snippet is the entire target content (header +
    # managed block + footer); we replace only the bracketed managed
    # section to preserve surrounding structure.
    # Preserve the existing `<!-- generated: ... -->` timestamp on
    # refresh so re-runs in different seconds do not produce different
    # bytes outside the managed section (idempotency).
    existing_section = read_managed_section(text)
    existing_ts = extract_generated_ts(existing_section) if existing_section else None

    new_section = build_managed_section(snippet_text, existing_ts=existing_ts)

    # The new section must replace the existing one with surrounding
    # whitespace preserved byte-for-byte. We strip all leading
    # newlines from `after` (the END marker's own terminator plus any
    # blank-line gap that may have accumulated on a prior install) and
    # strip the section's own trailing newlines; we then re-add
    # exactly one `\n` to keep a single boundary newline.
    begin_m = MANAGED_BEGIN_RE.search(text)
    end_m = MANAGED_END_RE.search(text)
    if begin_m and end_m:
        before = text[:begin_m.start()]
        after = text[end_m.end():]
        # Strip ALL leading newlines from `after` so any accumulated
        # blank-line gap from a previous install does not re-appear.
        after = after.lstrip("\n")
        ns = new_section.rstrip("\n")
        # Re-add exactly one boundary newline.
        new_text = before + ns + "\n" + after
    else:
        new_text = replace_managed_section(text, new_section)
    target.write_text(new_text, encoding="utf-8")
    sys.stderr.write(
        f"[openclaw install] refreshed managed section in {target} "
        f"({len(new_section)} bytes)\n"
    )
    return 0


def do_uninstall(target: Path) -> int:
    """Remove only the MPM managed section from target."""
    if not target.exists():
        return 0
    text = target.read_text(encoding="utf-8")
    begin_count = len(MANAGED_BEGIN_RE.findall(text))
    end_count = len(MANAGED_END_RE.findall(text))
    if begin_count != end_count:
        sys.stderr.write(
            f"[openclaw install] ERROR: mismatched markers in {target}\n"
        )
        return 2
    if begin_count == 0:
        return 0
    backup = backup_target(target)
    if backup is not None:
        sys.stderr.write(
            f"[openclaw install] backed up {target} -> {backup}\n"
        )
    new_text = replace_managed_section(text, "")
    # Strip a leading newline we may have left when removing the
    # section so we don't double-blank the file.
    new_text = re.sub(r"\n{3,}", "\n\n", new_text)
    target.write_text(new_text, encoding="utf-8")
    sys.stderr.write(
        f"[openclaw install] removed managed section from {target}\n"
    )
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--home", default=str(Path.home()),
                        help="Home directory (default: $HOME)")
    parser.add_argument("--target",
                        help="Explicit SOUL.md path (default: resolve from openclaw.json)")
    parser.add_argument("--snippet", required=True,
                        help="Path to the rendered SOUL.md.snippet")
    parser.add_argument("--agent-id", default=DEFAULT_AGENT_ID,
                        help=f"OpenClaw agent id (default: {DEFAULT_AGENT_ID})")
    parser.add_argument("--uninstall", action="store_true",
                        help="Remove the MPM managed section from target")
    args = parser.parse_args(argv)

    home = Path(args.home).expanduser()
    target = resolve_openclaw_target(home, args.agent_id, args.target)
    snippet = Path(args.snippet).expanduser()

    if not snippet.is_file():
        sys.stderr.write(f"[openclaw install] ERROR: snippet not found: {snippet}\n")
        return 4

    if args.uninstall:
        return do_uninstall(target)
    return do_install(target, snippet)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
