// cmd/gen-readme/main.go — README generator for the MCP tool surface.
//
// Run via:  go generate ./internal/tools/
//
// Or directly:  go run ./cmd/gen-readme
//
// The generator rewrites the block between sentinel comments in
// README.md based on the live tools.Registry (via
// tools.RenderToolSurface). Re-running the generator is idempotent —
// the file is rewritten in place between the sentinels and never
// edited by hand outside them.
//
// Why this exists: the README previously claimed 33 tools while the
// registry held 43. Manual sync had drifted silently. With this
// generator, the doc invariant becomes "I added a tool to
// registry_list.go and ran `go generate ./...` — the README is now
// correct." Drift is now caught at `go generate` time, not at
// agent-attachment time when an MCP client can't find a tool.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"mpm/internal/tools"
)

// Sentinels that bracket the generated block in README.md.
const (
	readmeBeginSentinel = "<!-- tools:begin — auto-generated by `go generate ./internal/tools/`. Do not edit by hand. -->"
	readmeEndSentinel   = "<!-- tools:end — auto-generated by `go generate ./internal/tools/`. Do not edit by hand. -->"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen_readme: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	readmePath, err := findReadmePath()
	if err != nil {
		return fmt.Errorf("locate README: %w", err)
	}
	data, err := os.ReadFile(readmePath)
	if err != nil {
		return fmt.Errorf("read %s: %w", readmePath, err)
	}
	content := string(data)

	beginIdx := strings.Index(content, readmeBeginSentinel)
	endIdx := strings.Index(content, readmeEndSentinel)
	if beginIdx < 0 || endIdx < 0 {
		return fmt.Errorf("README missing one or both sentinels — add them around the MCP tool surface block:\n  %s\n  %s",
			readmeBeginSentinel, readmeEndSentinel)
	}
	if endIdx <= beginIdx {
		return fmt.Errorf("README sentinels in wrong order: begin at %d, end at %d", beginIdx, endIdx)
	}

	// Replace the entire span from beginIdx through endIdx (inclusive
	// of the end sentinel). Preserve the original prefix/suffix so the
	// rendered block stays inside its code fence.
	beginLineStart := strings.LastIndex(content[:beginIdx], "\n") + 1
	endLineEnd := strings.Index(content[endIdx:], "\n")
	if endLineEnd < 0 {
		endLineEnd = len(content) - endIdx
	} else {
		endLineEnd += endIdx
	}

	prefix := content[beginLineStart:beginIdx]
	suffix := content[endIdx:endLineEnd]

	var newBlock strings.Builder
	newBlock.WriteString(prefix)
	newBlock.WriteString(readmeBeginSentinel)
	newBlock.WriteString("\n")
	newBlock.WriteString(tools.RenderToolSurface())
	newBlock.WriteString(readmeEndSentinel)
	newBlock.WriteString(suffix)

	newContent := content[:beginLineStart] + newBlock.String() + content[endLineEnd:]
	if newContent == content {
		fmt.Printf("%s unchanged\n", readmePath)
		return nil
	}
	if err := os.WriteFile(readmePath, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write %s: %w", readmePath, err)
	}
	fmt.Printf("updated %s (%d tools)\n", readmePath, len(tools.Registry))
	return nil
}

// findReadmePath locates README.md by walking up from cwd. Override
// via MPM_README env var.
func findReadmePath() (string, error) {
	if p := os.Getenv("MPM_README"); p != "" {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
		return "", fmt.Errorf("MPM_README=%s not found", p)
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for i := 0; i < 5; i++ {
		candidate := filepath.Join(dir, "README.md")
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("README.md not found in %s or any parent (up to 5 levels); set MPM_README to override", wd)
}
