"""
test_no_obsolete_paths.py — Regression coverage for the lifecycle-layout
restructure (2026-09-17).

Architectural contract:

  Active operational source/docs MUST NOT reference the obsolete
  ``scripts/install.sh`` path. The canonical installer path is
  ``install.sh`` at the repo root. The canonical deploy script is
  ``scripts/deploy.sh``.

  Historical dated documents (docs/archive/**) are explicitly excluded
  — rewriting past reality would falsify the history.

This test enforces the invariant without false positives by:
  - scanning only ACTIVE tracked files (not docs/archive/**),
  - allowing documentation/comments that describe the migration in
    past tense ("formerly at scripts/install.sh", "moved from ...").
"""

from __future__ import annotations

import re
import subprocess
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]


# Files that legitimately mention the historical path for narrative
# reasons (release notes, changelog entries, history commits). These
# are tracked but exempt.
HISTORICAL_FILES_ALLOWLIST = {
    "changelog.md",
    # Auto-generated by git; not part of the operational surface.
}

# Directories that are explicitly out of scope (historical archive).
EXCLUDED_PATH_PREFIXES = (
    "docs/archive/",
    "docs/superpowers/plans/",  # plans describe intent, may quote past
)

# Patterns that count as "the path is actually used as a path" (not a
# narrative mention). We only flag matches where the line uses the path
# as an instruction or invocation form.
PATH_USE_PATTERNS = [
    re.compile(r"`?scripts/install\.sh`?"),
    re.compile(r"`?\./scripts/install\.sh`?"),
    re.compile(r"\bsh\s+scripts/install\.sh\b"),
    re.compile(r"\bbash\s+scripts/install\.sh\b"),
    # As a referent for an installer script (e.g., "the install.sh at
    # scripts/install.sh" — narrative). Skip narrative-only matches
    # by looking for shell-style or path-prefix usage.
]


def _list_tracked_files() -> list[str]:
    """Return relative paths of all tracked files in the repo."""
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _is_active_operational(rel: str) -> bool:
    """Return True if the file is part of the active operational surface
    (source, scripts, agent_installation, Makefile, README, docs/INSTALL,
    AGENTS, CLAUDE). Excludes historical/changelog directories."""
    if rel in HISTORICAL_FILES_ALLOWLIST:
        return False
    if any(rel.startswith(p) for p in EXCLUDED_PATH_PREFIXES):
        return False
    # Active surface: anything tracked that isn't in docs/archive or
    # changelog.md. The list_tracked_files() call returns the source
    # of truth; we filter further.
    if rel.startswith("docs/archive/"):
        return False
    return True


def _looks_like_active_use(line: str) -> bool:
    """True if the line uses scripts/install.sh as a path (not as a
    narrative mention like 'see the previous scripts/install.sh')."""
    for pat in PATH_USE_PATTERNS:
        if pat.search(line):
            return True
    return False


class TestNoObsoleteInstallPaths(unittest.TestCase):
    """Spec §3: active operational files must not reference
    scripts/install.sh as the canonical path."""

    def test_active_files_no_obsolete_install_sh(self):
        offenders: list[tuple[str, int, str]] = []
        for rel in _list_tracked_files():
            if not _is_active_operational(rel):
                continue
            path = REPO_ROOT / rel
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except (OSError, UnicodeDecodeError):
                continue
            for n, line in enumerate(text.splitlines(), 1):
                if _looks_like_active_use(line):
                    offenders.append((rel, n, line.strip()))
        if offenders:
            msg = "\n".join(f"  {r}:{ln}: {txt}" for r, ln, txt in offenders)
            self.fail(
                f"active operational files reference obsolete 'scripts/install.sh':\n{msg}\n"
                "Use the canonical './install.sh' at the repo root."
            )


class TestCanonicalLifecycleFiles(unittest.TestCase):
    """Spec §1: the canonical lifecycle files exist and are executable."""

    def test_install_sh_exists_at_repo_root(self):
        self.assertTrue(
            (REPO_ROOT / "install.sh").is_file(),
            "install.sh missing at repo root",
        )

    def test_uninstall_sh_exists_at_repo_root(self):
        self.assertTrue(
            (REPO_ROOT / "uninstall.sh").is_file(),
            "uninstall.sh missing at repo root",
        )

    def test_deploy_sh_exists_under_scripts(self):
        self.assertTrue(
            (REPO_ROOT / "scripts" / "deploy.sh").is_file(),
            "scripts/deploy.sh missing",
        )

    def test_install_sh_is_executable(self):
        import stat
        mode = (REPO_ROOT / "install.sh").stat().st_mode
        self.assertTrue(mode & stat.S_IXUSR, "install.sh is not executable")

    def test_uninstall_sh_is_executable(self):
        import stat
        mode = (REPO_ROOT / "uninstall.sh").stat().st_mode
        self.assertTrue(mode & stat.S_IXUSR, "uninstall.sh is not executable")

    def test_deploy_sh_is_executable(self):
        import stat
        mode = (REPO_ROOT / "scripts" / "deploy.sh").stat().st_mode
        self.assertTrue(mode & stat.S_IXUSR, "scripts/deploy.sh is not executable")

    def test_no_install_sh_under_scripts(self):
        self.assertFalse(
            (REPO_ROOT / "scripts" / "install.sh").exists(),
            "scripts/install.sh still exists; should have been moved to repo root",
        )


if __name__ == "__main__":
    unittest.main()
