// Tests for the cron-kind wake retention sweep
// (wake_expiration.go, CronRetentionTickHandler / SweepOverdueCronWakes).
//
// The cron sweep retires cron-kind scheduled_wakes whose
// target_time is more than CronRetentionWindow in the past. Cron rows
// are bookkeeping for one-shot events generated by a recurring
// schedule; the ad-hoc dispatcher never claims them by design (the
// 2026-09-04 100% CPU wedge regression test pins that — see
// TestScheduler_DoesNotWedgeOnPastCronKindWake). Without this
// sweep, those rows accumulate indefinitely.
//
// Every guarantee from the wake_expiration.go cron-retention
// doc-comment is pinned below.

package scheduler

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"testing"
	"time"
)

// seedCronWake inserts a cron-kind wake with a target_time and the
// canonical cron metadata blob (matches what ProcessScheduledTasks
// actually writes).
func seedCronWake(t *testing.T, s *Scheduler, targetTime time.Time, taskID string) string {
	t.Helper()
	id := "cron-" + strconv.FormatInt(targetTime.UnixNano(), 10) + "-" + taskID
	reason := "cron:" + taskID
	metadata := fmt.Sprintf(`{"kind":"cron","task_id":%q,"directive_id":%q}`,
		taskID, "mpm-seed-epistemic-compaction-policy")
	if _, err := s.db.Exec(`
		INSERT INTO scheduled_wakes (id, target_time, reason, created_by, fired, metadata)
		VALUES (?, ?, ?, ?, 0, ?)
	`, id, targetTime.Unix(), reason, "mpm-scheduler", metadata); err != nil {
		t.Fatalf("seed cron wake: %v", err)
	}
	return id
}

// TestCronSweep_RetainsRecentCronWakes — the grace period.
//
// A cron wake overdue by less than CronRetentionWindow must remain
// unfired. This is the "no false-positive retirement" guarantee. The
// audit window exists so an operator inspecting `mpm list_wakes`
// immediately after a cron fire still sees the row.
func TestCronSweep_RetainsRecentCronWakes(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Three recent cron rows: 1 minute, 30 minutes, 59 minutes.
	// All three are well inside the 1h window.
	seedCronWake(t, s, now.Add(-1*time.Minute), "epistemic-compaction")
	seedCronWake(t, s, now.Add(-30*time.Minute), "epistemic-compaction")
	seedCronWake(t, s, now.Add(-59*time.Minute), "epistemic-compaction")

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != 0 {
		t.Errorf("sweep retired %d recent cron wakes, want 0", retired)
	}

	// Confirm every row is still unfired.
	var firedCount int
	if err := s.db.QueryRow(
		`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`,
	).Scan(&firedCount); err != nil {
		t.Fatalf("count fired: %v", err)
	}
	if firedCount != 0 {
		t.Errorf("fired count = %d, want 0 (under 1h cron retention)", firedCount)
	}
}

// TestCronSweep_RetiresOldCronWakes — the retirement path.
//
// A cron wake overdue by more than CronRetentionWindow must transition
// to fired=1, fired_at=now, with the cron audit note in metadata.
func TestCronSweep_RetiresOldCronWakes(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Three old cron rows: 2h, 1d, 7d. All past the 1h window.
	id2h := seedCronWake(t, s, now.Add(-2*time.Hour), "epistemic-compaction")
	id1d := seedCronWake(t, s, now.Add(-24*time.Hour), "epistemic-compaction")
	id7d := seedCronWake(t, s, now.Add(-7*24*time.Hour), "epistemic-compaction")

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != 3 {
		t.Errorf("sweep retired %d, want 3", retired)
	}

	for _, id := range []string{id2h, id1d, id7d} {
		fired, firedAt, metadata := readWakeFired(t, s.db, id)
		if fired != 1 {
			t.Errorf("%s: fired=%d, want 1", id, fired)
		}
		if firedAt != now.Unix() {
			t.Errorf("%s: fired_at=%d, want %d", id, firedAt, now.Unix())
		}
		reason := extractMetadataString(metadata, ExpirationMetadataKey+".reason")
		if reason != CronRetentionReasonValue {
			t.Errorf("%s: expired.reason=%q, want %q", id, reason, CronRetentionReasonValue)
		}
	}
}

// TestCronSweep_BoundedByNormalLimit — the 60 normal cap.
//
// Seeds 100 obsolete cron rows, runs the sweep with the normal cap
// (60). Exactly 60 must retire; the remaining 40 must remain. A
// second sweep drains the rest.
func TestCronSweep_BoundedByNormalLimit(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	const seed = 100
	for i := 0; i < seed; i++ {
		// Spread target_time across the past 2h..10h to ensure all
		// are past the retention window but ordered deterministically.
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != CronRetentionNormalLimit {
		t.Errorf("sweep retired %d, want %d (normal cap)", retired, CronRetentionNormalLimit)
	}

	var pendingCount int
	if err := s.db.QueryRow(
		`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 0`,
	).Scan(&pendingCount); err != nil {
		t.Fatalf("count pending: %v", err)
	}
	if pendingCount != seed-CronRetentionNormalLimit {
		t.Errorf("pending count = %d, want %d", pendingCount, seed-CronRetentionNormalLimit)
	}

	// Second call drains the rest.
	retired2, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("second sweep: %v", err)
	}
	if retired2 != seed-CronRetentionNormalLimit {
		t.Errorf("second sweep retired %d, want %d (drain remainder)", retired2, seed-CronRetentionNormalLimit)
	}
}

// TestCronSweep_BoundedByCatchUpLimit — the 180 catch-up cap.
//
// Seeds 250 obsolete cron rows, runs the sweep with the catch-up cap
// (180). Exactly 180 must retire; the remaining 70 must remain.
//
// This is the deterministic rule: the tick handler picks
// CronRetentionCatchUpLimit when the eligible backlog at start of
// sweep is ≥ CronRetentionCatchUpThreshold. This test exercises the
// same path directly via SweepOverdueCronWakes with the catch-up cap.
func TestCronSweep_BoundedByCatchUpLimit(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	const seed = 250
	for i := 0; i < seed; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionCatchUpLimit)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != CronRetentionCatchUpLimit {
		t.Errorf("sweep retired %d, want %d (catch-up cap)", retired, CronRetentionCatchUpLimit)
	}

	var pendingCount int
	if err := s.db.QueryRow(
		`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 0`,
	).Scan(&pendingCount); err != nil {
		t.Fatalf("count pending: %v", err)
	}
	if pendingCount != seed-CronRetentionCatchUpLimit {
		t.Errorf("pending count = %d, want %d", pendingCount, seed-CronRetentionCatchUpLimit)
	}
}

// TestCronSweep_HardCeiling180 — the per-call maximum.
//
// Seeds 500 obsolete cron rows, runs the sweep with maxRows=10000
// (an absurd caller-supplied cap). The sweep must still cap at
// CronRetentionCatchUpLimit (180), never processing more rows per
// call regardless of what the caller asked for.
func TestCronSweep_HardCeiling180(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	const seed = 500
	for i := 0; i < seed; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, 10000)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != CronRetentionCatchUpLimit {
		t.Errorf("sweep retired %d, want %d (hard ceiling 180 even when caller asked for 10000)",
			retired, CronRetentionCatchUpLimit)
	}
}

// TestCronSweep_DoesNotRetireNonCronKinds — the kind boundary.
//
// The sweep must NEVER retire non-cron rows. Notification-kind
// rows are swept by the separate notification sweep (which uses a
// 7-day window); snapshot/critic_audit/etc. are dispatched eagerly.
// A cron sweep must not touch any of them even when they are 30
// days overdue.
func TestCronSweep_DoesNotRetireNonCronKinds(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	for _, kind := range []string{"notification", "snapshot", "critic_audit", "gc", "cascade"} {
		seedWake(t, s, "noncron-"+kind, now.Add(-30*24*time.Hour), kind)
	}

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionCatchUpLimit)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != 0 {
		t.Errorf("sweep retired %d non-cron rows, want 0", retired)
	}

	for _, kind := range []string{"notification", "snapshot", "critic_audit", "gc", "cascade"} {
		fired, _, _ := readWakeFired(t, s.db, "noncron-"+kind)
		if fired != 0 {
			t.Errorf("noncron-%s fired=%d after cron sweep, want 0", kind, fired)
		}
	}
}

// TestCronSweep_IsIdempotent — double-sweep is a no-op.
//
// Running the sweep twice on the same input retires 0 rows the
// second time. The fired=1 filter excludes already-retired rows.
func TestCronSweep_IsIdempotent(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	for i := 0; i < 5; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	first, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("first sweep: %v", err)
	}
	if first != 5 {
		t.Fatalf("first sweep retired %d, want 5", first)
	}

	second, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("second sweep: %v", err)
	}
	if second != 0 {
		t.Errorf("second sweep retired %d, want 0 (idempotent)", second)
	}
}

// TestCronSweepTickHandler_GatesOnCadence — the tick handler does
// not work more than once per CronRetentionCadence.
func TestCronSweepTickHandler_GatesOnCadence(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Seed 100 obsolete cron rows.
	for i := 0; i < 100; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	handler := CronRetentionTickHandler(context.Background(), s.db)

	// First call should retire up to the normal cap (60).
	if err := handler(context.Background()); err != nil {
		t.Fatalf("first tick: %v", err)
	}
	var firedAfterFirst int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&firedAfterFirst); err != nil {
		t.Fatalf("count: %v", err)
	}
	if firedAfterFirst != CronRetentionNormalLimit {
		t.Errorf("after first tick: fired=%d, want %d", firedAfterFirst, CronRetentionNormalLimit)
	}

	// Second call within the cadence must be a no-op — even though
	// 40 rows remain eligible, the cadence gate short-circuits.
	if err := handler(context.Background()); err != nil {
		t.Fatalf("second tick: %v", err)
	}
	var firedAfterSecond int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&firedAfterSecond); err != nil {
		t.Fatalf("count: %v", err)
	}
	if firedAfterSecond != CronRetentionNormalLimit {
		t.Errorf("after second tick: fired=%d, want %d (cadence-gated, must not advance)",
			firedAfterSecond, CronRetentionNormalLimit)
	}
}

// TestCronSweepTickHandler_PicksCatchUpCapOnLargeBacklog — the
// deterministic catch-up trigger.
//
// When the eligible backlog at probe time is ≥
// CronRetentionCatchUpThreshold (240), the tick handler must use the
// catch-up cap (180) instead of the normal cap (60).
func TestCronSweepTickHandler_PicksCatchUpCapOnLargeBacklog(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Seed exactly CronRetentionCatchUpThreshold obsolete cron rows.
	for i := 0; i < CronRetentionCatchUpThreshold; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	handler := CronRetentionTickHandler(context.Background(), s.db)
	if err := handler(context.Background()); err != nil {
		t.Fatalf("handler: %v", err)
	}

	var firedCount int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&firedCount); err != nil {
		t.Fatalf("count: %v", err)
	}
	// Catch-up cap is 180, so a single tick retires at most 180 of
	// the 240 eligible rows.
	if firedCount != CronRetentionCatchUpLimit {
		t.Errorf("catch-up sweep retired %d, want %d (catch-up cap)", firedCount, CronRetentionCatchUpLimit)
	}
}

// TestCronSweepTickHandler_ProductionRateBounded — the long-term
// boundedness invariant.
//
// Simulates ~60 cron rows/hour of production (the realistic
// epistemic-compaction rate) across multiple cleanup cycles and
// verifies the backlog does not grow without bound.
func TestCronSweepTickHandler_ProductionRateBounded(t *testing.T) {
	s := newTestScheduler(t)
	handler := CronRetentionTickHandler(context.Background(), s.db)

	// Simulate 3 hours of cron production at 60 rows/hour = 180 rows
	// total. Each row's target_time must be past CronRetentionWindow
	// (1h) — so we age everything into the [now-4h, now-1h-1min]
	// window. Anything more recent than 1h is under retention.
	base := time.Now().Add(-4 * time.Hour)
	for hour := 0; hour < 3; hour++ {
		hourBase := base.Add(time.Duration(hour) * time.Hour)
		for minute := 0; minute < 60; minute++ {
			seedCronWake(t, s, hourBase.Add(time.Duration(minute)*time.Minute), "epistemic-compaction")
		}
	}

	// Sweep 1: normal cadence, normal cap.
	if err := handler(context.Background()); err != nil {
		t.Fatalf("sweep 1: %v", err)
	}
	var firedAfter1 int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&firedAfter1); err != nil {
		t.Fatalf("count: %v", err)
	}
	if firedAfter1 != CronRetentionNormalLimit {
		t.Errorf("sweep 1 fired %d, want %d (normal cap matches 1 hour production)",
			firedAfter1, CronRetentionNormalLimit)
	}

	// Force a second sweep by resetting the cadence gate. In
	// production this would happen naturally after Cadence elapses.
	// For the test we directly invoke SweepOverdueCronWakes again
	// (the tick handler refuses to run twice within Cadence; the
	// underlying function honors the cap correctly).
	retired, err := SweepOverdueCronWakes(context.Background(), s.db, time.Now(), CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("direct sweep 2: %v", err)
	}
	if retired != CronRetentionNormalLimit {
		t.Errorf("direct sweep 2 retired %d, want %d", retired, CronRetentionNormalLimit)
	}

	// Third sweep drains the remainder.
	retired3, err := SweepOverdueCronWakes(context.Background(), s.db, time.Now(), CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("direct sweep 3: %v", err)
	}
	// 180 total - 60 - 60 = 60 remaining.
	want3 := 180 - 2*CronRetentionNormalLimit
	if retired3 != want3 {
		t.Errorf("direct sweep 3 retired %d, want %d", retired3, want3)
	}

	// No backlog remains.
	var pendingCount int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 0`).Scan(&pendingCount); err != nil {
		t.Fatalf("count pending: %v", err)
	}
	if pendingCount != 0 {
		t.Errorf("pending after 3 sweeps = %d, want 0 (production rate stays bounded)", pendingCount)
	}
}

// TestCronSweep_PreservesMetadata — the metadata merge contract.
//
// Existing metadata keys (set by ProcessScheduledTasks — kind, task_id,
// directive_id) must survive the sweep. The sweep only ADDS the
// expiration keys.
func TestCronSweep_PreservesMetadata(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	id := seedCronWake(t, s, now.Add(-2*time.Hour), "epistemic-compaction")

	if _, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit); err != nil {
		t.Fatalf("sweep: %v", err)
	}

	_, _, metadata := readWakeFired(t, s.db, id)
	if !strings.Contains(metadata, `"kind":"cron"`) {
		t.Errorf("existing metadata destroyed: %s", metadata)
	}
	if !strings.Contains(metadata, `"task_id":"epistemic-compaction"`) {
		t.Errorf("existing metadata destroyed: %s", metadata)
	}
	if !strings.Contains(metadata, CronRetentionReasonValue) {
		t.Errorf("expiration reason missing: %s", metadata)
	}

	// Verify the audit note is itself valid JSON.
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(metadata), &parsed); err != nil {
		t.Fatalf("post-sweep metadata is not valid JSON: %v (%s)", err, metadata)
	}
	if exp, ok := parsed["expired"].(map[string]interface{}); !ok {
		t.Errorf("expired metadata block missing: %s", metadata)
	} else {
		if exp["reason"] != CronRetentionReasonValue {
			t.Errorf("expired.reason=%v, want %q", exp["reason"], CronRetentionReasonValue)
		}
	}
}

// TestCronSweepTickHandler_ConcurrentSafe — concurrency & idempotence.
//
// Two concurrent tick handlers must both succeed and not double-fire
// or miss rows. Each individual sweep is a SQLite transaction with
// row-level state checks; interleaving produces at-most-as-many
// retirements as eligible rows.
func TestCronSweepTickHandler_ConcurrentSafe(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Seed 120 obsolete cron rows — enough for both handlers to
	// each retire up to CronRetentionNormalLimit (60) rows.
	const seed = 120
	for i := 0; i < seed; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	h1 := CronRetentionTickHandler(context.Background(), s.db)
	h2 := CronRetentionTickHandler(context.Background(), s.db)

	// Run them concurrently — each handler has its own cadence
	// state so the gate does not serialize them.
	done := make(chan error, 2)
	go func() { done <- h1(context.Background()) }()
	go func() { done <- h2(context.Background()) }()
	if err := <-done; err != nil {
		t.Fatalf("h1: %v", err)
	}
	if err := <-done; err != nil {
		t.Fatalf("h2: %v", err)
	}

	// Each handler may have done up to NormalLimit. Total retirements
	// may be ≤ 2*NormalLimit (some overlap is OK; the SQLite-level
	// UPDATE is row-atomic so no row is double-counted in fired=1
	// state). The hard floor: no row should be retired twice (fired
	// stays at 1, fired_at unchanged on second hit).
	var firedCount int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&firedCount); err != nil {
		t.Fatalf("count: %v", err)
	}
	if firedCount < CronRetentionNormalLimit {
		t.Errorf("fired=%d, want at least %d (one sweep should have retired normal cap)", firedCount, CronRetentionNormalLimit)
	}
	if firedCount > 2*CronRetentionNormalLimit {
		t.Errorf("fired=%d, want at most %d (two sweeps, no double-fire)", firedCount, 2*CronRetentionNormalLimit)
	}
}

// TestCronSweep_DropsRetiredFromOverdueQuery — the wakes_overdue
// integration guarantee.
//
// This is the central test of the whole arc: a cron row past
// CronRetentionWindow, after a sweep, must NOT count in
// wakes_overdue. The query that powers wakes_overdue filters on
// fired=0; the sweep sets fired=1.
//
// We exercise the same SQL the production wakes_overdue health
// query uses (internal/core/db.go) so this test pins the contract
// end-to-end: cron rows past retention are boundedly retired by the
// sweep, and a subsequent wakes_overdue query reflects reality.
func TestCronSweep_DropsRetiredFromOverdueQuery(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Seed 50 obsolete cron rows + 5 notification-kind rows that
	// are overdue but still actionable.
	for i := 0; i < 50; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}
	for i := 0; i < 5; i++ {
		seedWake(t, s, "actionable-"+strconv.Itoa(i), now.Add(-1*time.Hour), "notification")
	}

	// Run a single normal-mode sweep — retires 60 of the 50+ cron rows
	// (capped by limit, not by candidate count). All 50 cron rows are
	// past retention so all 50 retire.
	if _, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit); err != nil {
		t.Fatalf("sweep: %v", err)
	}

	// Actionable overdue: only the 5 notifications. Cron rows must
	// NOT contribute to wakes_overdue.
	var actionableOverdue int
	err := s.db.QueryRow(`
		SELECT COUNT(*) FROM scheduled_wakes
		WHERE fired = 0
		  AND target_time < ?
		  AND (
		    metadata IS NULL OR metadata = ''
		    OR json_extract(metadata, '$.kind') IS NULL
		    OR json_extract(metadata, '$.kind') = ''
		    OR json_extract(metadata, '$.kind') IN ('notification','cascade')
		  )
	`, now.Unix()).Scan(&actionableOverdue)
	if err != nil {
		t.Fatalf("query actionable overdue: %v", err)
	}
	if actionableOverdue != 5 {
		t.Errorf("actionable overdue = %d, want 5 (only notifications; cron excluded)", actionableOverdue)
	}

	// Crude wakes_overdue (without kind filter) still counts cron +
	// actionable. Cron dominates here — exactly the bug.
	var crudeOverdue int
	if err := s.db.QueryRow(
		`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 0 AND target_time < ?`,
		now.Unix(),
	).Scan(&crudeOverdue); err != nil {
		t.Fatalf("query crude overdue: %v", err)
	}
	if crudeOverdue != 5 {
		t.Errorf("crude overdue = %d, want 5 (post-sweep, all cron rows fired)", crudeOverdue)
	}
}

// TestCronSweep_DoesNotDispatchOldCronEvents — the CPU-protection
// regression.
//
// A cron row, even after the sweep retires it (fired=1), must not be
// re-dispatched. The ad-hoc dispatcher's claim filter excludes cron
// kind entirely (dispatch.go:80-87), so this is structurally
// guaranteed. This test pins that the sweep does not change that:
// even with a large cron backlog, no cron row ends up in the
// dispatcher's claim set.
func TestCronSweep_DoesNotDispatchOldCronEvents(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Many cron rows — pre and post retention. Mix in some
	// notifications.
	for i := 0; i < 50; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+1)*time.Hour), "epistemic-compaction")
	}
	seedWake(t, s, "live-notification", now.Add(-1*time.Hour), "notification")

	if _, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionCatchUpLimit); err != nil {
		t.Fatalf("sweep: %v", err)
	}

	// Verify the dispatch claim query (matches dispatchClaimNextAdHocWake)
	// never returns a cron row.
	var cronClaimed int
	err := s.db.QueryRow(`
		SELECT COUNT(*) FROM scheduled_wakes
		WHERE fired = 0
		  AND target_time <= ?
		  AND (
		    metadata IS NULL OR metadata = ''
		    OR json_extract(metadata, '$.kind') IS NULL
		    OR json_extract(metadata, '$.kind') = ''
		    OR json_extract(metadata, '$.kind') = 'notification'
		  )
		  AND json_extract(metadata, '$.kind') = 'cron'
	`, now.Unix()).Scan(&cronClaimed)
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	if cronClaimed != 0 {
		t.Errorf("cron rows in dispatch claim set: %d, want 0", cronClaimed)
	}

	// And the live notification must still be in the claim set
	// (we did NOT touch it).
	var liveNotifFired int
	if err := s.db.QueryRow(`SELECT fired FROM scheduled_wakes WHERE id = 'live-notification'`).Scan(&liveNotifFired); err != nil {
		t.Fatalf("read live-notification: %v", err)
	}
	if liveNotifFired != 0 {
		t.Errorf("live-notification fired=%d, want 0 (sweep must not touch non-cron)", liveNotifFired)
	}
}

// TestCronSweepTickHandler_EligibleBacklogBoundedLookup — the
// probe must use a bounded query.
//
// The probe (cronRetentionProbeBacklog) is called on every
// cadence-eligible tick to decide normal vs catch-up cap. It must
// NEVER execute a full COUNT(*) — only a bounded LIMIT 241.
//
// This test verifies the probe returns 241 even when the underlying
// eligible count is much higher (LIMIT clamps the inner SELECT).
func TestCronSweepTickHandler_EligibleBacklogBoundedLookup(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// 500 obsolete cron rows. The probe's LIMIT caps the inner
	// COUNT at CronRetentionCatchUpThreshold+1 = 241, so the
	// probe result is 241 regardless of actual eligible count.
	for i := 0; i < 500; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	got, err := cronRetentionProbeBacklog(context.Background(), s.db, now.Unix())
	if err != nil {
		t.Fatalf("probe: %v", err)
	}
	want := CronRetentionCatchUpThreshold + 1
	if got != want {
		t.Errorf("probe returned %d, want %d (must clamp at LIMIT %d)",
			got, want, CronRetentionCatchUpThreshold+1)
	}
}

// TestCronSweep_BacklogConvergesAcrossCycles — eventual drain.
//
// 1000 obsolete cron rows; three catch-up sweeps (180 each = 540)
// plus one normal sweep (60) drain 600; the remaining 400 need ~3
// more cycles. Verifies the math and the per-call hard ceiling.
func TestCronSweep_BacklogConvergesAcrossCycles(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	const seed = 1000
	for i := 0; i < seed; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	calls := 0
	total := 0
	for total < seed {
		n, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionCatchUpLimit)
		if err != nil {
			t.Fatalf("sweep %d: %v", calls+1, err)
		}
		calls++
		total += n
		if n == 0 {
			t.Fatalf("sweep made no progress at call %d", calls)
		}
		if calls > 20 {
			t.Fatalf("too many sweep cycles (%d) to drain %d rows", calls, seed)
		}
	}

	// Every call processed exactly CronRetentionCatchUpLimit
	// (except possibly the last, which had fewer candidates).
	// Hard ceiling: no single call retired more than that.
	if calls < 6 {
		t.Errorf("drained %d rows in %d calls; expected at least 6 (1000/180 ≈ 5.6)", seed, calls)
	}

	var pendingCount int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 0`).Scan(&pendingCount); err != nil {
		t.Fatalf("count pending: %v", err)
	}
	if pendingCount != 0 {
		t.Errorf("pending after convergence = %d, want 0", pendingCount)
	}
}

// TestCronSweep_DatabaseNotUsedByHandlerBeyondProbe — the
// tick-handler probe is the only DB query on idle ticks.
//
// When state.lastSweepUnix > 0 and Cadence has not elapsed, the
// handler must return immediately without touching the DB. The
// SQLite file mtime should not change across calls in this state.
func TestCronSweep_DatabaseNotUsedByHandlerBeyondProbe(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Seed one eligible row so the first sweep does work.
	seedCronWake(t, s, now.Add(-2*time.Hour), "epistemic-compaction")

	handler := CronRetentionTickHandler(context.Background(), s.db)

	// First call: does work, advances lastSweepUnix.
	if err := handler(context.Background()); err != nil {
		t.Fatalf("first: %v", err)
	}

	// Subsequent calls within Cadence must return immediately
	// without DB query. We can't directly observe "no DB query"
	// from a black-box test, but we can verify the call is a no-op
	// (no panic, no error, no change to fired-count).
	beforeFired := 0
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&beforeFired); err != nil {
		t.Fatalf("count: %v", err)
	}
	for i := 0; i < 5; i++ {
		if err := handler(context.Background()); err != nil {
			t.Fatalf("cadence-gated call %d: %v", i, err)
		}
	}
	afterFired := 0
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM scheduled_wakes WHERE fired = 1`).Scan(&afterFired); err != nil {
		t.Fatalf("count: %v", err)
	}
	if afterFired != beforeFired {
		t.Errorf("cadence-gated calls changed fired count: %d -> %d", beforeFired, afterFired)
	}
}

// TestCronSweep_NoOpOnZeroCandidates — empty case.
//
// If no eligible rows exist, the sweep must return (0, nil) without
// touching the DB transactionally.
func TestCronSweep_NoOpOnZeroCandidates(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Only seed a recent (under-window) cron row.
	seedCronWake(t, s, now.Add(-1*time.Minute), "epistemic-compaction")

	retired, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit)
	if err != nil {
		t.Fatalf("sweep: %v", err)
	}
	if retired != 0 {
		t.Errorf("sweep retired %d, want 0 (no eligible rows)", retired)
	}
}

// TestCronSweep_ProductionRateDoesNotInflateWakesOverdue —
// integration with the wakes_overdue metric.
//
// Simulates 1 hour of cron production (60 rows). After the sweep,
// wakes_overdue (with the new kind filter) must remain 0; only
// notification-kind rows would have moved it.
func TestCronSweep_ProductionRateDoesNotInflateWakesOverdue(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// 60 cron rows past retention (production rate × 1h).
	for i := 0; i < 60; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	if _, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit); err != nil {
		t.Fatalf("sweep: %v", err)
	}

	// wakes_overdue with kind filter: zero.
	var actionableOverdue int
	err := s.db.QueryRow(`
		SELECT COUNT(*) FROM scheduled_wakes
		WHERE fired = 0
		  AND target_time < ?
		  AND (
		    metadata IS NULL OR metadata = ''
		    OR json_extract(metadata, '$.kind') IS NULL
		    OR json_extract(metadata, '$.kind') = ''
		    OR json_extract(metadata, '$.kind') IN ('notification','cascade')
		  )
	`, now.Unix()).Scan(&actionableOverdue)
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	if actionableOverdue != 0 {
		t.Errorf("actionable wakes_overdue = %d, want 0 (cron rows must not inflate the metric)", actionableOverdue)
	}
}

// TestCronSweep_SweepUnderManyDifferentCapValues — table-driven
// cap behavior. Verifies the function honors any cap up to the
// hard ceiling and clamps anything higher.
func TestCronSweep_SweepUnderManyDifferentCapValues(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	const seed = 300
	for i := 0; i < seed; i++ {
		seedCronWake(t, s, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
	}

	cases := []struct {
		name    string
		maxRows int
		want    int
	}{
		{"cap_60_normal", 60, 60},
		{"cap_100_below_threshold", 100, 100},
		{"cap_180_catchup", 180, 180},
		{"cap_500_above_hard_ceiling", 500, CronRetentionCatchUpLimit},
		{"cap_99999_above_hard_ceiling", 99999, CronRetentionCatchUpLimit},
		{"cap_0_defaults_to_hard_ceiling", 0, CronRetentionCatchUpLimit},
		{"cap_negative_clamps_to_hard_ceiling", -10, CronRetentionCatchUpLimit},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			fresh := newTestScheduler(t)
			for i := 0; i < seed; i++ {
				seedCronWake(t, fresh, now.Add(-time.Duration(i+2)*time.Hour), "epistemic-compaction")
			}
			got, err := SweepOverdueCronWakes(context.Background(), fresh.db, now, tc.maxRows)
			if err != nil {
				t.Fatalf("sweep: %v", err)
			}
			if got != tc.want {
				t.Errorf("maxRows=%d retired %d, want %d", tc.maxRows, got, tc.want)
			}
		})
	}
}

// TestCronSweep_PreservesExistingSchemaMetadata — defensive
// regression for the metadata preservation contract.
//
// Verifies the sweep's UPDATE ... metadata = json_set(...) call
// does not drop existing JSON keys that the JSON1 library considers
// odd (booleans, null, nested arrays). cron_wakes only ever carry
// a flat object {kind, source, task_id, directive_id} per
// ProcessScheduledTasks, so this is defensive.
func TestCronSweep_PreservesExistingSchemaMetadata(t *testing.T) {
	s := newTestScheduler(t)
	now := time.Now()

	// Seed a cron wake with extra metadata.
	if _, err := s.db.Exec(`
		INSERT INTO scheduled_wakes
		(id, target_time, reason, created_by, fired, metadata)
		VALUES (?, ?, ?, ?, 0, ?)
	`, "cron-with-extra-meta",
		now.Add(-2*time.Hour).Unix(),
		"cron:test-task",
		"mpm-scheduler",
		`{"kind":"cron","task_id":"t1","directive_id":"d1","flag":true,"count":42,"note":null}`,
	); err != nil {
		t.Fatalf("seed: %v", err)
	}

	if _, err := SweepOverdueCronWakes(context.Background(), s.db, now, CronRetentionNormalLimit); err != nil {
		t.Fatalf("sweep: %v", err)
	}

	_, _, metadata := readWakeFired(t, s.db, "cron-with-extra-meta")
	for _, key := range []string{`"flag":true`, `"count":42`, `"note":null`, `"task_id":"t1"`, `"directive_id":"d1"`} {
		if !strings.Contains(metadata, key) {
			t.Errorf("metadata lost key %s: %s", key, metadata)
		}
	}
	if !strings.Contains(metadata, CronRetentionReasonValue) {
		t.Errorf("expiration reason missing: %s", metadata)
	}
}