// run.go — Orchestration: which profiles to probe, in what order, with
// what timeout, and how to merge results back into system_config.
//
// Two public entry points:
//
//   ReadCachedHealth(dm, cfg)            — pure read; no network IO.
//                                        Used by `mpm` no-args.
//   RunActiveProbes(ctx, cfg, dm, opt)  — concurrent real probes.
//                                        Used by `mpm doctor` and `mpm
//                                        config profile (add|set)`. Persists
//                                        bounded results to system_config
//                                        when dm is non-nil.

package probe

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"sync"
	"time"

	mpminternal "github.com/flowbyte-com/mpm-core"
	"github.com/flowbyte-com/mpm-core/config"
)

// disabledFingerprint is the sentinel fingerprint value used for
// intentionally-disabled targets. Using a non-hex string keeps it
// strictly disjoint from real fingerprint hex digests.
const disabledFingerprint = "disabled"

// ProbeTarget is one effective binding to probe. Generated by
// ResolveEffectiveTargets from the live config.
//
// Disabled and dangling components use Profile == nil; the Disabled
// field distinguishes the two so runOneProbe can return ProbeDisabled
// versus ProbeUnknown.
type ProbeTarget struct {
	Kind         ProbeKind
	Component    string   // primary binding name from cfg.Components
	Components   []string // deduped component names binding to this profile (after merge)
	Capabilities []string
	Disabled     bool            // true iff the binding is intentionally disabled
	Profile      *config.Profile // nil for disabled / dangling
}

// CanProbe reports whether the profile has the material fields needed to
// run a real request. Used to filter out incomplete profiles from active
// probing — those would falsely be flagged as runtime health failures.
func CanProbe(p *config.Profile) bool {
	if p == nil {
		return false
	}
	if p.Provider == "" {
		return false
	}
	if p.Model == "" {
		return false
	}
	if p.BaseURL == "" {
		return false
	}
	return true
}

// ResolveEffectiveTargets iterates the live cfg.Components map and produces
// the canonical list of probe targets. Disabled bindings carry Disabled=true
// and Profile=nil; dangling bindings carry Profile=nil and Disabled=false.
//
// A custom component / profile binding absent from DefaultCapabilities is
// probed normally because we iterate the actual Components map — defaults
// do NOT decide what gets probed.
func ResolveEffectiveTargets(cfg *config.Config) []ProbeTarget {
	if cfg == nil {
		return nil
	}
	out := []ProbeTarget{}
	for component, profileName := range cfg.Components {
		capabilities := capabilitiesPointingTo(cfg, component)
		if profileName == "disabled" {
			out = append(out, ProbeTarget{
				Kind:         kindForComponent(component),
				Component:    component,
				Components:   []string{component},
				Capabilities: capabilities,
				Disabled:     true,
			})
			continue
		}
		p := cfg.ProfileFor(component)
		if p == nil {
			out = append(out, ProbeTarget{
				Kind:         kindForComponent(component),
				Component:    component,
				Components:   []string{component},
				Capabilities: capabilities,
			})
			continue
		}
		out = append(out, ProbeTarget{
			Kind:         kindForComponent(component),
			Component:    component,
			Components:   []string{component},
			Capabilities: capabilities,
			Profile:      p,
		})
	}

	out = dedupTargetsByFingerprint(out)
	sort.Slice(out, func(i, j int) bool {
		return componentOrderRank(out[i].Component) < componentOrderRank(out[j].Component)
	})
	return out
}

func kindForComponent(component string) ProbeKind {
	if component == "embedding" {
		return ProbeKindEmbedding
	}
	return ProbeKindGenerative
}

// componentOrderRank orders components for deterministic rendering.
func componentOrderRank(name string) int {
	switch name {
	case "embedding":
		return 0
	case "memory":
		return 1
	case "critic":
		return 2
	}
	return 100 + len(name)
}

// dedupTargetsByFingerprint collapses targets that point at the same
// profile (and therefore share the fingerprint). All-disabled targets all
// carry the sentinel fingerprint and are kept distinct because their
// fingerprint space is small and bounded.
func dedupTargetsByFingerprint(targets []ProbeTarget) []ProbeTarget {
	type acc struct {
		t       ProbeTarget
		compSet map[string]bool
		capSet  map[string]bool
	}
	buckets := map[string]*acc{}
	order := []string{}

	for _, t := range targets {
		fp := fingerprintForTarget(t)
		a, seen := buckets[fp]
		if !seen {
			a = &acc{
				t:       t,
				compSet: map[string]bool{},
				capSet:  map[string]bool{},
			}
			for _, c := range t.Components {
				a.compSet[c] = true
			}
			for _, c := range t.Capabilities {
				a.capSet[c] = true
			}
			buckets[fp] = a
			order = append(order, fp)
			continue
		}
		for _, c := range t.Components {
			a.compSet[c] = true
		}
		for _, c := range t.Capabilities {
			a.capSet[c] = true
		}
	}

	out := make([]ProbeTarget, 0, len(order))
	for _, fp := range order {
		a := buckets[fp]
		merged := a.t
		merged.Components = sortedKeys(a.compSet)
		merged.Capabilities = sortedKeys(a.capSet)
		out = append(out, merged)
	}
	return out
}

func fingerprintForTarget(t ProbeTarget) string {
	if t.Disabled || t.Profile == nil {
		return disabledFingerprint
	}
	return ComputeFingerprint(fingerprintInput{
		Provider:   t.Profile.Provider,
		Model:      t.Profile.Model,
		BaseURL:    t.Profile.BaseURL,
		Credential: t.Profile.APIKey,
	})
}

func sortedKeys(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// capabilitiesPointingTo returns the set of capability labels that resolve
// to the given component name. Used purely for annotation — does NOT gate
// which targets are probed.
func capabilitiesPointingTo(cfg *config.Config, component string) []string {
	seen := map[string]bool{}
	out := []string{}
	add := func(cap, comp string) {
		if comp != component || cap == "" || seen[cap] {
			return
		}
		seen[cap] = true
		out = append(out, cap)
	}
	for k, v := range cfg.Capabilities {
		add(k, v)
	}
	for k, v := range config.DefaultCapabilities {
		add(k, v)
	}
	sort.Strings(out)
	return out
}

// RunActiveProbes runs real-network probes for every effective target.
// Bounded fan-out (4 concurrent). Outer context timeout 30s.
//
// Results are returned AND, if dm is non-nil, a single SaveSystemConfig
// write commits the bounded cache row. Concurrent per-goroutine writes
// to system_config are NOT permitted; the merge-and-write happens here
// once after all probes complete.
func RunActiveProbes(ctx context.Context, cfg *config.Config, dm *mpminternal.DatabaseManager) ([]ProbeResult, error) {
	if cfg == nil {
		return nil, errors.New("probe: nil config")
	}
	targets := ResolveEffectiveTargets(cfg)
	if len(targets) == 0 {
		return nil, nil
	}

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	results := make([]ProbeResult, len(targets))
	var wg sync.WaitGroup
	sem := make(chan struct{}, 4)
	for i, t := range targets {
		i, t := i, t
		wg.Add(1)
		go func() {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			results[i] = runOneProbe(ctx, t)
		}()
	}
	wg.Wait()

	if dm != nil {
		existing, _ := LoadCache(dm)
		currentFps := map[string]struct{}{}
		for _, t := range targets {
			currentFps[fingerprintForTarget(t)] = struct{}{}
		}
		merged := MergeCache(existing, results, currentFps)
		if err := SaveCache(dm, merged); err != nil {
			return results, fmt.Errorf("save probe cache: %w", err)
		}
	}
	return results, nil
}

// runOneProbe executes a single probe. Disabled targets return
// ProbeDisabled; dangling bindings return ProbeUnknown with summary;
// incomplete profiles return ProbeUnknown without performing IO.
func runOneProbe(ctx context.Context, t ProbeTarget) ProbeResult {
	now := time.Now()
	if t.Disabled {
		return ProbeResult{
			Kind:         t.Kind,
			Components:   t.Components,
			Capabilities: t.Capabilities,
			Status:       ProbeDisabled,
			ErrorSummary: "intentionally disabled",
			CheckedAt:    now,
		}
	}
	if t.Profile == nil {
		return ProbeResult{
			Kind:         t.Kind,
			Components:   t.Components,
			Capabilities: t.Capabilities,
			Status:       ProbeUnknown,
			ErrorSummary: fmt.Sprintf("profile %q not found", t.Component),
			CheckedAt:    now,
		}
	}
	if !CanProbe(t.Profile) {
		return ProbeResult{
			Kind:         t.Kind,
			Components:   t.Components,
			Capabilities: t.Capabilities,
			Provider:     t.Profile.Provider,
			Model:        t.Profile.Model,
			BaseURL:      t.Profile.BaseURL,
			BaseURLSafe:  sanitizeURL(t.Profile.BaseURL),
			Status:       ProbeUnknown,
			ErrorSummary: "profile not executable (provider/model/base_url required)",
			CheckedAt:    now,
		}
	}
	var r ProbeResult
	if t.Kind == ProbeKindEmbedding {
		r = probeEmbedding(ctx, t.Profile)
	} else {
		r = probeGenerative(ctx, t.Profile, ProbeKindGenerative)
	}
	r.Components = t.Components
	r.Capabilities = t.Capabilities
	return r
}

// ReadCachedHealth reads the bounded system_config cache row and returns
// the rows whose fingerprint matches the live effective bindings. Stale
// rows (TTL exceeded) are kept in the result; the renderer decides
// whether to show `?` for stale based on checked_at. Pure read.
func ReadCachedHealth(dm *mpminternal.DatabaseManager, cfg *config.Config) ([]CachedProbe, error) {
	rows, err := LoadCache(dm)
	if err != nil {
		return nil, err
	}
	if cfg == nil {
		return rows, nil
	}

	currentFps := map[string]struct{}{}
	for _, t := range ResolveEffectiveTargets(cfg) {
		currentFps[fingerprintForTarget(t)] = struct{}{}
	}

	out := make([]CachedProbe, 0, len(rows))
	for _, r := range rows {
		if _, ok := currentFps[r.Fingerprint]; !ok {
			continue
		}
		out = append(out, r)
	}
	return out, nil
}

// IsStale reports whether a cached probe record is older than the
// freshness TTL. Exported so render code can tag stale rows with `?`.
func IsStale(c CachedProbe, now time.Time) bool {
	if c.CheckedAt == 0 {
		return true
	}
	return now.Sub(time.Unix(c.CheckedAt, 0)) > DefaultFreshnessTTL
}
