package main

import (
	"fmt"
	mpminternal "github.com/flowbyte-com/mpm-core"
	"github.com/flowbyte-com/mpm-core/usererror"
	"os"
)

// Command describes a single command
type Command struct {
	Name        string
	Description string
	Aliases     []string
	MinArgs     int
	MaxArgs     int
}

// CommandRouter routes commands to handlers
type CommandRouter struct {
	Commands map[string]*Command
	// helpRequested records that an ORIGINAL "-h"/"--help" token appeared
	// anywhere in argv, captured by the caller BEFORE any parseFlags pass
	// rewrote it to the literal token "help". Set in main.go (which runs
	// its own parseFlags pass) and honored in Execute. See the D5 comment
	// at the interception site below.
	helpRequested bool
}

// NewRouter creates a new command router
func NewRouter() *CommandRouter {
	r := &CommandRouter{}

	// Register all commands.
	//
	// Description style: outcome-oriented, terse, capability-named.
	// Persistence verbs (add/remember/decide/theorize/etc.) name the
	// capability the user gains. Inspection verbs (show/list/stats)
	// stay imperative — they describe what the command displays.
	// Parentheticals preserve complex syntax or cognitive-verb mappings.
	//
	// This block is the source of truth for the top-level CLI catalogue.
	// The README projection is generated by `go run ./cmd/gen-cli`.
	r.Commands = map[string]*Command{
		// Info / diagnostics
		"version": {Name: "version", Description: "Show version + build identity", MinArgs: 0, MaxArgs: 0},
		"help":    {Name: "help", Description: "Show CLI catalogue", MinArgs: 0, MaxArgs: 0},
		"doctor":  {Name: "doctor", Description: "Run substrate diagnostics (--deep-scan for FTS/integrity audit, --explain for FTS5 query plan)", MinArgs: 0},

		// Memory verbs — capability-named
		"recall":       {Name: "recall", Description: "Recall relevant context", MinArgs: 1, Aliases: []string{"s"}},
		"add":          {Name: "add", Description: "Persist knowledge (prefix content with `-- ` if it starts with `-`)", MinArgs: 1},
		"ls":           {Name: "ls", Description: "List memories", MinArgs: 0},
		"show":         {Name: "show", Description: "Show memory details", MinArgs: 1},
		"rm":           {Name: "rm", Description: "Delete memory", MinArgs: 1},
		"promote":      {Name: "promote", Description: "Mark as durable (exempt from decay)", MinArgs: 1},
		"patch-memory": {Name: "patch-memory", Description: "Patch memory metadata", MinArgs: 2},
		"reinforce":    {Name: "reinforce", Description: "Record reinforcement (provenance/display; does not affect current retrieval ranking — see §6.3)", MinArgs: 1},
		"weaken":       {Name: "weaken", Description: "Record weakening (provenance/display; does not affect current retrieval ranking — see §6.3)", MinArgs: 1},
		"snooze":       {Name: "snooze", Description: "Suppress from recall (temporary)", MinArgs: 1},
		"set-weight":   {Name: "set-weight", Description: "Set stored weight 0–100 (decay/LTM/provenance; does not affect current retrieval ranking — see §6.3)", MinArgs: 2, MaxArgs: 2},
		"synthesize":   {Name: "synthesize", Description: "Merge near-duplicate memories", MinArgs: 0},
		"shred":        {Name: "shred", Description: "Hard-delete memory", MinArgs: 1},
		"stats":        {Name: "stats", Description: "Show memory statistics", MinArgs: 0},
		"prune":        {Name: "prune", Description: "Prune expired memories", MinArgs: 0},
		"export":       {Name: "export", Description: "Export memories to JSON", MinArgs: 0},
		"integration":  {Name: "integration", Description: "Cross-framework config emitters (export-mcp)", MinArgs: 1},
		"maintain":     {Name: "maintain", Description: "Run self-maintenance sweep", MinArgs: 0},

		// Review
		"review": {Name: "review", Description: "Start spaced-repetition review", MinArgs: 0},

		// Feature namespaces
		"switch":    {Name: "switch", Description: "Switch persona/mode interactively", MinArgs: 0},
		"reference": {Name: "reference", Description: "Manage reference documents", MinArgs: 1},
		"topic":     {Name: "topic", Description: "Manage topics", MinArgs: 1},
		"session":   {Name: "session", Description: "Manage sessions", MinArgs: 1},
		"lesson":    {Name: "lesson", Description: "Manage lessons", MinArgs: 1},
		"memory":    {Name: "memory", Description: "Manage memories", MinArgs: 1},

		// Ingest / cascade / migrate
		"ingest":  {Name: "ingest", Description: "Import from external SQLite"},
		"cascade": {Name: "cascade", Description: "Materialize cascade intents"},
		"migrate": {Name: "migrate", Description: "Import from markdown/JSON (alias to ingest for non-SQLite sources)"},

		// Working Context (cognitive-interface RFC Wave 1)
		"work":      {Name: "work", Description: "Working context scratchpad — status|show|clear|promote"},
		"continue":  {Name: "continue", Description: "Resume previous session — composes working context, wake context, decisions, skills, theories"},

		// Cognitive-verb aliases (Wave 3). Humans express cognition;
		// the substrate contracts (add, record_decision, propose_theory,
		// resolve_theory, save-skill, list-skills, read-skill) stay
		// stable for agent calls.
		"remember": {Name: "remember", Description: "Persist knowledge (cognitive verb for `mpm add`)", MinArgs: 1},
		"learn":    {Name: "learn", Description: "Curate lesson (cognitive verb for `mpm lesson add`)", MinArgs: 1},
		"decide":   {Name: "decide", Description: "Record decision (cognitive verb for `record_decision`)", MinArgs: 0},
		"theorize": {Name: "theorize", Description: "Propose theory (cognitive verb for `propose_theory`)", MinArgs: 1},
		"decision": {Name: "decision", Description: "Decision CRUD"},
		"why":      {Name: "why", Description: "Show artifact provenance (evidence + confidence + retrieval)"},
		"theory":   {Name: "theory", Description: "Theory CRUD"},
		"skill":    {Name: "skill", Description: "Skill CRUD"},

		// Tour (cognitive-interface RFC Wave 4) — onboarding walkthrough.
		"tour": {Name: "tour", Description: "Walk through cognitive verbs (--demo auto-runs each step; --step N jumps)"},

		// Identity inspector — `mpm info`, distinct from `mpm status` (live substrate)
		// and `mpm doctor` (trust signals). Per the post-RFC polish session.
		"info": {Name: "info", Description: "Show install identity (version, database, models, scheduler, skills, persona, counts)"},

		// Configuration wizard (Wed 2026-07-29 polish session).
		"config": {Name: "config", Description: "Configure AI provider (interactive wizard or scripted set|get|show|edit)"},

		// Skills — versioned procedure rows with frontmatter + body
		"save-skill":  {Name: "save-skill", Description: "Save skill from markdown file (--file, --name, --version, --force)", MinArgs: 0},
		"list-skills": {Name: "list-skills", Description: "List skills (scope: all|local|shared)", MinArgs: 0, MaxArgs: 1},
		"read-skill":  {Name: "read-skill", Description: "Read skill by name (or id) and optional version", MinArgs: 1, MaxArgs: 2},

		// Operations — state, scheduling, diagnostics, engine-room
		"mode":       {Name: "mode", Description: "Manage modes"},
		"wake":       {Name: "wake", Description: "Show wake context (--json, --strict)", MinArgs: 0},
		"gc":         {Name: "gc", Description: "Run decay sweep (--dry-run, --review, --purge)"},
		"blob":       {Name: "blob", Description: "Blob storage management (gc)"},
		"tasks":      {Name: "tasks", Description: "Manage scheduled tasks (upsert|list|delete)", MinArgs: 0},
		"lint":       {Name: "lint", Description: "Validate router frontmatter (YAML + regex compile)", MinArgs: 0},
		"backup":     {Name: "backup", Description: "Export database to SQL dump (optional path arg)"},
		"restore":    {Name: "restore", Description: "Restore soft-deleted memory", MinArgs: 1},
		"restore-db": {Name: "restore-db", Description: "Restore database from SQL dump", MinArgs: 1},
		"directives": {Name: "directives", Description: "Show behavioral directives"},
		"status":     {Name: "status", Description: "Show system status", MinArgs: 0},
		"persona":    {Name: "persona", Description: "Manage personas"},
		"ops":        {Name: "ops", Description: "Engine-room operations (maintenance, diagnostics)"},

		// Routing — context-aware helpers
		"hint":  {Name: "hint", Description: "Surface context-relevant artifacts", MinArgs: 1},
		"route": {Name: "route", Description: "Route prompt to mode/persona (Claude Code hook input)", MinArgs: 0, MaxArgs: -1},

		// Epistemology Engine — substrate contracts (stable for agent calls)
		"propose_theory":  {Name: "propose_theory", Description: "Propose hypothesis", MinArgs: 1},
		"resolve_theory":  {Name: "resolve_theory", Description: "Resolve theory", MinArgs: 2},
		"record_decision": {Name: "record_decision", Description: "Record decision (full substrate form: context, choice, rationale)", MinArgs: 1},
		"challenge":       {Name: "challenge", Description: "Flag memory as obsolete (atomic theory + patch; use 'restore' subcommand to undo)", MinArgs: 1, MaxArgs: 2},
		"theories":        {Name: "theories", Description: "List theories [pending|resolved|all]", MinArgs: 0},
		"decisions":       {Name: "decisions", Description: "List decisions", MinArgs: 0},
		"call":            {Name: "call", Description: "Universal tool boundary (JSON): mpm call <tool> [--payload <json>] [--payload-file <path>] | (stdin)", MinArgs: 1},
		"evidence":        {Name: "evidence", Description: "Manage evidence (add|list) — confidence foundation", MinArgs: 0},

		// Knowledge Base — entity-centric namespace (reads + writes)
		"kb":    {Name: "kb", Description: "Knowledge-base operations (memory|topic|lesson|reference)", MinArgs: 0},
		"debug": {Name: "debug", Description: "Low-level debugging tools", MinArgs: 0},

		// Capability namespace — executable primitives (seed, lifecycle)
		"capability": {Name: "capability", Description: "Manage capabilities (seed, lifecycle, governance)", MinArgs: 0},

		// Provenance — artifact creation metadata
		"provenance": {Name: "provenance", Description: "Show artifact provenance (mpm provenance help for subcommands)", MinArgs: 0},

		// Drills — behavioural drill execution + compatibility matrix
		"drills": {Name: "drills", Description: "Behavioural drill execution + compatibility matrix (list|show|run|report)", MinArgs: 0},
	}

	return r
}

// Execute routes and runs the command, returning an exit code.
func (r *CommandRouter) Execute(args []string) int {
	if len(args) == 0 {
		PrintHelp()
		return 0
	}

	// Parse global flags first
	// D5 (Stage 7): the caller (main.go) captures explicit help requests in
	// r.helpRequested BEFORE its own parseFlags pass rewrites -h/--help into
	// the literal token "help". Exact-token match on raw argv only — a JSON
	// payload or quoted content is never exactly "-h"/"--help".
	helpRequested := r.helpRequested
	args = r.parseFlags(args)

	if len(args) < 1 {
		PrintHelp()
		return 0
	}

	cmdName := args[0]
	if cmdName == "" {
		PrintHelp()
		return 0
	}

	// Intercept bare +/- feedback: +<id> or -<id>
	// Requires len > 2 to avoid colliding with single-dash flags like -v, -h
	if len(cmdName) > 1 {
		if cmdName[0] == '+' {
			return handleFeedback([]string{"feedback", cmdName[1:], "1"})
		}
		if cmdName[0] == '-' && cmdName[1] != '-' && len(cmdName) > 2 {
			return handleFeedback([]string{"feedback", cmdName[1:], "-1"})
		}
	}

	cmd := r.resolveCommand(cmdName)
	if cmd == nil {
		r.unknownCommand(cmdName)
		return 1
	}

	// Centralized help interception (D5 fix, 2026-08-25).
	//
	// parseFlags rewrites -h/--help into the literal argument "help", so
	// before this guard the token fell through as DATA: `mpm prune --help`
	// performed a real prune, `mpm show --help` looked up memory "help",
	// `mpm recall --help` searched for the word. A help request must never
	// mutate state nor fail.
	//
	// Two interception layers:
	//   1. helpRequested — an ORIGINAL -h/--help token anywhere in argv,
	//      captured before the rewrite above (Stage 7 fix). Position-1-only
	//      interception left `mpm rm <id> --help` deleting the memory,
	//      `mpm lesson shred <id> --help` hard-deleting the lesson, and
	//      `mpm challenge/snooze <id> --help` mutating — handlers ignore
	//      trailing tokens they don't understand, so the rewritten "help"
	//      silently became handler data.
	//   2. A literal "help" as the first post-command argument (the
	//      rewrite artifact) keeps its help meaning; a literal
	//      "help" elsewhere remains data (`mpm recall help` searches).
	//
	// REGRESSION FIX (RECOMMENDED 12): `mpm work item --help` was
	// intercepted here on cmdName="work" and routed to handleCommandHelp,
	// which printed the "work" section page rather than dispatching
	// through handleWork → handleWorkItem. When --help was the LAST
	// original token AND the command dispatches subcommands (so the
	// positional token at args[1] is a subcommand name rather than
	// data), the help is for the SUBCOMMAND. Skip interception and
	// let the handler dispatch. The Stage 7 guarantee is preserved
	// for commands without subcommand dispatch — `mpm rm <id> --help`
	// still hits the interception path because "rm" is not in
	// commandsWithSubcommandDispatch.
	if cmdName != "help" && helpRequested {
		if !isSubcommandHelp(args, cmdName) {
			return r.handleCommandHelp(cmdName, cmd)
		}
		// fall through — let the handler dispatch the subcommand help.
	}
	if len(args) > 1 && args[1] == "help" && cmdName != "help" {
		return r.handleCommandHelp(cmdName, cmd)
	}

	// Validate arguments
	if len(args)-1 < cmd.MinArgs {
		r.errorf("[!] Error: %s requires %d argument(s)\n", cmd.Name, cmd.MinArgs)
		return 1
	}

	if cmd.MaxArgs > 0 && len(args)-1 > cmd.MaxArgs {
		r.errorf("[!] Error: %s takes at most %d argument(s)\n", cmd.Name, cmd.MaxArgs)
		return 1
	}

	// Route to appropriate handler
	switch cmd.Name {
	case "version":
		return r.handleVersion()
	case "wake":
		return handleWake(args)
	case "gc":
		return handleGC(args)
	case "blob":
		return handleBlob(args)
	case "tasks":
		return handleTasksCommand(args[1:])
	case "backup":
		return handleBackup(args)
	case "restore":
		return handleRestore(args)
	case "restore-db":
		return handleRestoreDB(args)
	case "help":
		return r.handleHelp(args[1:])
	case "doctor":
		return handleDoctor(args[1:])
	case "recall":
		return handleRecall(args)
	case "ingest":
		return handleIngest(args)
	case "cascade":
		return handleCascade(args)
	case "migrate":
		return handleMigrate(args)
	case "work":
		return handleWork(args[1:])
	case "continue":
		return handleContinue(args[1:])
	case "stats":
		return handleStats(args)
	case "prune":
		return handlePrune(args)
	case "export":
		return handleExport(args)
	case "integration":
		return handleIntegration(args[1:])
	case "maintain":
		return handleMaintain(args)
	case "review":
		return handleReview(args)
	case "why":
		return handleWhy(args[1:])
	case "lint":
		// W-6 (debt burn-down, 2026-09-01): the top-level dispatch was
		// passing `args` (which still contains "lint" at index 0) into
		// handleLint, causing the handler's flag loop to see "lint" as
		// the first positional and reject it with "unknown flag 'lint'".
		// Strip the command name so handleLint sees only flags, matching
		// the convention used by handleWhy and the ops subcommand path.
		return handleLint(args[1:])
	case "switch":
		return r.handleSwitch()
	case "add":
		return handleAdd(args)
	case "remember":
		// D1 fix: pass FULL args (command name included). handleRemember
		// delegates to handleAdd, which strips args[0] itself; pre-stripping
		// here caused a double-strip that silently dropped the first word
		// of multi-word content and rejected single-word content.
		return handleRemember(args)
	case "learn":
		return handleLearn(args[1:])
	case "decide":
		return handleDecide(args[1:])
	case "theorize":
		return handleTheorize(args[1:])
	case "decision":
		return handleDecision(args[1:])
	case "theory":
		return handleTheory(args[1:])
	case "skill":
		return handleSkill(args[1:])
	case "tour":
		return handleTour(args[1:])
	case "info":
		return handleInfo(args[1:])
	case "config":
		return handleConfig(args[1:])
	case "ls":
		return handleLs(args)
	case "show":
		return handleShow(args)
	case "rm":
		return handleRm(args)
	case "promote":
		return handlePromote(args)
	case "patch-memory":
		return handlePatchMemory(args)
	case "reinforce":
		return handleReinforce(args)
	case "weaken":
		return handleWeaken(args)
	case "snooze":
		return handleSnooze(args)
	case "set-weight":
		return handleSetWeight(args)
	case "synthesize":
		return handleSynthesize(args)
	case "shred":
		return handleShred(args[1:])
	case "reference":
		return handleRef(args[1:])
	case "directives":
		return handlePrimeDirectives()
	case "status":
		return handleStatus(args[1:])
	case "memory":
		return handleMemory(args[1:])
	case "mode":
		return handleMode(args[1:])
	case "persona":
		return handlePersona(args[1:])
	case "topic":
		return handleTopic(args[1:])
	case "session":
		return handleSession(args[1:])
	case "lesson":
		return handleLesson(args[1:])
	case "hint":
		return handleHint(args[1:])
	case "route":
		return r.handleRoute(args[1:])
	case "propose_theory":
		return handleProposeTheory(args[1:])
	case "resolve_theory":
		return handleResolveTheory(args[1:])
	case "record_decision":
		return handleRecordDecision(args[1:])
	case "theories":
		return handleTheories(args[1:])
	case "decisions":
		return handleDecisions(args[1:])
	case "audit":
		return handleAudit(args[1:])
	case "challenge":
		sub := args[1]
		if sub == "restore" && len(args) >= 3 {
			return handleChallengeRestore(args[1:])
		}
		return handleChallenge(args[1:])
	case "ops":
		return handleOps(args)
	case "kb":
		return handleKB(args)
	case "debug":
		return handleDebug(args)
	case "capability":
		return handleCapability(args)
	case "provenance":
		if len(args) < 2 {
			// No subcommand — show brief usage.
			fmt.Println("Usage: mpm provenance <artifact_id>")
			fmt.Println("       mpm provenance inspect --invocation <id>")
			fmt.Println("       mpm provenance model-yield [--days N]")
			fmt.Println("       mpm provenance help")
			return 0
		}
		sub := args[1]
		subArgs := args[2:]
		switch sub {
		case "inspect":
			return handleProvenanceInspect(subArgs)
		case "model-yield":
			return handleProvenanceModelYield(subArgs)
		case "help":
			fmt.Println("Usage: mpm provenance <artifact_id>")
			fmt.Println("       mpm provenance inspect --invocation <id>")
			fmt.Println("       mpm provenance model-yield [--days N]")
			return 0
		default:
			// Bare artifact ID.
			return handleProvenance(args[1:])
		}
	case "drills":
		return handleDrills(args)
	case "call":
		return handleCall(args[1:])
	case "evidence":
		return handleEvidence(args[1:])
	case "save-skill":
		return handleSaveSkill(args[1:])
	case "list-skills":
		return handleListSkills(args[1:])
	case "read-skill":
		return handleReadSkill(args[1:])

	default:
		r.unknownCommand(cmdName)
		return 1
	}
}

// resolveCommand finds command by name or alias
func (r *CommandRouter) resolveCommand(name string) *Command {
	if cmd, ok := r.Commands[name]; ok {
		return cmd
	}
	// Check aliases
	for _, cmd := range r.Commands {
		for _, alias := range cmd.Aliases {
			if alias == name {
				return cmd
			}
		}
	}
	return nil
}

// parseFlags parses global flags, returns remaining args
func (r *CommandRouter) parseFlags(args []string) []string {
	result := make([]string, 0, len(args))
	for _, arg := range args {
		switch arg {
		case "-h", "--help":
			result = append(result, "help")
		case "-v", "--version":
			result = append(result, "version")
		case "-f", "--force":
			os.Setenv("MPM_FORCE", "1")
		case "-i", "--interactive":
			os.Setenv("MPM_INTERACTIVE", "1")
		default:
			result = append(result, arg)
		}
	}
	return result
}

// ============================================================================
// Command Handlers
// ============================================================================

func (r *CommandRouter) handleVersion() int {
	fmt.Printf("MPM mpm %s\n", buildVersion)
	return 0
}

// handleHelp routes help requests per the cognitive-interface RFC §4
// progressive-disclosure principle. Order:
//
//   1. No args → cognitive default (~22 commands across 5 sections).
//   2. --all → full operator-interface catalogue (all 56+ commands).
//   3. <known-section> → expanded section help (knowledge, runtime,
//                         maintenance, reflection, work, explain).
//   4. <known-command> → existing per-command help (mode, persona, etc.).
//   5. Anything else → "no help available" + cognitive default.
//
// Stage 3 keeps existing per-command help reachable so scripts that
// depended on `mpm help mode` etc. continue to work.
func (r *CommandRouter) handleHelp(args []string) int {
	if len(args) == 0 {
		printCognitiveHelp()
		return 0
	}

	// Pull out --all before matching against command names. Operators
	// can also use `mpm help <section> --all` if they want a flat dump
	// from a section context.
	all := false
	filtered := make([]string, 0, len(args))
	for _, a := range args {
		if a == "--all" {
			all = true
			continue
		}
		filtered = append(filtered, a)
	}

	// `mpm help --all` (no other args) → full catalogue.
	if all && len(filtered) == 0 {
		printHelpAll()
		return 0
	}

	// At this point we have at least one positional arg.
	helpCmd := filtered[0]

	// 3. Section-name help (progressive disclosure).
	if printSectionHelp(helpCmd) {
		return 0
	}

	// 4. Per-command help (existing dispatch).
	var helpFunc func() int
	switch helpCmd {
	case "mode":
		helpFunc = handleModeHelp
	case "persona":
		helpFunc = handlePersonaHelp
	case "topic":
		helpFunc = handleTopicHelp
	case "session":
		helpFunc = handleSessionHelp
	case "lesson":
		helpFunc = handleLessonHelp
	case "reference":
		helpFunc = printRefHelp
	case "memory":
		helpFunc = handleMemoryHelp
	case "gateway":
		helpFunc = printGatewayHelp
	case "challenge":
		fmt.Println("Usage: mpm challenge <id> <evidence>")
		fmt.Println("       mpm challenge restore <id>")
		fmt.Println("Challenges a memory as obsolete by proposing an atomic theory and patch.")
		return 0
	case "evidence":
		// RECOMMENDED 7: surface the canonical evidence-type
		// documentation under `mpm help evidence` so the vocabulary
		// is discoverable without grepping source.
		fmt.Println(mpminternal.EvidenceTypeHelp())
		return 0
	case "ops":
		printOpsHelp()
		return 0
	case "work":
		printWorkHelp()
		return 0
	case "remember":
		// W-002: cognitive-verb aliases route through `mpm help <verb>`
		// directly. Reuses the existing per-cmd help functions so
		// there's no second source of truth.
		printRememberHelp()
		return 0
	case "learn":
		printLearnHelp()
		return 0
	case "decide":
		printDecideHelp()
		return 0
	case "theorize":
		printTheorizeHelp()
		return 0
	case "decision":
		printDecisionHelp()
		return 0
	case "theory":
		printTheoryHelp()
		return 0
	case "record_decision":
		printDecideHelp()
		return 0
	case "propose_theory":
		printTheorizeHelp()
		return 0
	case "resolve_theory":
		printResolveTheoryHelp()
		return 0
	default:
		// W-007: tool-name introspection. Before falling through to
		// "no help available", check whether the requested name is a
		// registered tool (e.g. `mpm help mpm_memory`). Returns the
		// tool description + valid action list derived from the same
		// tools.Registry the dispatch uses — no duplicate registry.
		if handled := printToolHelp(helpCmd); handled {
			return 0
		}
		// 5. Unknown: stay explicit rather than dumping the cognitive
		// default. Operator asked for a specific help page; tell them
		// if we don't have one. They can then run `mpm help` for the
		// cognitive default.
		r.errorf("[!] Error: no help available for '%s'\n", helpCmd)
		fmt.Println("Try one of: mpm help, mpm help --all, mpm help knowledge, mpm help work")
		return 1
	}

	if helpFunc != nil {
		helpFunc()
	}
	return 0
}

func (r *CommandRouter) handleSwitch() int {
	return handleSwitch([]string{})
}

// handleCommandHelp serves `mpm <command> --help` (see the interception in
// Execute). It prints a dedicated help page when one exists — the same page
// `mpm help <command>` would print — and falls back to registry metadata
// (usage line + description) otherwise. Always exits 0: asking for help is
// never an error, and never a mutation.
func (r *CommandRouter) handleCommandHelp(name string, cmd *Command) int {
	// 1. Dedicated per-command help pages (same dispatch as handleHelp).
	// Checked FIRST so `mpm <cmd> --help` routes to the command's own
	// help function rather than to section help. Previously `mpm work
	// --help` printed the "work" section page (cognitive-verb summary)
	// because printSectionHelp("work") matched before the dedicated
	// case "work": printWorkHelp() branch could run. The two paths are
	// conceptually distinct: section help is for `mpm help <section>`,
	// per-command help is for `mpm <cmd> --help`.
	//
	// `mpm help work` still prints section help because handleHelp
	// (which `mpm help` dispatches to) calls printSectionHelp directly,
	// not handleCommandHelp.
	var helpFunc func() int
	switch name {
	case "mode":
		helpFunc = handleModeHelp
	case "persona":
		helpFunc = handlePersonaHelp
	case "topic":
		helpFunc = handleTopicHelp
	case "session":
		helpFunc = handleSessionHelp
	case "lesson":
		helpFunc = handleLessonHelp
	case "reference":
		helpFunc = printRefHelp
	case "memory":
		helpFunc = handleMemoryHelp
	case "gateway":
		helpFunc = printGatewayHelp
	case "challenge":
		fmt.Println("Usage: mpm challenge <id> <evidence>")
		fmt.Println("       mpm challenge restore <id>")
		fmt.Println("Challenges a memory as obsolete by proposing an atomic theory and patch.")
		return 0
	case "evidence":
		// RECOMMENDED 7: surface the canonical evidence-type
		// documentation under `mpm help evidence` so the vocabulary
		// is discoverable without grepping source.
		fmt.Println(mpminternal.EvidenceTypeHelp())
		return 0
	case "ops":
		printOpsHelp()
		return 0
	case "work":
		printWorkHelp()
		return 0
	case "remember":
		printRememberHelp()
		return 0
	case "learn":
		printLearnHelp()
		return 0
	case "decide":
		printDecideHelp()
		return 0
	case "theorize":
		printTheorizeHelp()
		return 0
	case "decision":
		printDecisionHelp()
		return 0
	case "theory":
		printTheoryHelp()
		return 0
	case "record_decision":
		printDecideHelp()
		return 0
	case "propose_theory":
		printTheorizeHelp()
		return 0
	case "resolve_theory":
		printResolveTheoryHelp()
		return 0
	}
	if helpFunc != nil {
		helpFunc()
		return 0
	}

	// 2. Section help (knowledge, runtime, maintenance, reflection,
	// explain) — fallback for commands without a dedicated help page.
	if printSectionHelp(name) {
		return 0
	}

	// 3. Generic fallback from registry metadata.
	fmt.Printf("Usage: mpm %s\n", name)
	fmt.Printf("  %s\n", cmd.Description)
	fmt.Println("\nRun 'mpm help' for the full interface or 'mpm help --all' for every command.")
	return 0
}

// commandsWithSubcommandDispatch lists top-level commands whose first
// positional argument is a subcommand name (rather than data). Used by
// the help-interception guard in Execute to distinguish subcommand
// help (route to handler) from data-positional help (intercept for
// Stage 7 mutation safety).
//
// Kept inline (not in the registry) because the dispatch topology is
// handler-level concern: it reflects what each handler's switch does
// with args[0], not what the registry declares. Add a command here
// when its handler treats args[0] as a subcommand name.
var commandsWithSubcommandDispatch = map[string]bool{
	"work":        true, // status|show|clear|promote|item
	"session":     true, // add|search|show|shred|list
	"lesson":      true, // add|show|list|search|shred
	"ops":         true, // doctor|gc|synthesize|...
	"call":        true, // <tool> --payload
	"kb":          true, // memory|lesson|skill|topic|...
	"topic":       true, // add|list|show
	"reference":   true, // add|list|show|search|shred
	"memory":      true, // add|list|show|...
	"mode":        true, // list|show|set|active
	"persona":     true, // list|show|set|active
	"integration": true, // export-mcp
	"self-heal":   true, // (ops subcommand pattern)
	"why":         true, // (uses subcommand-style args)
}

// isSubcommandHelp reports whether the given args (post-parseFlags, with
// cmdName still at index 0) indicate that --help was meant for a
// SUBCOMMAND rather than for the top-level command. The signal is:
// parseFlags rewrites -h/--help to the literal token "help"; if that
// rewrite appears at the LAST position AND the command dispatches
// subcommands (so args[1] is a subcommand name rather than a data
// positional), the help belongs to the subcommand.
func isSubcommandHelp(args []string, cmdName string) bool {
	if !commandsWithSubcommandDispatch[cmdName] {
		return false
	}
	if len(args) < 2 {
		return false
	}
	return args[len(args)-1] == "help"
}

// ============================================================================
// Ops Subcommand — Maintenance, diagnostics, and engine-room tools
// ============================================================================

// handleOps routes to the appropriate sub-command under the ops parent.
// All engine-room commands live here. Root-level aliases are kept for
// backwards compatibility.
func handleOps(args []string) int {
	if len(args) < 2 {
		printOpsHelp()
		return 0
	}

	subCmd := args[1]
	subArgs := args[2:]

	switch subCmd {
	// — Diagnostics & Maintenance —
	case "doctor":
		runDoctorCommand(subArgs)
		return 0
	case "maintain":
		return handleMaintain(append([]string{"maintain"}, subArgs...))
	case "lint":
		return handleLint(subArgs)
	case "synthesize":
		return handleSynthesize(append([]string{"synthesize"}, subArgs...))
	case "shared":
		return handleOpsShared(subArgs)
	case "logs":
		return handleOpsLogs(subArgs)
	case "gc":
		return handleGC(append([]string{"gc"}, subArgs...))
	case "backfill-embeddings":
		return handleBackfillEmbeddings(subArgs)
	case "backfill-snapshots":
		return handleBackfillSnapshots(subArgs)
	case "migrate-embeddings":
		return handleMigrateEmbeddings(subArgs)
	case "rebalance":
		return handleOpsRebalance(subArgs)
	case "resolve-contradictions":
		return handleOpsResolveContradictions(subArgs)
	case "broadcast":
		return handleOpsBroadcast(subArgs)
	case "active-sessions":
		return handleOpsActiveSessions(subArgs)

	// — Review & Stats —
	case "review":
		return handleReview(append([]string{"review"}, subArgs...))
	case "stats":
		return handleStats(append([]string{"stats"}, subArgs...))
	case "prune":
		return handlePrune(append([]string{"prune"}, subArgs...))
	case "export":
		return handleExport(append([]string{"export"}, subArgs...))
	case "integration":
		return handleIntegration(subArgs)

	// — Backup & Restore & Ingest —
	case "ingest":
		return handleIngest(append([]string{"ingest"}, subArgs...))
	case "cascade":
		return handleCascade(append([]string{"cascade"}, subArgs...))
	case "migrate":
		return handleMigrate(append([]string{"migrate"}, subArgs...))

	// — Interactive & Identity —
	case "switch":
		return handleSwitch(subArgs)
	case "directives":
		return handlePrimeDirectives()
	case "mode":
		return handleMode(subArgs)
	case "persona":
		return handlePersona(subArgs)

	// — Memory, Topic, Lesson, Session —
	case "memory":
		return handleMemory(subArgs)
	case "topic":
		return handleTopic(subArgs)
	case "lesson":
		return handleLesson(subArgs)
	case "session":
		return handleSession(subArgs)
	case "reference":
		return handleRef(subArgs)
	case "wake":
		return handleWake(subArgs)

	// — Gateway —
	case "gateway":
		handleGatewayCommand(subArgs)
		return 0

		// — Status Dashboard —
	case "stance":
		return handleStance(subArgs)

	case "promote":
		return handleOpsPromote()

	case "confidence":
		return handleOpsConfidence(subArgs)

	case "changelog":
		return handleOpsChangelogRoute(subArgs)

	case "milestones":
		return handleOpsMilestones(subArgs)

	case "init":
		return handleOpsInit(subArgs)

	case "self-heal":
		return handleSelfHeal(subArgs)

	case "status":
		return handleStatus(subArgs)

		// — Help —
	case "help":
		printOpsHelp()
		return 0

	default:
		printOpsHelp()
		return 0
	}
}

// opsSubcommandDescs is the canonical list of all ops subcommands and their descriptions.
var opsSubcommandDescs = []struct {
	name string
	desc string
}{
	{"doctor [--deep-scan|--explain]", "Run diagnostics (--deep-scan for FTS/integrity audit, --explain for FTS5 query plan)"},
	{"maintain", "Self-maintenance: decay, consolidate, prune"},
	{"synthesize [--dry-run]", "LLM synthesis on all memories"},
	{"gc [--dry-run/--review/--purge/--shred-negative]", "Memory decay sweep"},
	{"backfill-embeddings [--batch-size/--collection/--dry-run]", "Backfill embeddings for existing memories"},
	{"backfill-snapshots [--batch-size/--dry-run]", "Derive _epistemic_snapshot blocks for pre-resolver memories"},
	{"review", "Spaced reinforcement review"},
	{"stats", "Memory statistics"},
	{"prune", "Prune expired memories"},
	{"export", "Export memories to JSON"},
	{"backup [path]", "Database backup (.sql dump)"},
	{"restore-db <path>", "Restore database from .sql dump"},
	{"ingest", "Import memories from external SQLite"},
	{"migrate", "Import memories from markdown/JSON files"},
	{"switch", "Interactive persona/mode switcher"},
	{"directives", "Show behavioral directives"},
	{"mode", "Mode operations"},
	{"persona", "Persona operations"},
	{"topic", "Topic operations"},
	{"lesson", "Lesson operations"},
	{"session", "Session operations"},
	{"memory", "Memory operations"},
	{"reference", "Reference library"},
	{"wake", "Show last session context"},
	{"gateway", "Gateway control"},
	{"status", "System status dashboard"},
	{"stance assume <mode> <persona> <rationale>", "XITL: hot-swap existing persona when auto active"},
	{"stance synthesize <name> [flags]", "XITL: generate JIT persona for novel edge cases"},
	{"promote", "XITL: promote ephemeral persona to permanent disk file"},
	{"confidence show|recompute", "Confidence/evidence engine: snapshot or trigger recompute"},
	{"changelog build [--since/--until/--version/--legacy/--dry-run]", "Generate CHANGELOG.md + changelog.json from git log"},
	{"milestones [--flavor/--days/--limit]", "List recent narrative milestones (memories tagged type:milestone-*)"},
	{"init directives", "Seed the Baseline Cognitive Bootstrap (idempotent)"},
	{"init skills", "Seed the Baseline Skill Library (idempotent)"},
	{"init tasks", "Seed the Baseline Cognitive Bootstrap for scheduled tasks (idempotent)"},
	{"self-heal [--dry-run/--force/--quiet]", "Autonomous integrity repair — auto-fix known drift, escalate unknown via theory"},
	{"resolve-contradictions [--dry-run/--apply/--json/--limit=N]", "Resolve the shared contradiction queue by provenance scoring"},
	{"broadcast <memory_id> [--kind/--rationale/--to/--dry-run/--json]", "Arc 2 fan-out: push an epistemic event to every active session"},
	{"active-sessions [--json]", "List sessions active within the heartbeat window"},
	{"help", "Show this help"},
}

// printOpsHelp displays the ops subcommand help text.
func printOpsHelp() {
	fmt.Println()
	fmt.Println("mpm ops — Engine Room: maintenance, diagnostics, and power tools")
	fmt.Println()
	fmt.Println("Usage: mpm ops <subcommand> [arguments]")
	fmt.Println()
	fmt.Println("Subcommands:")
	for _, sc := range opsSubcommandDescs {
		fmt.Printf("  %-22s %s\n", sc.name, sc.desc)
	}
	fmt.Println()
	fmt.Println("All ops subcommands also work at the root level for")
	fmt.Println("backwards compatibility (e.g. `mpm doctor` = `mpm ops doctor`).")
	fmt.Println()
}

// ============================================================================
// KB Namespace — Knowledge Base: memory, topic, lesson, session, reference
// ============================================================================

// handleKB routes to the appropriate kb subcommand.
func handleKB(args []string) int {
	if len(args) < 2 {
		printKBHelp()
		return 0
	}

	subCmd := args[1]
	subArgs := args[2:]

	switch subCmd {
	// — Entity subcommands —
	case "memory":
		return handleKBMemory(subArgs)
	case "topic":
		return handleKBTopic(subArgs)
	case "lesson":
		return handleKBLesson(subArgs)
	case "session":
		return handleKBSession(subArgs)
	case "reference":
		return handleKBReference(subArgs)

	// — Epistemology engine —
	case "theories":
		return handleTheories(subArgs)
	case "decisions":
		return handleDecisions(subArgs)
	case "propose_theory":
		return handleProposeTheory(subArgs)
	case "resolve_theory":
		return handleResolveTheory(subArgs)
	case "record_decision":
		return handleRecordDecision(subArgs)
	case "hint":
		return handleHint(subArgs)

	// — Help —
	case "help":
		printKBHelp()
		return 0

	default:
		printKBHelp()
		return 0
	}
}

// handleKBMemory routes memory subcommands. Thin wrapper around handleMemory.
func handleKBMemory(args []string) int {
	return handleMemory(args)
}

func handleKBTopic(args []string) int {
	return handleTopic(args)
}

func handleKBLesson(args []string) int {
	return handleLesson(args)
}

func handleKBSession(args []string) int {
	return handleSession(args)
}

func handleKBReference(args []string) int {
	return handleRef(args)
}

// kbSubcommandDescs is the canonical list of all kb subcommands.
var kbSubcommandDescs = []struct {
	name string
	desc string
}{
	{"memory list|show|search|shred", "Memory operations"},
	{"memory add|reinforce|weaken|snooze|set-weight|promote", "Memory mutations"},
	{"topic list|show|search|shred|add", "Topic operations"},
	{"lesson list|show|search|shred|add", "Lesson operations"},
	{"session list|get|search|shred|stats", "Session operations"},
	{"reference list|show|search|shred|add", "Reference library"},
	{"theories [pending|resolved|all]", "List theories"},
	{"decisions", "Show decision ledger"},
	{"propose_theory <theoryId>", "Record a hypothesis with validation criteria"},
	{"resolve_theory <theoryId> <status>", "Mark a theory as resolved"},
	{"record_decision <decisionId>", "Record a decision with context/choice/rationale"},
	{"hint <topic>", "Check conversation for relevant decisions/theories"},
	{"help", "Show this help"},
}

func printKBHelp() {
	fmt.Println()
	fmt.Println("mpm kb — Knowledge Base: entity-centric memory interface")
	fmt.Println()
	fmt.Println("Usage: mpm kb <entity> <subcommand> [arguments]")
	fmt.Println()
	fmt.Println("Entities and subcommands:")
	for _, sc := range kbSubcommandDescs {
		fmt.Printf("  %-22s %s\n", sc.name, sc.desc)
	}
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  mpm kb memory list")
	fmt.Println("  mpm kb memory search <query>")
	fmt.Println("  mpm kb memory shred <id>")
	fmt.Println("  mpm kb theories pending")
	fmt.Println()
}

// ============================================================================
// Debug Namespace — Low-level inspection for human troubleshooting
// ============================================================================

// handleDebug routes to the appropriate debug subcommand.
func handleDebug(args []string) int {
	if len(args) < 2 {
		printDebugHelp()
		return 0
	}

	subCmd := args[1]
	subArgs := args[2:]

	switch subCmd {
	// — Version history —
	case "history":
		return handleHistory(append([]string{"history"}, subArgs...))
	case "diff":
		return handleDiff(append([]string{"diff"}, subArgs...))
	case "diff-lines":
		return handleDiffLines(append([]string{"diff-lines"}, subArgs...))

	// — Memory patching —
	case "patch-memory":
		return handlePatchMemory(append([]string{"patch-memory"}, subArgs...))
	case "shred":
		return handleShredMem(append([]string{"shred"}, subArgs...))
	case "show":
		return handleShow(append([]string{"show"}, subArgs...))

	// — Inspection —
	case "gc":
		return handleGC(append([]string{"gc"}, subArgs...))

	// — Help —
	case "help":
		printDebugHelp()
		return 0

	default:
		printDebugHelp()
		return 0
	}
}

// debugSubcommandDescs is the canonical list of all debug subcommands.
var debugSubcommandDescs = []struct {
	name string
	desc string
}{
	{"history <memoryId>", "Show version history for a memory"},
	{"diff <memoryId> <v1> <v2>", "Unified diff between two versions"},
	{"diff-lines <text1> <text2>", "Compute unified diff of two text blocks"},
	{"patch-memory <id> <json>", "Patch metadata JSON in-place"},
	{"shred <id>", "Secure delete memory"},
	{"show <id>", "Show memory details"},
	{"gc [--dry-run]", "Memory decay sweep (dry-run for inspection)"},
	{"help", "Show this help"},
}

func printDebugHelp() {
	fmt.Println()
	fmt.Println("mpm debug — Low-level inspection tools for human troubleshooting")
	fmt.Println()
	fmt.Println("Usage: mpm debug <subcommand> [arguments]")
	fmt.Println()
	fmt.Println("Subcommands:")
	for _, sc := range debugSubcommandDescs {
		fmt.Printf("  %-22s %s\n", sc.name, sc.desc)
	}
	fmt.Println()
}

// ============================================================================
// Blob Namespace — Blob storage: gc
// ============================================================================

// handleBlob routes to the appropriate blob subcommand.
func handleBlob(args []string) int {
	if len(args) < 2 {
		printBlobHelp()
		return 0
	}

	subCmd := args[1]
	subArgs := args[2:]

	switch subCmd {
	case "gc":
		return handleBlobGC(subArgs)
	case "help":
		printBlobHelp()
		return 0
	default:
		printBlobHelp()
		return 1
	}
}

// blobSubcommandDescs is the canonical list of blob subcommands.
var blobSubcommandDescs = []struct {
	name string
	desc string
}{
	{"gc [--dry-run|-n]", "Garbage-collect expired and orphaned blobs"},
	{"help", "Show this help"},
}

func printBlobHelp() {
	fmt.Println()
	fmt.Println("mpm blob — Blob storage management")
	fmt.Println()
	fmt.Println("Usage: mpm blob <subcommand> [arguments]")
	fmt.Println()
	fmt.Println("Subcommands:")
	for _, sc := range blobSubcommandDescs {
		fmt.Printf("  %-22s %s\n", sc.name, sc.desc)
	}
	fmt.Println()
}

// ============================================================================
// Capability Namespace — Executable primitives (seed, lifecycle, governance)
// ============================================================================
//
// Capabilities are stateful, executable artifacts with a lifecycle
// (draft → linted → validated → probation → active → degraded →
// fractured). This namespace surfaces the operator-facing commands
// for bringing the Tier 1 read-only primitive set online and
// governing the lifecycle. Future subcommands (e.g. `invoke`,
// `fracture`, `grant-operator`) will be added here.
//
// Note: `mpm config capability` is a separate namespace used for
// config binding (which capabilities are bound to which components).
// This namespace is for capability *operations*: bringing a bundle
// into the database, stamping governance metadata, etc.

// handleCapability routes to the appropriate capability subcommand.
// Pattern mirrors handleKB / handleDebug.
func handleCapability(args []string) int {
	if len(args) < 2 {
		printCapabilityHelp()
		return 0
	}

	subCmd := args[1]
	subArgs := args[2:]

	switch subCmd {
	// — Bundle installation —
	case "seed":
		return handleCapabilitySeed(subArgs)

	// — Operator approval (CS-3) —
	case "grant-operator":
		return handleCapabilityGrantOperator(subArgs)

	// — Help —
	case "help":
		printCapabilityHelp()
		return 0

	default:
		printCapabilityHelp()
		return 0
	}
}

// capabilitySubcommandDescs is the canonical list of capability
// subcommands and their descriptions. Drives printCapabilityHelp.
var capabilitySubcommandDescs = []struct {
	name string
	desc string
}{
	{"seed [--sidecar <path>]", "Install / refresh the Tier 1 capability bundle (idempotent)"},
	{"grant-operator <id>", "Stamp operator_approved_at so the executor's operator-domain gate admits it"},
	{"help", "Show this help"},
}

func printCapabilityHelp() {
	fmt.Println()
	fmt.Println("mpm capability — Executable primitives: seed, lifecycle, governance")
	fmt.Println()
	fmt.Println("Usage: mpm capability <subcommand> [arguments]")
	fmt.Println()
	fmt.Println("Subcommands:")
	for _, sc := range capabilitySubcommandDescs {
		fmt.Printf("  %-22s %s\n", sc.name, sc.desc)
	}
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  mpm capability seed")
	fmt.Println("  mpm capability seed --sidecar /etc/mpm/bundled_capabilities.json")
	fmt.Println()
}

// ============================================================================
// Output Helpers
// ============================================================================

// PrintHelp shows the lipgloss-styled help menu
func PrintHelp() {
	printHelp()
}

func (r *CommandRouter) unknownCommand(name string) {
	r.errorf("[!] Error: unknown command '%s'\n", name)
	fmt.Printf("    Run 'mpm help' for available commands.\n")
}

func (r *CommandRouter) errorf(format string, args ...interface{}) {
	usererror.Error(format, args...)
}

// handleRoute reads prompt from positional arg or stdin, evaluates against
// the workspace's mode+persona files, and prints a <system-reminder> block
// to stdout. Designed for the Claude Code UserPromptSubmit hook — never
// blocks the user on errors (any failure → exit 0, no output).
//
// Usage:
//
//	mpm route "review this code"        # positional arg
//	echo "review this" | mpm route      # stdin literal
//	mpm route --apply                   # persist the route to active.json
//	mpm route < hook-stdin.json         # stdin JSON (Claude Code format)
//
// With --apply, the selected persona (when non-empty) and selected modes
// (when non-empty) are merged into active.json so the cross-session read
// at session start reflects the live routing signal, not a stale bag.
// Pre-fix active_persona was stuck at "" for over a month (2026-07-30 audit).
// REPLACEMENT for handleRoute in cmd/mpm/router.go
// Original lines ~911-944 (verify before applying). Drop in verbatim.
//
// Three-state gate replaces the always-route flow:
//   - blank (active.json has neither persona nor modes) → emit nothing.
//   - auto (persona or modes is the literal "auto") → run router, optionally persist.
//   - manual (concrete values) → render from those values, skip the router.
//
// This makes `mpm route` the full selector: it always returns concrete
// persona/modes (or nothing), never the "auto" sentinel. Frameworks that
// want auto-route set the sentinel in active.json; frameworks that want
// manual selection just write the values; frameworks that want no
// selection at all leave active.json blank.
func (r *CommandRouter) handleRoute(args []string) int {
	apply, cleanedArgs := stripApplyFlag(args)
	prompt := extractRoutePrompt(cleanedArgs, os.Stdin)
	skip, _ := shouldSkipRoute(prompt, os.Getenv)
	if skip {
		return 0
	}

	workspace := resolveRouteWorkspace()

	// Three-state gate.
	active, _ := mpminternal.LoadActiveJSON()
	switch {
	case isBlankActive(active):
		// Blank = nothing active. Emit nothing — no router call, no
		// persistence, no <system-reminder>. Hook consumers see no output.
		return 0

	case mpminternal.CheckAutoActive().Active:
		// Auto sentinel — the router picks mode/persona per turn.
		// --apply: persist the route result to active.json before rendering,
		// so cross-session reads see the live signal even when render fails
		// (e.g. mode file missing — renderRoute refuses to emit a partial
		// <system-reminder>).
		if apply {
			if router, err := mpminternal.NewRouter(workspace); err == nil {
				applyRouteToActive(router.Evaluate(prompt))
			} else if isatty(os.Stderr) {
				usererror.Warn("route --apply: %v", err)
			}
		}
		rendered, err := renderRoute(workspace, prompt)
		if err != nil {
			if isatty(os.Stdout) {
				usererror.Error("%v", err)
			}
			return 0
		}
		if rendered != "" {
			fmt.Println(rendered)
		}

	default:
		// Manual concrete values — render with those, skip the router.
		// The user has chosen specific persona/modes; respect them.
		rendered, err := renderManualRoute(workspace, active)
		if err != nil {
			if isatty(os.Stdout) {
				usererror.Error("%v", err)
			}
			return 0
		}
		if rendered != "" {
			fmt.Println(rendered)
		}
	}
	return 0
}

// isBlankActive returns true when active.json has no persona and no modes.
// Distinct from isAutoActive: blank means "user hasn't chosen anything",
// auto means "user explicitly opted into auto-route".
func isBlankActive(active *mpminternal.ActiveState) bool {
	if active == nil {
		return true
	}
	return active.Persona == "" && len(active.Modes) == 0
}

// isatty returns true if f is a terminal. Used to gate stderr noise.
func isatty(f *os.File) bool {
	fi, err := f.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

// handleOpsInit dispatches `mpm ops init <subcommand>`. Currently
// supports `init directives` (Baseline Cognitive Bootstrap),
// `init skills` (Baseline Skill Library), and `init tasks` (Baseline
// Cognitive Bootstrap for scheduled tasks). Other init subcommands
// (e.g. `init config`) can be added here.
func handleOpsInit(args []string) int {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "init requires a subcommand. Try: init directives, init skills, init tasks")
		return 1
	}
	sub := args[0]
	switch sub {
	case "directives":
		return handleOpsInitDirectives(args[1:])
	case "skills":
		return handleOpsInitSkills(args[1:])
	case "tasks":
		return handleOpsInitTasks(args[1:])
	default:
		return usererror.Error("unknown init subcommand: %q (want: directives, skills, tasks)", sub)
	}
}
