// template_drift_test.go — regression guard for the retired `mpm_session`
// tool name.
//
// `mpm_session` was split into `mpm_handoff` (cross-session: write/read/
// list/shred) and `mpm_scratchpad` (intra-session: flush/read/discard/
// promote) in the runtime registry, but several operational surfaces
// (plugin MCP registrations, instruction templates installed into the
// user's working files, plugin READMEs, INSTALL.md, verify.py, the
// top-level README) still referenced the retired name and caused live
// agents to attempt `mpm_session` calls that the runtime correctly
// rejects. This test scans the current operational surface and fails
// loudly if any non-whitelisted file re-acquires the retired name.
//
// Whitelisted files preserve legitimate references:
//
//   - cmd/mpm/call.go and cmd/mpm/f1_call_bridge_regression_test.go:
//     the runtime safety-net alias that maps old mpm_session action
//     names onto mpm_handoff/mpm_scratchpad.
//   - internal/core/handoff.go, internal/core/tools/handlers.go,
//     internal/core/tools/f1_f4_f5_machine_interface_regression_test.go:
//     code / test comments that name the legacy tool for traceability.
//   - changelog.md, docs/archive/**, agent_installation/*/VALIDATION-2026-08-19.md,
//     agent_installation/mpm-hermes/SKILL.md: historical record.
package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// retdName is the literal string the test scans for. Kept as a
// constant so a future rename of the retired tool would only require
// updating this single line.
const retdName = "mpm_session"

// whitelist path prefixes (relative to the repo root) that may
// reference the retired name without failing the drift guard.
var whitelistPrefixes = []string{
	// Runtime safety net — must keep the legacy name in its docstring.
	"cmd/mpm/call.go",
	"cmd/mpm/f1_call_bridge_regression_test.go",

	// Code / test comments that name the legacy tool for traceability.
	"internal/core/handoff.go",
	"internal/core/tools/handlers.go",
	"internal/core/tools/f1_f4_f5_machine_interface_regression_test.go",

	// Historical record — changelog, archive, validation logs.
	"changelog.md",
	"docs/archive/",
	"agent_installation/mpm-claude-code/VALIDATION-2026-08-19.md",
	"agent_installation/mpm-opencode/VALIDATION-2026-08-19.md",
	"agent_installation/mpm-memory-openclaw/VALIDATION-2026-08-19.md",
	"agent_installation/mpm-hermes/SKILL.md",

	// This test itself references the retired name to explain what it
	// is guarding against.
	"cmd/mpm/template_drift_test.go",
}

// driftScanPaths is the set of files this test scans. Listed
// explicitly rather than walking the whole repo so a stray reference
// in an unrelated file (a personal note, a vendored dep) does not
// false-positive — and so adding a new operational surface requires
// an explicit decision to extend this list.
var driftScanPaths = []string{
	// Plugin MCP tool registrations (the highest-risk drift source —
	// not regenerated by any installer; hand-edited only).
	"agent_installation/mpm-opencode/src/index.ts",
	"agent_installation/mpm-pi/index.ts",

	// Instruction templates installed into the user's working files.
	"agent_installation/mpm-claude-code/templates/CLAUDE.md.snippet",
	"agent_installation/mpm-hermes/templates/hermes.md.snippet",
	"agent_installation/mpm-opencode/templates/AGENTS.md.snippet",
	"agent_installation/mpm-pi/templates/AGENTS.md.snippet",

	// User-visible operational documentation.
	"agent_installation/INSTALL.md",
	"agent_installation/mpm-claude-code/README.md",
	"agent_installation/mpm-opencode/README.md",
	"agent_installation/mpm-pi/README.md",

	// Claude Code integration verify script — must drive the live
	// contract, not the legacy alias.
	"agent_installation/mpm-claude-code/verify.py",

	// Top-level README. The auto-generated block at the
	// <!-- tools:begin/end --> sentinels has no fenced marker the
	// test can target — scan the whole file.
	"README.md",
}

// isWhitelisted reports whether the given repo-relative path is
// allowed to reference retdName. Whitelist is matched as a full path
// or as a path-prefix (for directories like docs/archive/).
func isWhitelisted(relPath string) bool {
	for _, w := range whitelistPrefixes {
		if relPath == w {
			return true
		}
		if strings.HasSuffix(w, "/") && strings.HasPrefix(relPath, w) {
			return true
		}
	}
	return false
}

// repoRootFromTest resolves the repo root by walking up from this
// test's source file until it finds go.mod. Hardcoding the path
// would break across checkouts.
func repoRootFromTest(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("could not locate repo root from %s", dir)
	return ""
}

// TestNoRetiredMpmSessionReferences is the drift guard. It scans the
// operational surface listed in driftScanPaths and fails if any
// non-whitelisted file contains the literal retdName string. The
// whitelist allows the runtime safety net and legitimate historical
// references; everything else must use mpm_handoff / mpm_scratchpad.
func TestNoRetiredMpmSessionReferences(t *testing.T) {
	root := repoRootFromTest(t)
	var offenders []string
	for _, rel := range driftScanPaths {
		abs := filepath.Join(root, rel)
		data, err := os.ReadFile(abs)
		if err != nil {
			t.Errorf("scan target missing or unreadable: %s (%v)", rel, err)
			offenders = append(offenders, rel+" (read error)")
			continue
		}
		if isWhitelisted(rel) {
			continue
		}
		// Match whole-word occurrences only — `mpm_session_id` (a
		// hypothetical env-var-derived field name) must not fail.
		if lineNo, snippet, hit := findOccurrence(string(data), retdName); hit {
			offenders = append(offenders,
				rel+":"+lineNoString(lineNo)+": "+snippet)
		}
	}
	if len(offenders) > 0 {
		t.Fatalf("drift guard: %d operational surface file(s) still reference the retired tool %q:\n  %s\n\n"+
			"Fix the source/template (not just one installed copy) so future installer runs regenerate clean. "+
			"If the reference is intentional, add the path to whitelistPrefixes with a comment explaining why.",
			len(offenders), retdName, strings.Join(offenders, "\n  "))
	}
}

// findOccurrence reports the first 1-based line number containing
// needle and a trimmed snippet. Returns hit=false if not found.
func findOccurrence(haystack, needle string) (int, string, bool) {
	for i, line := range strings.Split(haystack, "\n") {
		if strings.Contains(line, needle) {
			snippet := strings.TrimSpace(line)
			if len(snippet) > 160 {
				snippet = snippet[:160] + "…"
			}
			return i + 1, snippet, true
		}
	}
	return 0, "", false
}

// lineNoString is a tiny local helper to keep this file stdlib-only without
// pulling strconv just for line numbers.
func lineNoString(n int) string {
	if n == 0 {
		return "0"
	}
	var b [20]byte
	pos := len(b)
	neg := n < 0
	if neg {
		n = -n
	}
	for n > 0 {
		pos--
		b[pos] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		pos--
		b[pos] = '-'
	}
	return string(b[pos:])
}