// template_drift_test.go — regression guard for the retired `mpm_session`
// tool name.
//
// `mpm_session` was split into `mpm_handoff` (cross-session: write/read/
// list/shred) and `mpm_scratchpad` (intra-session: flush/read/discard/
// promote) in the runtime registry, but several operational surfaces
// (plugin MCP registrations, instruction templates installed into the
// user's working files, plugin READMEs, INSTALL.md, verify.py, the
// top-level README) still referenced the retired name and caused live
// agents to attempt `mpm_session` calls that the runtime correctly
// rejects. This test scans the current operational surface and fails
// loudly if any non-whitelisted file re-acquires the retired name.
//
// Whitelisted files preserve legitimate references:
//
//   - cmd/mpm/call.go and cmd/mpm/f1_call_bridge_regression_test.go:
//     the runtime safety-net alias that maps old mpm_session action
//     names onto mpm_handoff/mpm_scratchpad.
//   - internal/core/handoff.go, internal/core/tools/handlers.go,
//     internal/core/tools/f1_f4_f5_machine_interface_regression_test.go:
//     code / test comments that name the legacy tool for traceability.
//   - changelog.md, docs/archive/**, agent_installation/*/VALIDATION-2026-08-19.md,
//     agent_installation/mpm-hermes/SKILL.md: historical record.
package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// retdName is the literal string the test scans for. Kept as a
// constant so a future rename of the retired tool would only require
// updating this single line.
const retdName = "mpm_session"

// whitelist path prefixes (relative to the repo root) that may
// reference the retired name without failing the drift guard.
var whitelistPrefixes = []string{
	// Runtime safety net — must keep the legacy name in its docstring.
	"cmd/mpm/call.go",
	"cmd/mpm/f1_call_bridge_regression_test.go",

	// Code / test comments that name the legacy tool for traceability.
	"internal/core/handoff.go",
	"internal/core/tools/handlers.go",
	"internal/core/tools/f1_f4_f5_machine_interface_regression_test.go",

	// Historical record — changelog, archive, validation logs.
	"changelog.md",
	"docs/archive/",
	"agent_installation/mpm-claude-code/VALIDATION-2026-08-19.md",
	"agent_installation/mpm-opencode/VALIDATION-2026-08-19.md",
	"agent_installation/mpm-memory-openclaw/VALIDATION-2026-08-19.md",
	"agent_installation/mpm-hermes/SKILL.md",

	// This test itself references the retired name to explain what it
	// is guarding against.
	"cmd/mpm/template_drift_test.go",
}

// driftScanPaths is the set of files this test scans. Listed
// explicitly rather than walking the whole repo so a stray reference
// in an unrelated file (a personal note, a vendored dep) does not
// false-positive — and so adding a new operational surface requires
// an explicit decision to extend this list.
var driftScanPaths = []string{
	// Plugin MCP tool registrations (the highest-risk drift source —
	// not regenerated by any installer; hand-edited only).
	"agent_installation/mpm-opencode/src/index.ts",
	"agent_installation/mpm-pi/index.ts",

	// Instruction templates installed into the user's working files.
	"agent_installation/mpm-claude-code/templates/CLAUDE.md.snippet",
	"agent_installation/mpm-hermes/templates/hermes.md.snippet",
	"agent_installation/mpm-opencode/templates/AGENTS.md.snippet",
	"agent_installation/mpm-pi/templates/AGENTS.md.snippet",

	// User-visible operational documentation.
	"agent_installation/INSTALL.md",
	"agent_installation/mpm-claude-code/README.md",
	"agent_installation/mpm-opencode/README.md",
	"agent_installation/mpm-pi/README.md",

	// Claude Code integration verify script — must drive the live
	// contract, not the legacy alias.
	"agent_installation/mpm-claude-code/verify.py",

	// Technical specification. The auto-generated block at the
	// <!-- tools:begin/end --> sentinels has no fenced marker the
	// test can target — scan the whole file.
	"README.md",
	"docs/SPEC.md",
}

// isWhitelisted reports whether the given repo-relative path is
// allowed to reference retdName. Whitelist is matched as a full path
// or as a path-prefix (for directories like docs/archive/).
func isWhitelisted(relPath string) bool {
	for _, w := range whitelistPrefixes {
		if relPath == w {
			return true
		}
		if strings.HasSuffix(w, "/") && strings.HasPrefix(relPath, w) {
			return true
		}
	}
	return false
}

// repoRootFromTest resolves the repo root by walking up from this
// test's source file until it finds go.mod. Hardcoding the path
// would break across checkouts.
func repoRootFromTest(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("could not locate repo root from %s", dir)
	return ""
}

// TestNoRetiredMpmSessionReferences is the drift guard. It scans the
// operational surface listed in driftScanPaths and fails if any
// non-whitelisted file contains the literal retdName string. The
// whitelist allows the runtime safety net and legitimate historical
// references; everything else must use mpm_handoff / mpm_scratchpad.
func TestNoRetiredMpmSessionReferences(t *testing.T) {
	root := repoRootFromTest(t)
	var offenders []string
	for _, rel := range driftScanPaths {
		abs := filepath.Join(root, rel)
		data, err := os.ReadFile(abs)
		if err != nil {
			t.Errorf("scan target missing or unreadable: %s (%v)", rel, err)
			offenders = append(offenders, rel+" (read error)")
			continue
		}
		if isWhitelisted(rel) {
			continue
		}
		// Boundary-aware match: a retired name flagged only when it
		// appears as a complete identifier (see isStandaloneIdentified
		// for the rule and the test cases below for the contract).
		// Substrings of longer names — mpm_session_id,
		// mpm_session_ids, some_mpm_session_helper — are not retired
		// tool references, they are valid current symbols.
		if lineNo, snippet, hit := findOccurrence(string(data), retdName); hit {
			offenders = append(offenders,
				rel+":"+lineNoString(lineNo)+": "+snippet)
		}
	}
	if len(offenders) > 0 {
		t.Fatalf("drift guard: %d operational surface file(s) still reference the retired tool %q:\n  %s\n\n"+
			"Fix the source/template (not just one installed copy) so future installer runs regenerate clean. "+
			"If the reference is intentional, add the path to whitelistPrefixes with a comment explaining why.",
			len(offenders), retdName, strings.Join(offenders, "\n  "))
	}
}

// findOccurrence reports the first 1-based line number containing
// needle as a complete identifier (per the lexical rule used by
// isStandaloneIdentified), along with a trimmed snippet. Returns
// hit=false if not found.
//
// The lexical rule is the contract: mpm_session_id, mpm_session_ids,
// some_mpm_session_helper, and mpm_session2 are NOT standalone
// references to the retired tool name — they are longer identifiers
// that share a prefix with it. A drift guard that flags them would
// block legitimate current code, which is the defect this function
// fixes.
func findOccurrence(haystack, needle string) (int, string, bool) {
	for i, line := range strings.Split(haystack, "\n") {
		if isStandaloneIdentified(line, needle) {
			snippet := strings.TrimSpace(line)
			if len(snippet) > 160 {
				snippet = snippet[:160] + "…"
			}
			return i + 1, snippet, true
		}
	}
	return 0, "", false
}

// isStandaloneIdentified reports whether needle appears in line as a
// complete identifier — bounded on both sides by a non-identifier
// character (or by the line edge).
//
// Identifier characters are ASCII letters, digits, and underscore. The
// set is the one Go uses for identifiers, which matches the
// snake_case/camelCase the rest of this repo names its symbols with.
// Prose like `mpm_session`, "mpm_session", mpm_session(…) matches
// because backtick, quote, and open-paren are not identifier chars;
// longer names like mpm_session_id do not, because the character
// following `_` is itself an identifier character.
func isStandaloneIdentified(line, needle string) bool {
	if needle == "" {
		return false
	}
	for i := 0; i+len(needle) <= len(line); {
		j := strings.Index(line[i:], needle)
		if j < 0 {
			return false
		}
		j += i
		end := j + len(needle)
		leftOK := j == 0 || !isIdentByte(line[j-1])
		rightOK := end == len(line) || !isIdentByte(line[end])
		if leftOK && rightOK {
			return true
		}
		i = end
	}
	return false
}

// isIdentByte reports whether b is a Go identifier character. Pulled
// into a helper so the boundary rule has one definition that both the
// matcher and the regression tests reference.
func isIdentByte(b byte) bool {
	return (b >= 'a' && b <= 'z') ||
		(b >= 'A' && b <= 'Z') ||
		(b >= '0' && b <= '9') ||
		b == '_'
}

// lineNoString is a tiny local helper to keep this file stdlib-only without
// pulling strconv just for line numbers.
func lineNoString(n int) string {
	if n == 0 {
		return "0"
	}
	var b [20]byte
	pos := len(b)
	neg := n < 0
	if neg {
		n = -n
	}
	for n > 0 {
		pos--
		b[pos] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		pos--
		b[pos] = '-'
	}
	return string(b[pos:])
}

// ==================== isStandaloneIdentified contract ====================
//
// Pin the boundary rule as a contract test. The main drift guard
// depends on this matcher behaving the same way across the whole
// repo, so the test cases here are the operational definition of
// "what counts as a retired tool reference".
//
// MUST match (drift guard must flag):
//   - the bare retired name in prose,
//   - backticked / quoted forms, because that is how documentation
//     and chat-style callouts reference a tool name,
//   - call-style references (mpm_session(…)) and tool-list references
//     (tool: mpm_session).
//
// MUST NOT match (legitimate current code):
//   - longer names that share a prefix: mpm_session_id,
//     mpm_session_ids, mpm_session2, some_mpm_session_helper. These
//     are real identifiers that contain the retired name as a prefix
//     or substring; flagging them is the defect the new matcher fixes.
func TestIsStandaloneIdentified_BoundaryContract(t *testing.T) {
	cases := []struct {
		name  string
		line  string
		want  bool
	}{
		// MUST match — bare retired name in prose.
		{"bare-name", "the retired mpm_session tool must not appear", true},
		{"bare-name-edge", "mpm_session", true},
		{"bare-name-leading-space", " (mpm_session)", true},
		{"bare-name-trailing-punct", "see mpm_session.", true},
		{"bare-name-trailing-comma", "see mpm_session, mpm_wakes", true},

		// MUST match — quoted / backticked forms in docs and chat.
		{"backticked", "retired `mpm_session` interface must not be wired", true},
		{"double-quoted", `migrate "mpm_session" to mpm_handoff`, true},
		{"single-quoted", "the 'mpm_session' surface", true},
		{"call-style", "resolveLegacySessionAlias(\"mpm_session\", …)", true},
		{"tool-prefix", "tool: mpm_session", true},
		{"heading", "## mpm_session status", true},

		// MUST NOT match — longer identifiers that contain the
		// retired name as a prefix or substring.
		{"mpm_session_id", "store carries mpm_session_id against active.json", false},
		{"mpm_session_ids", "multiple mpm_session_ids in one batch", false},
		{"some_mpm_session_helper", "calls into some_mpm_session_helper with the handoff", false},
		{"mpm_session2", "the mpm_session2 migration rolled out", false},
		{"mpm_sessionx", "no mpm_sessionx identifier exists; this is a fixture", false},

		// MUST NOT match — short identifiers, exactly the failure
		// mode the live SPEC.md and README.md used to trip the guard
		// with.
		{"spec-id-only", "`mpm_session_id` against its own database's active.json — never", false},
		{"readme-id-only", "`mpm_session_id` against its own database's active.json — never", false},

		// MUST NOT match — empty / pathological inputs.
		{"empty-needle-called", "", false}, // never true regardless of line
		{"needle-not-in-line", "no relevant reference here", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := isStandaloneIdentified(tc.line, retdName); got != tc.want {
				t.Errorf("isStandaloneIdentified(%q, %q) = %v, want %v", tc.line, retdName, got, tc.want)
			}
		})
	}
}

// TestIsStandaloneIdentified_RealSourceFixture pins the contract
// against an actual source-line fixture so a future change to the
// matcher cannot quietly regress the SPEC.md / README.md case that
// motivated this work.
func TestIsStandaloneIdentified_RealSourceFixture(t *testing.T) {
	// Taken verbatim from docs/SPEC.md:2774 (pre-edit) and the same
	// reference after the HITL documentation work moved the line
	// range. The boundary matcher must let this line pass.
	const specLine = "`mpm_session_id` against its own database's `active.json` — never"
	if isStandaloneIdentified(specLine, retdName) {
		t.Errorf("SPEC.md fixture wrongly flagged; matcher regressed to substring semantics")
	}

	// The same line with the legitimate field replaced by the actual
	// retired name must NOT pass — that is the boundary the guard
	// exists to enforce.
	const badLine = "`mpm_session` against its own database's `active.json` — never"
	if !isStandaloneIdentified(badLine, retdName) {
		t.Errorf("Synthetic retrospective test still catches the retired name; matcher regressed")
	}
}
